$axure.loadCurrentPage({
  "url":"主页.html",
  "generationDate":new Date(1417677944148.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"462d80f74b70480a8b092cd38792c5d0",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9249134dadcc4eb28e6cd07df0ec7d10",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":30},
            "size":{
              "width":320,
              "height":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33c984b0d987459c835afb7341600748",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":30},
                "size":{
                  "width":320,
                  "height":470}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"604e72e038574f799aa89ca3916e3c6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"99px",
            "location":{
              "x":363,
              "y":106},
            "size":{
              "width":61,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8247bee3b0244d1aec4e4e3aec4c576",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"99px",
                "location":{
                  "x":363,
                  "y":106},
                "size":{
                  "width":61,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"467edb2dbcbc4e13a22ac4342ba3ae4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":420,
              "y":158},
            "size":{
              "width":73,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d77d72b56516417e946832d81d68719e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":420,
                  "y":158},
                "size":{
                  "width":73,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2d7e1208463408194db2c58d5d9c46c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":356,
              "y":252},
            "size":{
              "width":174,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c6ae897addc2470aa10d0d769a860a26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":256},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e10511667954207b955021d5020a267",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":256},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab9eb2b677fb471f8d4a0aed467c4e20",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":356,
              "y":295},
            "size":{
              "width":174,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"48c5e64a8dba47fab8faaa9c0d490ddc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":299},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d70368a29b854ffebc131793d6ae2634",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":299},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3141f87e1a964251b125b2c9acbbee8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":373,
              "y":360},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa1213e0685e4683b122877e05811f48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":373,
                  "y":360},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 日程",
                      "target":{
                        "targetType":"page",
                        "url":"日程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u12.png"}},
{
          "id":"45b56b6c97714d96bd973be96cd6aea0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":477,
              "y":374},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04ca5bba70064ab0bef5cefc76ac4160",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":477,
                  "y":374},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "9249134dadcc4eb28e6cd07df0ec7d10":{
      "scriptId":"u0"},
    "33c984b0d987459c835afb7341600748":{
      "scriptId":"u1"},
    "604e72e038574f799aa89ca3916e3c6d":{
      "scriptId":"u2"},
    "f8247bee3b0244d1aec4e4e3aec4c576":{
      "scriptId":"u3"},
    "467edb2dbcbc4e13a22ac4342ba3ae4e":{
      "scriptId":"u4"},
    "d77d72b56516417e946832d81d68719e":{
      "scriptId":"u5"},
    "c2d7e1208463408194db2c58d5d9c46c":{
      "scriptId":"u6"},
    "c6ae897addc2470aa10d0d769a860a26":{
      "scriptId":"u7"},
    "8e10511667954207b955021d5020a267":{
      "scriptId":"u8"},
    "ab9eb2b677fb471f8d4a0aed467c4e20":{
      "scriptId":"u9"},
    "48c5e64a8dba47fab8faaa9c0d490ddc":{
      "scriptId":"u10"},
    "d70368a29b854ffebc131793d6ae2634":{
      "scriptId":"u11"},
    "3141f87e1a964251b125b2c9acbbee8f":{
      "scriptId":"u12"},
    "aa1213e0685e4683b122877e05811f48":{
      "scriptId":"u13"},
    "45b56b6c97714d96bd973be96cd6aea0":{
      "scriptId":"u14"},
    "04ca5bba70064ab0bef5cefc76ac4160":{
      "scriptId":"u15"}}});