$axure.loadCurrentPage({
  "url":"流程新.html",
  "generationDate":new Date(1415687654803.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8a7537c4b5a94a5982fa988de0e69d2e",
    "type":"Axure:Page",
    "name":"流程新",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"56d91e246a5d43599465731298d0c95c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":102,
              "y":11},
            "size":{
              "width":794,
              "height":1487}},
          "adaptiveStyles":{
},
          "masterId":"984fa132bdee4430802a486dd3e5c298"},
{
          "id":"536d0d100dca4134ab06fed9ada44ef8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":181,
              "y":1140},
            "size":{
              "width":643,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"724ebb9bb0b14046b17dd5c09ee35313",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":181,
                  "y":1140},
                "size":{
                  "width":643,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程新/u21.png"}},
{
          "id":"46fcf42d70f141fa9925795c82013b9b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":1147},
            "size":{
              "width":97,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a0169d35fca4f8893de9f6373e442a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":1147},
                "size":{
                  "width":97,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程新/u23.png"}},
{
          "id":"13b50a344b1b43d4b308bbbed7fe1dc7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":438,
              "y":1143},
            "size":{
              "width":95,
              "height":94}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee54a70fb6ab4f2fa25d1daa69c85048",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":438,
                  "y":1143},
                "size":{
                  "width":95,
                  "height":94}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程新/u25.png"}},
{
          "id":"1efd341041db4ba8a133bcdae5b46164",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":660,
              "y":1144},
            "size":{
              "width":98,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"509974f981314ac0b9db1d11cbbb2038",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":660,
                  "y":1144},
                "size":{
                  "width":98,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程新/u27.png"}},
{
          "id":"f462e4e48ae743399d739a75bc0820ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "location":{
              "x":181,
              "y":370},
            "size":{
              "width":643,
              "height":770},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94f02d1086ee4ec5b9d7a4cb1d14bfb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "location":{
                  "x":181,
                  "y":370},
                "size":{
                  "width":643,
                  "height":770},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程新/u29.png"}},
{
          "id":"9a5deaca854a477282ee9303dd679f37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":550},
            "size":{
              "width":554,
              "height":478}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f46f1315858b4c7c8748a5d337f61473",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":236,
                  "y":550},
                "size":{
                  "width":554,
                  "height":478}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程新/u31.png"}},
{
          "id":"7b4e663c77f14bf78408223775cb6cc4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":314},
            "size":{
              "width":643,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46ad6b27f9fd442f8a3bafa5b605b3a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":181,
                  "y":314},
                "size":{
                  "width":643,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程新/u33.png"}},
{
          "id":"46434533c58a4b28931531f25dd28061",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":319.5},
            "size":{
              "width":54,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92cef07cb93441bc8d186246b7ff6a7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":760,
                  "y":319.5},
                "size":{
                  "width":54,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 切换状态",
                      "target":{
                        "targetType":"page",
                        "url":"切换状态.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/流程新/u35.png"}},
{
          "id":"f97cdce5d42f4c4aa01341d28a866b1d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":323},
            "size":{
              "width":121,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ce958c1c27f4e9991cf00d8de1ef28e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":323},
                "size":{
                  "width":121,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程新/u37.png"}},
{
          "id":"ba3ed01c864a4d7dbe7282d0d303381b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":321},
            "size":{
              "width":56,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb48195f545d4eea83c5df4e226dc6cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":321},
                "size":{
                  "width":56,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程新/u39.png"}},
{
          "id":"005dcf8832234997a86d607866dd6943",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":385},
            "size":{
              "width":542,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fca390ad1d8040c480b0518ac1bff151",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":385},
                "size":{
                  "width":542,
                  "height":155}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程新/u41.png"}},
{
          "id":"2a56a604a41e41909995438ce879ea46",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF434343,
              "opacity":1},
            "location":{
              "x":620,
              "y":692},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0f84f6797c04bdca491e6b0081ad6ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF434343,
                  "opacity":1},
                "location":{
                  "x":620,
                  "y":692},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e734b557eec74c71be6523b4c27d64e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF434343,
              "opacity":1},
            "location":{
              "x":620,
              "y":842},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cf280c068f246ad8a5a3e373197e1ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF434343,
                  "opacity":1},
                "location":{
                  "x":620,
                  "y":842},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"928df0bd189a41a88588aac17308a996",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":320,
              "y":692},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e79cff07289148b5bcad403cb888a968",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":692},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"feddad8a430d477b98b1b8e96ded1867",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":466,
              "y":692},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14a44abc3802417db9806635afe29cb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":466,
                  "y":692},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5b7cb0da88a454a9b4f6f9833a51ef8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":320,
              "y":842},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd7c18326ff14e5383b04074c1eb9fc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":842},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2ad44fbac5c4b82879cd5e14a495290",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":466,
              "y":842},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52f4d0c6532540fb99f33aa457c0c5cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":466,
                  "y":842},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "984fa132bdee4430802a486dd3e5c298":{
      "packageId":"984fa132bdee4430802a486dd3e5c298",
      "type":"Axure:Master",
      "name":"shoujixin",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0924992c31c149048016d672e5c7f726",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":794,
                "height":1487},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18279859f5f846ce8c3645a511e3061b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":794,
                    "height":1487},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u0.jpg"}},
{
            "id":"70f92109e52a40af94df453ebb3e8fd2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":307},
              "size":{
                "width":640,
                "height":822},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1a0f733bad824f2595138b3ed7ed226f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":80,
                    "y":307},
                  "size":{
                    "width":640,
                    "height":822},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u2.png"}},
{
            "id":"afaeff7a64e54c80962de48a01e9fe2c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":1129},
              "size":{
                "width":640,
                "height":97},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"74df996240be4f2eae72b660a9d138d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":80,
                    "y":1129},
                  "size":{
                    "width":640,
                    "height":97},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u4.png"}},
{
            "id":"ad28bbac596b43b58a7b09fd8c61d066",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":368,
                "y":1139},
              "size":{
                "width":39,
                "height":36},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fd172ca0c7684ee3a771250caa2a4708",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":368,
                    "y":1139},
                  "size":{
                    "width":39,
                    "height":36},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u6.png"}},
{
            "id":"00913d450cdc4fcaa0b8e0987daf0158",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":580,
                "y":1141},
              "size":{
                "width":39,
                "height":33},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"23e12321df4e4b8e918b93a4238c0b2e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":580,
                    "y":1141},
                  "size":{
                    "width":39,
                    "height":33},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u8.png"}},
{
            "id":"6aff273e7ae443acaad54ef5d53ef650",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":175,
                "y":1143},
              "size":{
                "width":38,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"895a51871df84fdeb64de494f9ded835",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":175,
                    "y":1143},
                  "size":{
                    "width":38,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u10.png"}},
{
            "id":"f64805ae112045e2acbffd535c1532ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":327,
                "y":1134},
              "size":{
                "width":123,
                "height":92},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"46456e5bf1a64ccf8f309dbbddbdde36",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":327,
                    "y":1134},
                  "size":{
                    "width":123,
                    "height":92},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"153adc10da0545eb85d07f4f4553ba83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":539,
                "y":1134},
              "size":{
                "width":123,
                "height":92},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2071049e0e8d4b418468c9a8514ed7e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":539,
                    "y":1134},
                  "size":{
                    "width":123,
                    "height":92},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登陆页",
                        "target":{
                          "targetType":"page",
                          "url":"登陆页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bb67617ebb764a5ba40a60393669df03",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":132,
                "y":1129},
              "size":{
                "width":123,
                "height":92},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"35fcb7f3ba564c56a8900c8c914f3812",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":132,
                    "y":1129},
                  "size":{
                    "width":123,
                    "height":92},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 聊天",
                        "target":{
                          "targetType":"page",
                          "url":"聊天.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ca7ebea22b8a48e9a088034eb7d63cfb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFF0000},
              "location":{
                "x":223,
                "y":1139},
              "size":{
                "width":11,
                "height":11},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24509502b78240de82bb50d987c9e129",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF0000},
                  "location":{
                    "x":223,
                    "y":1139},
                  "size":{
                    "width":11,
                    "height":11},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/确定施工方式简介/u19.png"}}]}}},
  "objectPaths":{
    "56d91e246a5d43599465731298d0c95c":{
      "scriptId":"u0",
      "0924992c31c149048016d672e5c7f726":{
        "scriptId":"u1"},
      "18279859f5f846ce8c3645a511e3061b":{
        "scriptId":"u2"},
      "70f92109e52a40af94df453ebb3e8fd2":{
        "scriptId":"u3"},
      "1a0f733bad824f2595138b3ed7ed226f":{
        "scriptId":"u4"},
      "afaeff7a64e54c80962de48a01e9fe2c":{
        "scriptId":"u5"},
      "74df996240be4f2eae72b660a9d138d3":{
        "scriptId":"u6"},
      "ad28bbac596b43b58a7b09fd8c61d066":{
        "scriptId":"u7"},
      "fd172ca0c7684ee3a771250caa2a4708":{
        "scriptId":"u8"},
      "00913d450cdc4fcaa0b8e0987daf0158":{
        "scriptId":"u9"},
      "23e12321df4e4b8e918b93a4238c0b2e":{
        "scriptId":"u10"},
      "6aff273e7ae443acaad54ef5d53ef650":{
        "scriptId":"u11"},
      "895a51871df84fdeb64de494f9ded835":{
        "scriptId":"u12"},
      "f64805ae112045e2acbffd535c1532ea":{
        "scriptId":"u13"},
      "46456e5bf1a64ccf8f309dbbddbdde36":{
        "scriptId":"u14"},
      "153adc10da0545eb85d07f4f4553ba83":{
        "scriptId":"u15"},
      "2071049e0e8d4b418468c9a8514ed7e2":{
        "scriptId":"u16"},
      "bb67617ebb764a5ba40a60393669df03":{
        "scriptId":"u17"},
      "35fcb7f3ba564c56a8900c8c914f3812":{
        "scriptId":"u18"},
      "ca7ebea22b8a48e9a088034eb7d63cfb":{
        "scriptId":"u19"},
      "24509502b78240de82bb50d987c9e129":{
        "scriptId":"u20"}},
    "536d0d100dca4134ab06fed9ada44ef8":{
      "scriptId":"u21"},
    "724ebb9bb0b14046b17dd5c09ee35313":{
      "scriptId":"u22"},
    "46fcf42d70f141fa9925795c82013b9b":{
      "scriptId":"u23"},
    "5a0169d35fca4f8893de9f6373e442a2":{
      "scriptId":"u24"},
    "13b50a344b1b43d4b308bbbed7fe1dc7":{
      "scriptId":"u25"},
    "ee54a70fb6ab4f2fa25d1daa69c85048":{
      "scriptId":"u26"},
    "1efd341041db4ba8a133bcdae5b46164":{
      "scriptId":"u27"},
    "509974f981314ac0b9db1d11cbbb2038":{
      "scriptId":"u28"},
    "f462e4e48ae743399d739a75bc0820ff":{
      "scriptId":"u29"},
    "94f02d1086ee4ec5b9d7a4cb1d14bfb9":{
      "scriptId":"u30"},
    "9a5deaca854a477282ee9303dd679f37":{
      "scriptId":"u31"},
    "f46f1315858b4c7c8748a5d337f61473":{
      "scriptId":"u32"},
    "7b4e663c77f14bf78408223775cb6cc4":{
      "scriptId":"u33"},
    "46ad6b27f9fd442f8a3bafa5b605b3a3":{
      "scriptId":"u34"},
    "46434533c58a4b28931531f25dd28061":{
      "scriptId":"u35"},
    "92cef07cb93441bc8d186246b7ff6a7c":{
      "scriptId":"u36"},
    "f97cdce5d42f4c4aa01341d28a866b1d":{
      "scriptId":"u37"},
    "7ce958c1c27f4e9991cf00d8de1ef28e":{
      "scriptId":"u38"},
    "ba3ed01c864a4d7dbe7282d0d303381b":{
      "scriptId":"u39"},
    "eb48195f545d4eea83c5df4e226dc6cf":{
      "scriptId":"u40"},
    "005dcf8832234997a86d607866dd6943":{
      "scriptId":"u41"},
    "fca390ad1d8040c480b0518ac1bff151":{
      "scriptId":"u42"},
    "2a56a604a41e41909995438ce879ea46":{
      "scriptId":"u43"},
    "a0f84f6797c04bdca491e6b0081ad6ff":{
      "scriptId":"u44"},
    "e734b557eec74c71be6523b4c27d64e9":{
      "scriptId":"u45"},
    "9cf280c068f246ad8a5a3e373197e1ef":{
      "scriptId":"u46"},
    "928df0bd189a41a88588aac17308a996":{
      "scriptId":"u47"},
    "e79cff07289148b5bcad403cb888a968":{
      "scriptId":"u48"},
    "feddad8a430d477b98b1b8e96ded1867":{
      "scriptId":"u49"},
    "14a44abc3802417db9806635afe29cb1":{
      "scriptId":"u50"},
    "d5b7cb0da88a454a9b4f6f9833a51ef8":{
      "scriptId":"u51"},
    "bd7c18326ff14e5383b04074c1eb9fc5":{
      "scriptId":"u52"},
    "f2ad44fbac5c4b82879cd5e14a495290":{
      "scriptId":"u53"},
    "52f4d0c6532540fb99f33aa457c0c5cf":{
      "scriptId":"u54"}}});