$axure.loadCurrentPage({
  "url":"聊天.html",
  "generationDate":new Date(1414464499810),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e4f542841665452b8c52a6b8ffaac2dc",
    "type":"Axure:Page",
    "name":"聊天",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ed16615b27124015a73a601b8e9048b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":10},
            "size":{
              "width":794,
              "height":1487},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b02eda15b20f4f119e063d420572e110",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":10},
                "size":{
                  "width":794,
                  "height":1487},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.jpg"}},
{
          "id":"222b21fef4934b2793725ec334ebc489",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":317},
            "size":{
              "width":640,
              "height":822},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71f2bc9757094eac8ce0677bdcd07db5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":181,
                  "y":317},
                "size":{
                  "width":640,
                  "height":822},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u2.png"}},
{
          "id":"6ed88515c1424f7d8e5d8dc08d038d9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":324,
              "y":1149},
            "size":{
              "width":11,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6df9eb6b5234fa5811f68282301adfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":324,
                  "y":1149},
                "size":{
                  "width":11,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确定施工方式简介/u19.png"}},
{
          "id":"13f691b451f840c1a8a4a3ea312d7f2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "location":{
              "x":181,
              "y":957.5},
            "size":{
              "width":641,
              "height":275},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"238a1c2781c14490bd0ae805c26ec821",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "location":{
                  "x":181,
                  "y":957.5},
                "size":{
                  "width":641,
                  "height":275},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u6.png"}},
{
          "id":"b08c236937614f198bfe37842b922cfb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":315},
            "size":{
              "width":642,
              "height":645}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab25cde73b624a06b6a6cbe667a34de5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":181,
                  "y":315},
                "size":{
                  "width":642,
                  "height":645}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u8.png"}},
{
          "id":"4f9dad3d53804238997d9a3bc1694f1d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":1147},
            "size":{
              "width":641,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fd1d863811e4ae79434797feeea77d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":181,
                  "y":1147},
                "size":{
                  "width":641,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u10.png"}},
{
          "id":"d5bee4cf92b3456dbd5a87f3c6e923c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":260,
              "y":1156},
            "size":{
              "width":471,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13a7a7265fe54b6cbb77bca7e55e7dc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":260,
                  "y":1156},
                "size":{
                  "width":471,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 键盘",
                      "objectsToFades":[{
                          "objectPath":["e43eab17e1864fa4977a75dd77032696"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 语音,<br>+",
                      "objectsToFades":[{
                          "objectPath":["aac1b193f5f44f52a0633b975e114d4f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1a7103f2cdce4b678eb32c035500df3b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 键盘 to 状态1 向上滑动 in 1000ms",
                      "panelsToStates":[{
                          "panelPath":["e43eab17e1864fa4977a75dd77032696"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateIn":{
                                "easing":"slideUp",
                                "duration":1000},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"579d1d17e09649028aefbc803c1ba128",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":761,
              "y":1156},
            "size":{
              "width":44,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d59537a3cb6f488aa6f8ad9becccd0a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":761,
                  "y":1156},
                "size":{
                  "width":44,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 语音",
                      "objectsToFades":[{
                          "objectPath":["aac1b193f5f44f52a0633b975e114d4f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 键盘,<br>+",
                      "objectsToFades":[{
                          "objectPath":["e43eab17e1864fa4977a75dd77032696"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1a7103f2cdce4b678eb32c035500df3b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/聊天/u14.png"}},
{
          "id":"24362fb201954a8bb76b779a04009b1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"bold",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":190,
              "y":325},
            "size":{
              "width":60,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d06b44c88fa4b7bbacb214fa20325d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"bold",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":190,
                  "y":325},
                "size":{
                  "width":60,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3a2aa1646ab476b9439a65421a356ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":181,
              "y":373},
            "size":{
              "width":639,
              "height":367},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c2fcb1b60d48adb142b946f2aa5d3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":181,
                  "y":373},
                "size":{
                  "width":639,
                  "height":367},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 键盘,<br>语音,<br>+",
                      "objectsToFades":[{
                          "objectPath":["e43eab17e1864fa4977a75dd77032696"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["aac1b193f5f44f52a0633b975e114d4f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1a7103f2cdce4b678eb32c035500df3b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0307d7e5e77441184c37c2a17d0048d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":201,
              "y":1164},
            "size":{
              "width":49,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc01fdb8a5e14ac8b546a293a4e4aba2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":201,
                  "y":1164},
                "size":{
                  "width":49,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 +",
                      "objectsToFades":[{
                          "objectPath":["1a7103f2cdce4b678eb32c035500df3b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 键盘,<br>语音",
                      "objectsToFades":[{
                          "objectPath":["e43eab17e1864fa4977a75dd77032696"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["aac1b193f5f44f52a0633b975e114d4f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 键盘 to 状态1 向上滑动 in 1000ms",
                      "panelsToStates":[{
                          "panelPath":["e43eab17e1864fa4977a75dd77032696"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateIn":{
                                "easing":"slideUp",
                                "duration":1000},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce085b87b857446c903c14c6f990f58f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":399},
            "size":{
              "width":634,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e75b8fe35ebe4f638ba387330668a263",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":186,
                  "y":399},
                "size":{
                  "width":634,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u22.png"}},
{
          "id":"74b13033ba38475cba4dad42d6e7776e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":183,
              "y":680},
            "size":{
              "width":639,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d604ff9d31b48a1a692d076c8f3db19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":183,
                  "y":680},
                "size":{
                  "width":639,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u24.png"}},
{
          "id":"e43eab17e1864fa4977a75dd77032696",
          "label":"键盘",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":181,
              "y":740},
            "size":{
              "width":639,
              "height":494},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e2c936953a644fc48a094dda93dad849",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b20336c4ef2140f4a20b1266eb51bd78",
                  "label":"",
                  "parentDynamicPanel":"e43eab17e1864fa4977a75dd77032696",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":87},
                    "size":{
                      "width":636,
                      "height":403},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c42f5764715e4ea7acedc8a8c4bff481",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e43eab17e1864fa4977a75dd77032696",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":87},
                        "size":{
                          "width":636,
                          "height":403},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/聊天/u27.png"}},
{
                  "id":"ba8538562ac74c998467075ea231a6df",
                  "label":"",
                  "parentDynamicPanel":"e43eab17e1864fa4977a75dd77032696",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-5,
                      "y":0},
                    "size":{
                      "width":641,
                      "height":87}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e1b5db64180a448a92aff3477031cd7d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e43eab17e1864fa4977a75dd77032696",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-5,
                          "y":0},
                        "size":{
                          "width":641,
                          "height":87}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/聊天/u10.png"}},
{
                  "id":"0e7fba571f1e46e78dcdc1f8e566e3fe",
                  "label":"",
                  "parentDynamicPanel":"e43eab17e1864fa4977a75dd77032696",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":75,
                      "y":9},
                    "size":{
                      "width":471,
                      "height":66},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9d954c048b9243a09dc93c1b5f6f811a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e43eab17e1864fa4977a75dd77032696",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":75,
                          "y":9},
                        "size":{
                          "width":471,
                          "height":66},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 键盘",
                              "objectsToFades":[{
                                  "objectPath":["e43eab17e1864fa4977a75dd77032696"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"setPanelState",
                              "description":"设置 键盘 to 状态1 向上滑动 in 1000ms",
                              "panelsToStates":[{
                                  "panelPath":["e43eab17e1864fa4977a75dd77032696"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateIn":{
                                        "easing":"slideUp",
                                        "duration":1000},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"63926d10575349e09d2b520f5ca27d10",
                  "label":"",
                  "parentDynamicPanel":"e43eab17e1864fa4977a75dd77032696",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":10,
                      "y":19},
                    "size":{
                      "width":55,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"043f4c15f7c249ce989b66edd3fe41e0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e43eab17e1864fa4977a75dd77032696",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":10,
                          "y":19},
                        "size":{
                          "width":55,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 +",
                              "objectsToFades":[{
                                  "objectPath":["1a7103f2cdce4b678eb32c035500df3b"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 键盘,<br>语音",
                              "objectsToFades":[{
                                  "objectPath":["e43eab17e1864fa4977a75dd77032696"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["aac1b193f5f44f52a0633b975e114d4f"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"setPanelState",
                              "description":"设置 键盘 to 状态1 向上滑动 in 1000ms",
                              "panelsToStates":[{
                                  "panelPath":["e43eab17e1864fa4977a75dd77032696"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateIn":{
                                        "easing":"slideUp",
                                        "duration":1000},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f174e97950e841109652730007d4d13c",
                  "label":"",
                  "parentDynamicPanel":"e43eab17e1864fa4977a75dd77032696",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":575,
                      "y":10},
                    "size":{
                      "width":44,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6bce531095ce4029b203f14344fd244b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e43eab17e1864fa4977a75dd77032696",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":575,
                          "y":10},
                        "size":{
                          "width":44,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 语音",
                              "objectsToFades":[{
                                  "objectPath":["aac1b193f5f44f52a0633b975e114d4f"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 键盘,<br>+",
                              "objectsToFades":[{
                                  "objectPath":["e43eab17e1864fa4977a75dd77032696"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["1a7103f2cdce4b678eb32c035500df3b"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/聊天/u14.png"}}]}]},
{
          "id":"aac1b193f5f44f52a0633b975e114d4f",
          "label":"语音",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":182,
              "y":740},
            "size":{
              "width":639,
              "height":493},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ddbc2fbe7cab4e3f81d5a5ff1335baf2",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2f3676705d8f454fbbc1bc28e6c328de",
                  "label":"",
                  "parentDynamicPanel":"aac1b193f5f44f52a0633b975e114d4f",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-5,
                      "y":0},
                    "size":{
                      "width":641,
                      "height":87}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"98a135794b5e419e854c38c477168940",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aac1b193f5f44f52a0633b975e114d4f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-5,
                          "y":0},
                        "size":{
                          "width":641,
                          "height":87}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/聊天/u10.png"}},
{
                  "id":"646fabdfdc684d95a90a74ae11ff5902",
                  "label":"",
                  "parentDynamicPanel":"aac1b193f5f44f52a0633b975e114d4f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":75,
                      "y":9},
                    "size":{
                      "width":471,
                      "height":66},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"48112946a763479c9d9ad2fc21dcf9b9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aac1b193f5f44f52a0633b975e114d4f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":75,
                          "y":9},
                        "size":{
                          "width":471,
                          "height":66},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 语音",
                              "objectsToFades":[{
                                  "objectPath":["aac1b193f5f44f52a0633b975e114d4f"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"setPanelState",
                              "description":"设置 语音 to 状态1 向上滑动 in 1000ms",
                              "panelsToStates":[{
                                  "panelPath":["aac1b193f5f44f52a0633b975e114d4f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateIn":{
                                        "easing":"slideUp",
                                        "duration":1000},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2402be72e5064bda95126e92003e03df",
                  "label":"",
                  "parentDynamicPanel":"aac1b193f5f44f52a0633b975e114d4f",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-48,
                      "y":85},
                    "size":{
                      "width":720,
                      "height":377}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8755d6a63af64c25a158854116f6efe6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aac1b193f5f44f52a0633b975e114d4f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-48,
                          "y":85},
                        "size":{
                          "width":720,
                          "height":377}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/聊天/u42.png"}},
{
                  "id":"2c63c95d5ea84edcad384bc4ef9db04b",
                  "label":"",
                  "parentDynamicPanel":"aac1b193f5f44f52a0633b975e114d4f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":450},
                    "size":{
                      "width":650,
                      "height":100},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"50d26e544c734b47a0bc9bc7edf5dcab",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aac1b193f5f44f52a0633b975e114d4f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":450},
                        "size":{
                          "width":650,
                          "height":100},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/聊天/u44.png"}},
{
                  "id":"43ba775b5e0449968b9b592cf5eb6abf",
                  "label":"",
                  "parentDynamicPanel":"aac1b193f5f44f52a0633b975e114d4f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":10,
                      "y":19},
                    "size":{
                      "width":55,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"441fb75f4d79427b95f9fb8c315ef52e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aac1b193f5f44f52a0633b975e114d4f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":10,
                          "y":19},
                        "size":{
                          "width":55,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 +",
                              "objectsToFades":[{
                                  "objectPath":["1a7103f2cdce4b678eb32c035500df3b"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 键盘,<br>语音",
                              "objectsToFades":[{
                                  "objectPath":["e43eab17e1864fa4977a75dd77032696"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["aac1b193f5f44f52a0633b975e114d4f"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"setPanelState",
                              "description":"设置 键盘 to 状态1 向上滑动 in 1000ms",
                              "panelsToStates":[{
                                  "panelPath":["e43eab17e1864fa4977a75dd77032696"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateIn":{
                                        "easing":"slideUp",
                                        "duration":1000},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c4ba0bed098d4117abe9c4fc2f887235",
                  "label":"",
                  "parentDynamicPanel":"aac1b193f5f44f52a0633b975e114d4f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":570,
                      "y":19},
                    "size":{
                      "width":55,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0c4483d294a24af784b048f0b876cb1c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"aac1b193f5f44f52a0633b975e114d4f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":570,
                          "y":19},
                        "size":{
                          "width":55,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 键盘",
                              "objectsToFades":[{
                                  "objectPath":["e43eab17e1864fa4977a75dd77032696"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 +,<br>语音",
                              "objectsToFades":[{
                                  "objectPath":["1a7103f2cdce4b678eb32c035500df3b"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["aac1b193f5f44f52a0633b975e114d4f"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"setPanelState",
                              "description":"设置 键盘 to 状态1 向上滑动 in 1000ms",
                              "panelsToStates":[{
                                  "panelPath":["e43eab17e1864fa4977a75dd77032696"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateIn":{
                                        "easing":"slideUp",
                                        "duration":1000},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"1a7103f2cdce4b678eb32c035500df3b",
          "label":"+",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":181,
              "y":740},
            "size":{
              "width":639,
              "height":493},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"eed17c083f924dc7974d69bf765bb325",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"21a37a754f744030a54f99eedf973eb0",
                  "label":"",
                  "parentDynamicPanel":"1a7103f2cdce4b678eb32c035500df3b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-5,
                      "y":0},
                    "size":{
                      "width":641,
                      "height":87}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5517f90ef2e5482182f9ba9e8341b7cd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1a7103f2cdce4b678eb32c035500df3b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-5,
                          "y":0},
                        "size":{
                          "width":641,
                          "height":87}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/聊天/u10.png"}},
{
                  "id":"acf3a827f6564f54bd8942acc6163904",
                  "label":"",
                  "parentDynamicPanel":"1a7103f2cdce4b678eb32c035500df3b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":75,
                      "y":9},
                    "size":{
                      "width":471,
                      "height":66},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"21b4601539984069a3accbcb35a3730e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1a7103f2cdce4b678eb32c035500df3b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":75,
                          "y":9},
                        "size":{
                          "width":471,
                          "height":66},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 +",
                              "objectsToFades":[{
                                  "objectPath":["1a7103f2cdce4b678eb32c035500df3b"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"setPanelState",
                              "description":"设置 + to 状态1 向上滑动 in 1000ms",
                              "panelsToStates":[{
                                  "panelPath":["1a7103f2cdce4b678eb32c035500df3b"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateIn":{
                                        "easing":"slideUp",
                                        "duration":1000},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c1693331824242598ed302c9cf0a454c",
                  "label":"",
                  "parentDynamicPanel":"1a7103f2cdce4b678eb32c035500df3b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-15,
                      "y":87},
                    "size":{
                      "width":670,
                      "height":353}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"475ee4c9094346cebf36dde5c0a6f9dd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1a7103f2cdce4b678eb32c035500df3b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-15,
                          "y":87},
                        "size":{
                          "width":670,
                          "height":353}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/聊天/u55.png"}},
{
                  "id":"7e21c36f572f4d838df99f443b2bc527",
                  "label":"",
                  "parentDynamicPanel":"1a7103f2cdce4b678eb32c035500df3b",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-130,
                      "y":432},
                    "size":{
                      "width":840,
                      "height":10},
                    "borderWidth":"5",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/聊天/u57_line.png"}},
{
                  "id":"4cfaeebf2d4b4641aec6e054e127e1f9",
                  "label":"",
                  "parentDynamicPanel":"1a7103f2cdce4b678eb32c035500df3b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-15,
                      "y":400},
                    "size":{
                      "width":695,
                      "height":130},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b527290e112e461aadf2bb816b2460b0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1a7103f2cdce4b678eb32c035500df3b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-15,
                          "y":400},
                        "size":{
                          "width":695,
                          "height":130},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/聊天/u58.png"}},
{
                  "id":"22ff446183cd469fad26de0a18ae79b7",
                  "label":"",
                  "parentDynamicPanel":"1a7103f2cdce4b678eb32c035500df3b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":10,
                      "y":19},
                    "size":{
                      "width":55,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"765a257a22934e90b47882de4f9f3bdf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1a7103f2cdce4b678eb32c035500df3b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":10,
                          "y":19},
                        "size":{
                          "width":55,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 键盘",
                              "objectsToFades":[{
                                  "objectPath":["e43eab17e1864fa4977a75dd77032696"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 语音,<br>+",
                              "objectsToFades":[{
                                  "objectPath":["aac1b193f5f44f52a0633b975e114d4f"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["1a7103f2cdce4b678eb32c035500df3b"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"setPanelState",
                              "description":"设置 键盘 to 状态1 向上滑动 in 1000ms",
                              "panelsToStates":[{
                                  "panelPath":["e43eab17e1864fa4977a75dd77032696"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateIn":{
                                        "easing":"slideUp",
                                        "duration":1000},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cdf9d5d0f29a43519ed874ef406c5d10",
                  "label":"",
                  "parentDynamicPanel":"1a7103f2cdce4b678eb32c035500df3b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":575,
                      "y":13},
                    "size":{
                      "width":44,
                      "height":63}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a3f337f0e45341478e61036b3f2559df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1a7103f2cdce4b678eb32c035500df3b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":575,
                          "y":13},
                        "size":{
                          "width":44,
                          "height":63}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 语音",
                              "objectsToFades":[{
                                  "objectPath":["aac1b193f5f44f52a0633b975e114d4f"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 键盘,<br>+",
                              "objectsToFades":[{
                                  "objectPath":["e43eab17e1864fa4977a75dd77032696"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["1a7103f2cdce4b678eb32c035500df3b"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/聊天/u14.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "ed16615b27124015a73a601b8e9048b7":{
      "scriptId":"u0"},
    "b02eda15b20f4f119e063d420572e110":{
      "scriptId":"u1"},
    "222b21fef4934b2793725ec334ebc489":{
      "scriptId":"u2"},
    "71f2bc9757094eac8ce0677bdcd07db5":{
      "scriptId":"u3"},
    "6ed88515c1424f7d8e5d8dc08d038d9d":{
      "scriptId":"u4"},
    "b6df9eb6b5234fa5811f68282301adfb":{
      "scriptId":"u5"},
    "13f691b451f840c1a8a4a3ea312d7f2f":{
      "scriptId":"u6"},
    "238a1c2781c14490bd0ae805c26ec821":{
      "scriptId":"u7"},
    "b08c236937614f198bfe37842b922cfb":{
      "scriptId":"u8"},
    "ab25cde73b624a06b6a6cbe667a34de5":{
      "scriptId":"u9"},
    "4f9dad3d53804238997d9a3bc1694f1d":{
      "scriptId":"u10"},
    "8fd1d863811e4ae79434797feeea77d3":{
      "scriptId":"u11"},
    "d5bee4cf92b3456dbd5a87f3c6e923c1":{
      "scriptId":"u12"},
    "13a7a7265fe54b6cbb77bca7e55e7dc9":{
      "scriptId":"u13"},
    "579d1d17e09649028aefbc803c1ba128":{
      "scriptId":"u14"},
    "d59537a3cb6f488aa6f8ad9becccd0a1":{
      "scriptId":"u15"},
    "24362fb201954a8bb76b779a04009b1c":{
      "scriptId":"u16"},
    "8d06b44c88fa4b7bbacb214fa20325d2":{
      "scriptId":"u17"},
    "f3a2aa1646ab476b9439a65421a356ac":{
      "scriptId":"u18"},
    "43c2fcb1b60d48adb142b946f2aa5d3b":{
      "scriptId":"u19"},
    "b0307d7e5e77441184c37c2a17d0048d":{
      "scriptId":"u20"},
    "bc01fdb8a5e14ac8b546a293a4e4aba2":{
      "scriptId":"u21"},
    "ce085b87b857446c903c14c6f990f58f":{
      "scriptId":"u22"},
    "e75b8fe35ebe4f638ba387330668a263":{
      "scriptId":"u23"},
    "74b13033ba38475cba4dad42d6e7776e":{
      "scriptId":"u24"},
    "8d604ff9d31b48a1a692d076c8f3db19":{
      "scriptId":"u25"},
    "e43eab17e1864fa4977a75dd77032696":{
      "scriptId":"u26"},
    "b20336c4ef2140f4a20b1266eb51bd78":{
      "scriptId":"u27"},
    "c42f5764715e4ea7acedc8a8c4bff481":{
      "scriptId":"u28"},
    "ba8538562ac74c998467075ea231a6df":{
      "scriptId":"u29"},
    "e1b5db64180a448a92aff3477031cd7d":{
      "scriptId":"u30"},
    "0e7fba571f1e46e78dcdc1f8e566e3fe":{
      "scriptId":"u31"},
    "9d954c048b9243a09dc93c1b5f6f811a":{
      "scriptId":"u32"},
    "63926d10575349e09d2b520f5ca27d10":{
      "scriptId":"u33"},
    "043f4c15f7c249ce989b66edd3fe41e0":{
      "scriptId":"u34"},
    "f174e97950e841109652730007d4d13c":{
      "scriptId":"u35"},
    "6bce531095ce4029b203f14344fd244b":{
      "scriptId":"u36"},
    "aac1b193f5f44f52a0633b975e114d4f":{
      "scriptId":"u37"},
    "2f3676705d8f454fbbc1bc28e6c328de":{
      "scriptId":"u38"},
    "98a135794b5e419e854c38c477168940":{
      "scriptId":"u39"},
    "646fabdfdc684d95a90a74ae11ff5902":{
      "scriptId":"u40"},
    "48112946a763479c9d9ad2fc21dcf9b9":{
      "scriptId":"u41"},
    "2402be72e5064bda95126e92003e03df":{
      "scriptId":"u42"},
    "8755d6a63af64c25a158854116f6efe6":{
      "scriptId":"u43"},
    "2c63c95d5ea84edcad384bc4ef9db04b":{
      "scriptId":"u44"},
    "50d26e544c734b47a0bc9bc7edf5dcab":{
      "scriptId":"u45"},
    "43ba775b5e0449968b9b592cf5eb6abf":{
      "scriptId":"u46"},
    "441fb75f4d79427b95f9fb8c315ef52e":{
      "scriptId":"u47"},
    "c4ba0bed098d4117abe9c4fc2f887235":{
      "scriptId":"u48"},
    "0c4483d294a24af784b048f0b876cb1c":{
      "scriptId":"u49"},
    "1a7103f2cdce4b678eb32c035500df3b":{
      "scriptId":"u50"},
    "21a37a754f744030a54f99eedf973eb0":{
      "scriptId":"u51"},
    "5517f90ef2e5482182f9ba9e8341b7cd":{
      "scriptId":"u52"},
    "acf3a827f6564f54bd8942acc6163904":{
      "scriptId":"u53"},
    "21b4601539984069a3accbcb35a3730e":{
      "scriptId":"u54"},
    "c1693331824242598ed302c9cf0a454c":{
      "scriptId":"u55"},
    "475ee4c9094346cebf36dde5c0a6f9dd":{
      "scriptId":"u56"},
    "7e21c36f572f4d838df99f443b2bc527":{
      "scriptId":"u57"},
    "4cfaeebf2d4b4641aec6e054e127e1f9":{
      "scriptId":"u58"},
    "b527290e112e461aadf2bb816b2460b0":{
      "scriptId":"u59"},
    "22ff446183cd469fad26de0a18ae79b7":{
      "scriptId":"u60"},
    "765a257a22934e90b47882de4f9f3bdf":{
      "scriptId":"u61"},
    "cdf9d5d0f29a43519ed874ef406c5d10":{
      "scriptId":"u62"},
    "a3f337f0e45341478e61036b3f2559df":{
      "scriptId":"u63"}}});