$axure.loadCurrentPage({
  "url":"未签约.html",
  "generationDate":new Date(1416971006100.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"229fe7f6a5684a9fa57c8bba934ec6ee",
    "type":"Axure:Page",
    "name":"未签约",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"39090e407f514b7dbd88b1597b2f0156",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":30},
            "size":{
              "width":320,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e72745642fc44ab92d4ad66f0c67999",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":209,
                  "y":30},
                "size":{
                  "width":320,
                  "height":495}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u0.png"}},
{
          "id":"bd21b2e128e24650b387abf9194a15c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":209,
              "y":30},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6684ec3aa584ec7b468fbc098f282f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":209,
                  "y":30},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u2.png"}},
{
          "id":"b7dd40596f2d425db7ac4b81a83f211a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":79},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"951c77a6cf3c4ff3bdb52919b1b58860",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":209,
                  "y":79},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天",
                      "target":{
                        "targetType":"page",
                        "url":"聊天.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/搜索/u54.png"}},
{
          "id":"f3c600e76b2646f6b602b4b8d62cb014",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":86},
            "size":{
              "width":46,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f52baf31ae34d47887b309f58567b05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":86},
                "size":{
                  "width":46,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u56.png"}},
{
          "id":"d83e09fd7e0c4188a82d70f4a8170f36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":297,
              "y":91},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12865c9b2409478dadb77829deda6aa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":297,
                  "y":91},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eaac6293c13740cb9bb9eba4fb685b91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3333FF,
              "opacity":1},
            "location":{
              "x":297,
              "y":110},
            "size":{
              "width":61,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"454e99d680234bd2a6212a82fbf21a5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3333FF,
                  "opacity":1},
                "location":{
                  "x":297,
                  "y":110},
                "size":{
                  "width":61,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e6ebc7d0e824771b4e0194f5dc9f5e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":129},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3e2a135366246ae99527a2099cb567f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":209,
                  "y":129},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u54.png"}},
{
          "id":"2defd3d5bfbb40949c3731ffb20096a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":297,
              "y":141},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d30f2f534c8546c39bccdf760db781ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":297,
                  "y":141},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80bb559e49184f94aab9a0bd48c07905",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":297,
              "y":160},
            "size":{
              "width":122,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a635f02e0b44130aba4828fce40fe37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":297,
                  "y":160},
                "size":{
                  "width":122,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"989ff9797eac4e93ac3dfcb237428fd9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":137},
            "size":{
              "width":46,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe68a3da6597418d9fd2d41eac89d42c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":137},
                "size":{
                  "width":46,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u68.png"}},
{
          "id":"31e9e9446b6e42e0ba5caa55933c3cc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":179},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"387e638a52c44ba1932472bfb8a3e3ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":209,
                  "y":179},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u54.png"}},
{
          "id":"373a48299cdc431fa3be347c98c4a143",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":186},
            "size":{
              "width":46,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"507db13a2b2146f3bab1f98ea85b5585",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":186},
                "size":{
                  "width":46,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u56.png"}},
{
          "id":"b47c696ca61c48b3a0bca6cd96d01ab2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":297,
              "y":191},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b6261ceab0f4e8b947bfb43c48c6d0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":297,
                  "y":191},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efe4258862d2436293b55560f0a787d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3333FF,
              "opacity":1},
            "location":{
              "x":297,
              "y":210},
            "size":{
              "width":67,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f44599fed6694f62b6c6ef8c9e4a3fca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3333FF,
                  "opacity":1},
                "location":{
                  "x":297,
                  "y":210},
                "size":{
                  "width":67,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bebc3c3ca2494992853270b52d370b55",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":229},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69a8174a725a4ab99767d68b8dab177f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":209,
                  "y":229},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u54.png"}},
{
          "id":"b31fa982b6e94c9da022f564a223f9e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":297,
              "y":241},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ff07388e5e549238a4b8800cffb650b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":297,
                  "y":241},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a052a6a2d1c24cf4a4d73e280a4d619a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3333FF,
              "opacity":1},
            "location":{
              "x":297,
              "y":260},
            "size":{
              "width":67,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94eb9178dac94cb49d6ecab09bfe3671",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3333FF,
                  "opacity":1},
                "location":{
                  "x":297,
                  "y":260},
                "size":{
                  "width":67,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"767fda134b2f4dd7a74fafc8e3bd3e4e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":237},
            "size":{
              "width":46,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"409dd2bff0594da6b9fd625b3ba61e96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":237},
                "size":{
                  "width":46,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u68.png"}},
{
          "id":"7be3a618a3ec4a2ab3feda94ada3bf59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":477,
              "y":128},
            "size":{
              "width":50,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10bc8095096642df8c60fc9c322d3ee7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":477,
                  "y":128},
                "size":{
                  "width":50,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约客户/u62.png"}},
{
          "id":"cb800aa5a6054a2bb47bed1fbd2e92c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":128},
            "size":{
              "width":268,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d91c3605c31841e1ace4a809f6a8d21d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":209,
                  "y":128},
                "size":{
                  "width":268,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未签约/u38.png"}},
{
          "id":"764718d692f148088bdcb0fb69424985",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":140},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33e641c1f197488794e6901c55c2a183",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":140},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0dbe800ccf04b1982189aad4b269629",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3333FF,
              "opacity":1},
            "location":{
              "x":247,
              "y":159},
            "size":{
              "width":67,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c360c52eb2fa418290c205e76d0338f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3333FF,
                  "opacity":1},
                "location":{
                  "x":247,
                  "y":159},
                "size":{
                  "width":67,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3f8746f7bae4430b6e703be93638e5c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":171,
              "y":136},
            "size":{
              "width":46,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e26df97fbda64a65ae89a1a57468c873",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":171,
                  "y":136},
                "size":{
                  "width":46,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u68.png"}},
{
          "id":"0b73a3308bea4b9cada008035fa11766",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":203,
              "y":86},
            "size":{
              "width":10,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/签约客户/u74_line.png"}},
{
          "id":"9da61dd42e0440e88c88d51accdafced",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":335,
              "y":44},
            "size":{
              "width":84,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 签约客户",
                      "target":{
                        "targetType":"page",
                        "url":"签约客户.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}}},
{
          "id":"926597ad5a784d59bfcc3c831e1ad353",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":29}},
          "adaptiveStyles":{
},
          "masterId":"99966c745e5f45f4976c9a95bb5da09d"},
{
          "id":"28d5e96b44c2401992911a0de336220e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":44},
            "size":{
              "width":20,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f73feae1dd948248c37985a4fb8fb23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":497,
                  "y":44},
                "size":{
                  "width":20,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 搜索",
                      "target":{
                        "targetType":"page",
                        "url":"搜索.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/签约客户/u75.png"}}]}},
  "masters":{
    "99966c745e5f45f4976c9a95bb5da09d":{
      "packageId":"99966c745e5f45f4976c9a95bb5da09d",
      "type":"Axure:Master",
      "name":"客户管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"21a821cb16b54306b9015940b180a62a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":178,
                "y":14},
              "size":{
                "width":29,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fbbf13530b6b49e787465f7a571acfa3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":178,
                    "y":14},
                  "size":{
                    "width":29,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u66.png"}},
{
            "id":"a1fe460a89ae47ee97b68852bf32ac45",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "location":{
                "x":1,
                "y":0},
              "size":{
                "width":170,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3fd417b58ca349ebb4d4981f6122bf5d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "location":{
                    "x":1,
                    "y":0},
                  "size":{
                    "width":170,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u68.png"}},
{
            "id":"1cd1a7f0e67241bb8ba5d7b6b62eb716",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":50},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da48e42ab03e4ab6ac48b84208588f1f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":50},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 日程",
                        "target":{
                          "targetType":"page",
                          "url":"日程.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/日程/u74.png"}},
{
            "id":"54902604f47c44048a587be91b30756f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":66},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e83528ad13b64bee8a10ef3f6e9855d1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":66},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u54.png"}},
{
            "id":"5d12d74c96df4882b31e6343bf1cd305",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":1,
                "y":94},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1248eaabc571433aa2b244f86e20a54b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":1,
                    "y":94},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 签约客户",
                        "target":{
                          "targetType":"page",
                          "url":"签约客户.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/日程/u70.png"}},
{
            "id":"628f6484e12940bd99afc1b51bc88af1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":153,
                "y":112},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"87f2cd1c7a074a59862f829ccf129058",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":153,
                    "y":112},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u76.png"}},
{
            "id":"d807acd0e9984e3598688184ce6e1493",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":110},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13798a5a4cd948f9a2ad5920e11adaf8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":110},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u54.png"}},
{
            "id":"b1af99fc529d45739c179d593305efd1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":139},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3adca718259f4cef84f7784c75e861be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":139},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u74.png"}},
{
            "id":"065baa2c43d44a8fa95af24921c91cfb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":153,
                "y":156},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9ad0f25db1cc4d209e4c95fd3fe655fa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":153,
                    "y":156},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u76.png"}},
{
            "id":"377aac317b9340359789438e770fa200",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":156},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7039944031114272ba855fd709db50c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":156},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u54.png"}},
{
            "id":"4b324441b48e47dd9c143d09e20ab94f",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":90},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u86_line.png"}},
{
            "id":"b6f7194cec7e43ceaa66a9050ef10c72",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":184},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9cf03b547ff4121ac3aa6afe8c798e7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":184},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u74.png"}},
{
            "id":"e5a0a46b28064b71885cd7878f644bd4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":153,
                "y":202},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"16f4a3dba55e4ef4a4a0812359f0e9a2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":153,
                    "y":202},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u76.png"}},
{
            "id":"177bb9e0bb5a4b52b7d1b0fb22d3ddb0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":200},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a54d9d6efa24743a08b7d6759498e65",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":200},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u54.png"}},
{
            "id":"1d965cb0186a4f4891af930d058faba0",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":178},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u86_line.png"}},
{
            "id":"8ee97f95eac44c908349b0f7fe786fa3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":230},
              "size":{
                "width":170,
                "height":266}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f815ced99d8f44a3a9a4953dc461a0c3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":230},
                  "size":{
                    "width":170,
                    "height":266}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u95.png"}},
{
            "id":"345f63b7e52c4a00ac36d1ef82074e39",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":224},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u86_line.png"}},
{
            "id":"d3621adbffe44a69bba07a4030de9746",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":134},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u86_line.png"}}]}}},
  "objectPaths":{
    "39090e407f514b7dbd88b1597b2f0156":{
      "scriptId":"u0"},
    "2e72745642fc44ab92d4ad66f0c67999":{
      "scriptId":"u1"},
    "bd21b2e128e24650b387abf9194a15c8":{
      "scriptId":"u2"},
    "a6684ec3aa584ec7b468fbc098f282f1":{
      "scriptId":"u3"},
    "b7dd40596f2d425db7ac4b81a83f211a":{
      "scriptId":"u4"},
    "951c77a6cf3c4ff3bdb52919b1b58860":{
      "scriptId":"u5"},
    "f3c600e76b2646f6b602b4b8d62cb014":{
      "scriptId":"u6"},
    "1f52baf31ae34d47887b309f58567b05":{
      "scriptId":"u7"},
    "d83e09fd7e0c4188a82d70f4a8170f36":{
      "scriptId":"u8"},
    "12865c9b2409478dadb77829deda6aa5":{
      "scriptId":"u9"},
    "eaac6293c13740cb9bb9eba4fb685b91":{
      "scriptId":"u10"},
    "454e99d680234bd2a6212a82fbf21a5b":{
      "scriptId":"u11"},
    "3e6ebc7d0e824771b4e0194f5dc9f5e3":{
      "scriptId":"u12"},
    "a3e2a135366246ae99527a2099cb567f":{
      "scriptId":"u13"},
    "2defd3d5bfbb40949c3731ffb20096a7":{
      "scriptId":"u14"},
    "d30f2f534c8546c39bccdf760db781ce":{
      "scriptId":"u15"},
    "80bb559e49184f94aab9a0bd48c07905":{
      "scriptId":"u16"},
    "4a635f02e0b44130aba4828fce40fe37":{
      "scriptId":"u17"},
    "989ff9797eac4e93ac3dfcb237428fd9":{
      "scriptId":"u18"},
    "fe68a3da6597418d9fd2d41eac89d42c":{
      "scriptId":"u19"},
    "31e9e9446b6e42e0ba5caa55933c3cc2":{
      "scriptId":"u20"},
    "387e638a52c44ba1932472bfb8a3e3ad":{
      "scriptId":"u21"},
    "373a48299cdc431fa3be347c98c4a143":{
      "scriptId":"u22"},
    "507db13a2b2146f3bab1f98ea85b5585":{
      "scriptId":"u23"},
    "b47c696ca61c48b3a0bca6cd96d01ab2":{
      "scriptId":"u24"},
    "1b6261ceab0f4e8b947bfb43c48c6d0c":{
      "scriptId":"u25"},
    "efe4258862d2436293b55560f0a787d1":{
      "scriptId":"u26"},
    "f44599fed6694f62b6c6ef8c9e4a3fca":{
      "scriptId":"u27"},
    "bebc3c3ca2494992853270b52d370b55":{
      "scriptId":"u28"},
    "69a8174a725a4ab99767d68b8dab177f":{
      "scriptId":"u29"},
    "b31fa982b6e94c9da022f564a223f9e3":{
      "scriptId":"u30"},
    "4ff07388e5e549238a4b8800cffb650b":{
      "scriptId":"u31"},
    "a052a6a2d1c24cf4a4d73e280a4d619a":{
      "scriptId":"u32"},
    "94eb9178dac94cb49d6ecab09bfe3671":{
      "scriptId":"u33"},
    "767fda134b2f4dd7a74fafc8e3bd3e4e":{
      "scriptId":"u34"},
    "409dd2bff0594da6b9fd625b3ba61e96":{
      "scriptId":"u35"},
    "7be3a618a3ec4a2ab3feda94ada3bf59":{
      "scriptId":"u36"},
    "10bc8095096642df8c60fc9c322d3ee7":{
      "scriptId":"u37"},
    "cb800aa5a6054a2bb47bed1fbd2e92c6":{
      "scriptId":"u38"},
    "d91c3605c31841e1ace4a809f6a8d21d":{
      "scriptId":"u39"},
    "764718d692f148088bdcb0fb69424985":{
      "scriptId":"u40"},
    "33e641c1f197488794e6901c55c2a183":{
      "scriptId":"u41"},
    "e0dbe800ccf04b1982189aad4b269629":{
      "scriptId":"u42"},
    "c360c52eb2fa418290c205e76d0338f2":{
      "scriptId":"u43"},
    "d3f8746f7bae4430b6e703be93638e5c":{
      "scriptId":"u44"},
    "e26df97fbda64a65ae89a1a57468c873":{
      "scriptId":"u45"},
    "0b73a3308bea4b9cada008035fa11766":{
      "scriptId":"u46"},
    "9da61dd42e0440e88c88d51accdafced":{
      "scriptId":"u47"},
    "926597ad5a784d59bfcc3c831e1ad353":{
      "scriptId":"u48",
      "21a821cb16b54306b9015940b180a62a":{
        "scriptId":"u49"},
      "fbbf13530b6b49e787465f7a571acfa3":{
        "scriptId":"u50"},
      "a1fe460a89ae47ee97b68852bf32ac45":{
        "scriptId":"u51"},
      "3fd417b58ca349ebb4d4981f6122bf5d":{
        "scriptId":"u52"},
      "1cd1a7f0e67241bb8ba5d7b6b62eb716":{
        "scriptId":"u53"},
      "da48e42ab03e4ab6ac48b84208588f1f":{
        "scriptId":"u54"},
      "54902604f47c44048a587be91b30756f":{
        "scriptId":"u55"},
      "e83528ad13b64bee8a10ef3f6e9855d1":{
        "scriptId":"u56"},
      "5d12d74c96df4882b31e6343bf1cd305":{
        "scriptId":"u57"},
      "1248eaabc571433aa2b244f86e20a54b":{
        "scriptId":"u58"},
      "628f6484e12940bd99afc1b51bc88af1":{
        "scriptId":"u59"},
      "87f2cd1c7a074a59862f829ccf129058":{
        "scriptId":"u60"},
      "d807acd0e9984e3598688184ce6e1493":{
        "scriptId":"u61"},
      "13798a5a4cd948f9a2ad5920e11adaf8":{
        "scriptId":"u62"},
      "b1af99fc529d45739c179d593305efd1":{
        "scriptId":"u63"},
      "3adca718259f4cef84f7784c75e861be":{
        "scriptId":"u64"},
      "065baa2c43d44a8fa95af24921c91cfb":{
        "scriptId":"u65"},
      "9ad0f25db1cc4d209e4c95fd3fe655fa":{
        "scriptId":"u66"},
      "377aac317b9340359789438e770fa200":{
        "scriptId":"u67"},
      "7039944031114272ba855fd709db50c7":{
        "scriptId":"u68"},
      "4b324441b48e47dd9c143d09e20ab94f":{
        "scriptId":"u69"},
      "b6f7194cec7e43ceaa66a9050ef10c72":{
        "scriptId":"u70"},
      "b9cf03b547ff4121ac3aa6afe8c798e7":{
        "scriptId":"u71"},
      "e5a0a46b28064b71885cd7878f644bd4":{
        "scriptId":"u72"},
      "16f4a3dba55e4ef4a4a0812359f0e9a2":{
        "scriptId":"u73"},
      "177bb9e0bb5a4b52b7d1b0fb22d3ddb0":{
        "scriptId":"u74"},
      "0a54d9d6efa24743a08b7d6759498e65":{
        "scriptId":"u75"},
      "1d965cb0186a4f4891af930d058faba0":{
        "scriptId":"u76"},
      "8ee97f95eac44c908349b0f7fe786fa3":{
        "scriptId":"u77"},
      "f815ced99d8f44a3a9a4953dc461a0c3":{
        "scriptId":"u78"},
      "345f63b7e52c4a00ac36d1ef82074e39":{
        "scriptId":"u79"},
      "d3621adbffe44a69bba07a4030de9746":{
        "scriptId":"u80"}},
    "28d5e96b44c2401992911a0de336220e":{
      "scriptId":"u81"},
    "3f73feae1dd948248c37985a4fb8fb23":{
      "scriptId":"u82"}}});