$axure.loadCurrentPage({
  "url":"日程编辑页.html",
  "generationDate":new Date(1417146909804.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"800fb0e2fae44bf0a61e846048a7a135",
    "type":"Axure:Page",
    "name":"日程编辑页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ec5548f227784bfc8eed36b7a8a3c369",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":20},
            "size":{
              "width":320,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1f85c848299414ab9367fc2cecc6244",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":20},
                "size":{
                  "width":320,
                  "height":495}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u0.png"}},
{
          "id":"e3125ce755044bf3be0dbf75a1530ddf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":360,
              "y":20},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20a311fa03c2471b90ddd11ec9233561",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":360,
                  "y":20},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u2.png"}},
{
          "id":"83c947a6a9a342ddbd6640d229f723bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":633,
              "y":36},
            "size":{
              "width":27,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a3ba869f105498f9bc613af7098d5cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":633,
                  "y":36},
                "size":{
                  "width":27,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 日程",
                      "target":{
                        "targetType":"page",
                        "url":"日程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f222537c205c448c8c599ff0a6343766",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":377,
              "y":38},
            "size":{
              "width":35,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d12e7053d5464d8f8c7c9cb15ff5f450",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":377,
                  "y":38},
                "size":{
                  "width":35,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 日程",
                      "target":{
                        "targetType":"page",
                        "url":"日程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ee59a83587842f58758fca3a561db85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":360,
              "y":70},
            "size":{
              "width":320,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feec53294b8b4cf8aab5e8284203267a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":360,
                  "y":70},
                "size":{
                  "width":320,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64ec0d3f50194acd9fe5a974bc560b3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":370,
              "y":212},
            "size":{
              "width":300,
              "height":202},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0043cff1582f4fdfade249286e827a81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":370,
                  "y":212},
                "size":{
                  "width":300,
                  "height":202},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u10.png"}},
{
          "id":"3e12a0d482704b489a75ff500551e5a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":360,
              "y":106},
            "size":{
              "width":157,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d99087553834b8da455a96df3a60819",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":360,
                  "y":106},
                "size":{
                  "width":157,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u12.png"}},
{
          "id":"ae5c92682aa047a1a92ff6a72bab945c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":456,
              "y":113},
            "size":{
              "width":17,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d30737bcde8841a4894142d088d533a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":456,
                  "y":113},
                "size":{
                  "width":17,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u14.png"}},
{
          "id":"1a6a78bde8b241039feb0e843a818826",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":439,
              "y":113},
            "size":{
              "width":17,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfbbbaf854bc4deea431f0b86b3e6a57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":439,
                  "y":113},
                "size":{
                  "width":17,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u14.png"}},
{
          "id":"cf7a2a8a5c0247a3bcc80488161f4216",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":474,
              "y":113},
            "size":{
              "width":17,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06d70d83efc5407ab23e4a275527b1fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":474,
                  "y":113},
                "size":{
                  "width":17,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u18.png"}},
{
          "id":"f1a7290aa57546b1936c40970668a8aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":360,
              "y":137},
            "size":{
              "width":320,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d75b3bb5ad2e4611afab2f58a1a759e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":360,
                  "y":137},
                "size":{
                  "width":320,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u20.png"}},
{
          "id":"37fabcc0fbf94a05bc2b3a9dc56c01ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":652,
              "y":147},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1e965abbbdd4ec8a2033e03bdc8bd76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":652,
                  "y":147},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u22.png"}},
{
          "id":"63cfb3cc3dfb44ebbbc78853be21c233",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":20},
            "size":{
              "width":320,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b5e08b35ce8473ea54f63fbb4ba16f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":20},
                "size":{
                  "width":320,
                  "height":495}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u0.png"}},
{
          "id":"f41dbc99a2274c9b8e00aaee99991c10",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":30,
              "y":20},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"934b44cd24d641bf97b6b3693b965cfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":30,
                  "y":20},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u2.png"}},
{
          "id":"dcee0b3406034d3a919f6d87adb14b10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":36},
            "size":{
              "width":27,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ea64fe6d5de437c9d69b90439295e4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":36},
                "size":{
                  "width":27,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 日程",
                      "target":{
                        "targetType":"page",
                        "url":"日程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21473d652e1a446191d55ad7d170ea2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":38},
            "size":{
              "width":35,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbc3b8aba9f84be4a01c5ac85b7b2881",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":38},
                "size":{
                  "width":35,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 日程",
                      "target":{
                        "targetType":"page",
                        "url":"日程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6cae35b3bf442a0a843ead24a10b7f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":30,
              "y":70},
            "size":{
              "width":320,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9160f5eacf94a758193b6c92eba81d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":30,
                  "y":70},
                "size":{
                  "width":320,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49930140f29b4fa6ad0dd94dfd6b767f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":106},
            "size":{
              "width":157,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca87819bf23842488ab5a5d578d5189a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":106},
                "size":{
                  "width":157,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u12.png"}},
{
          "id":"d4c05130676f4f85a4ab8cc373d12f6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":126,
              "y":113},
            "size":{
              "width":17,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b88339d060944fb958418eeb16a2d47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":126,
                  "y":113},
                "size":{
                  "width":17,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u18.png"}},
{
          "id":"9c80f956627e42dbb635ac6da18815c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":109,
              "y":113},
            "size":{
              "width":17,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66dfe1725a5f4caaad7a955a4d47dbfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":109,
                  "y":113},
                "size":{
                  "width":17,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u14.png"}},
{
          "id":"98868eaa52424cbc9749a95fa7b428c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":113},
            "size":{
              "width":17,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6da8d256569d437ea255c70765bba847",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":113},
                "size":{
                  "width":17,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u18.png"}},
{
          "id":"f79b9c0012bd4be6aa06a9e75dea4b6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":137},
            "size":{
              "width":320,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf7aceb079c64debb23bc6d1061d6423",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":137},
                "size":{
                  "width":320,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u20.png"}},
{
          "id":"cfe919b5c8c04e7f8cf7cfdb49c446bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":322,
              "y":147},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f042ba98d2e34b789d9b3d8f3ad99948",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":322,
                  "y":147},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u22.png"}},
{
          "id":"2146582103ed48748508da1bb9961f36",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":209},
            "size":{
              "width":307,
              "height":214}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28a846fec6ba42639874e8957fcbde46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":209},
                "size":{
                  "width":307,
                  "height":214}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u46.png"}},
{
          "id":"392616259ea040b4b47e1a44bc5077e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":167},
            "size":{
              "width":320,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"850540686a524f2db0751e1a316d83f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":167},
                "size":{
                  "width":320,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u20.png"}},
{
          "id":"5204eaa5a9ee43c295d7b44f96e2e4d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":322,
              "y":177.5},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c609d67b92ae4576906ad5d85d5f86ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":322,
                  "y":177.5},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u22.png"}},
{
          "id":"5e1bbcb775ed4131bd6790a6d28d56e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":360,
              "y":167},
            "size":{
              "width":320,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abe201b837a743048f09a12f07e7fd72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":360,
                  "y":167},
                "size":{
                  "width":320,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u20.png"}},
{
          "id":"9d9bc2fcb6b449949ff674d07c98537e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":652,
              "y":178},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43072d92014e42f69125c9e9007a02ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":652,
                  "y":178},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程编辑页/u22.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ec5548f227784bfc8eed36b7a8a3c369":{
      "scriptId":"u0"},
    "a1f85c848299414ab9367fc2cecc6244":{
      "scriptId":"u1"},
    "e3125ce755044bf3be0dbf75a1530ddf":{
      "scriptId":"u2"},
    "20a311fa03c2471b90ddd11ec9233561":{
      "scriptId":"u3"},
    "83c947a6a9a342ddbd6640d229f723bf":{
      "scriptId":"u4"},
    "1a3ba869f105498f9bc613af7098d5cc":{
      "scriptId":"u5"},
    "f222537c205c448c8c599ff0a6343766":{
      "scriptId":"u6"},
    "d12e7053d5464d8f8c7c9cb15ff5f450":{
      "scriptId":"u7"},
    "3ee59a83587842f58758fca3a561db85":{
      "scriptId":"u8"},
    "feec53294b8b4cf8aab5e8284203267a":{
      "scriptId":"u9"},
    "64ec0d3f50194acd9fe5a974bc560b3d":{
      "scriptId":"u10"},
    "0043cff1582f4fdfade249286e827a81":{
      "scriptId":"u11"},
    "3e12a0d482704b489a75ff500551e5a1":{
      "scriptId":"u12"},
    "1d99087553834b8da455a96df3a60819":{
      "scriptId":"u13"},
    "ae5c92682aa047a1a92ff6a72bab945c":{
      "scriptId":"u14"},
    "d30737bcde8841a4894142d088d533a6":{
      "scriptId":"u15"},
    "1a6a78bde8b241039feb0e843a818826":{
      "scriptId":"u16"},
    "cfbbbaf854bc4deea431f0b86b3e6a57":{
      "scriptId":"u17"},
    "cf7a2a8a5c0247a3bcc80488161f4216":{
      "scriptId":"u18"},
    "06d70d83efc5407ab23e4a275527b1fb":{
      "scriptId":"u19"},
    "f1a7290aa57546b1936c40970668a8aa":{
      "scriptId":"u20"},
    "d75b3bb5ad2e4611afab2f58a1a759e8":{
      "scriptId":"u21"},
    "37fabcc0fbf94a05bc2b3a9dc56c01ec":{
      "scriptId":"u22"},
    "f1e965abbbdd4ec8a2033e03bdc8bd76":{
      "scriptId":"u23"},
    "63cfb3cc3dfb44ebbbc78853be21c233":{
      "scriptId":"u24"},
    "1b5e08b35ce8473ea54f63fbb4ba16f6":{
      "scriptId":"u25"},
    "f41dbc99a2274c9b8e00aaee99991c10":{
      "scriptId":"u26"},
    "934b44cd24d641bf97b6b3693b965cfe":{
      "scriptId":"u27"},
    "dcee0b3406034d3a919f6d87adb14b10":{
      "scriptId":"u28"},
    "8ea64fe6d5de437c9d69b90439295e4e":{
      "scriptId":"u29"},
    "21473d652e1a446191d55ad7d170ea2b":{
      "scriptId":"u30"},
    "bbc3b8aba9f84be4a01c5ac85b7b2881":{
      "scriptId":"u31"},
    "b6cae35b3bf442a0a843ead24a10b7f7":{
      "scriptId":"u32"},
    "c9160f5eacf94a758193b6c92eba81d3":{
      "scriptId":"u33"},
    "49930140f29b4fa6ad0dd94dfd6b767f":{
      "scriptId":"u34"},
    "ca87819bf23842488ab5a5d578d5189a":{
      "scriptId":"u35"},
    "d4c05130676f4f85a4ab8cc373d12f6c":{
      "scriptId":"u36"},
    "4b88339d060944fb958418eeb16a2d47":{
      "scriptId":"u37"},
    "9c80f956627e42dbb635ac6da18815c2":{
      "scriptId":"u38"},
    "66dfe1725a5f4caaad7a955a4d47dbfd":{
      "scriptId":"u39"},
    "98868eaa52424cbc9749a95fa7b428c0":{
      "scriptId":"u40"},
    "6da8d256569d437ea255c70765bba847":{
      "scriptId":"u41"},
    "f79b9c0012bd4be6aa06a9e75dea4b6d":{
      "scriptId":"u42"},
    "cf7aceb079c64debb23bc6d1061d6423":{
      "scriptId":"u43"},
    "cfe919b5c8c04e7f8cf7cfdb49c446bb":{
      "scriptId":"u44"},
    "f042ba98d2e34b789d9b3d8f3ad99948":{
      "scriptId":"u45"},
    "2146582103ed48748508da1bb9961f36":{
      "scriptId":"u46"},
    "28a846fec6ba42639874e8957fcbde46":{
      "scriptId":"u47"},
    "392616259ea040b4b47e1a44bc5077e8":{
      "scriptId":"u48"},
    "850540686a524f2db0751e1a316d83f1":{
      "scriptId":"u49"},
    "5204eaa5a9ee43c295d7b44f96e2e4d7":{
      "scriptId":"u50"},
    "c609d67b92ae4576906ad5d85d5f86ef":{
      "scriptId":"u51"},
    "5e1bbcb775ed4131bd6790a6d28d56e6":{
      "scriptId":"u52"},
    "abe201b837a743048f09a12f07e7fd72":{
      "scriptId":"u53"},
    "9d9bc2fcb6b449949ff674d07c98537e":{
      "scriptId":"u54"},
    "43072d92014e42f69125c9e9007a02ee":{
      "scriptId":"u55"}}});