$axure.loadCurrentPage({
  "url":"意向客户.html",
  "generationDate":new Date(1417677946018.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"229fe7f6a5684a9fa57c8bba934ec6ee",
    "type":"Axure:Page",
    "name":"意向客户",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"39090e407f514b7dbd88b1597b2f0156",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":30},
            "size":{
              "width":320,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e72745642fc44ab92d4ad66f0c67999",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":209,
                  "y":30},
                "size":{
                  "width":320,
                  "height":495}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u0.png"}},
{
          "id":"bd21b2e128e24650b387abf9194a15c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":209,
              "y":30},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6684ec3aa584ec7b468fbc098f282f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":209,
                  "y":30},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u2.png"}},
{
          "id":"0b73a3308bea4b9cada008035fa11766",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":203,
              "y":86},
            "size":{
              "width":10,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/全部客户/u30_line.png"}},
{
          "id":"926597ad5a784d59bfcc3c831e1ad353",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":29}},
          "adaptiveStyles":{
},
          "masterId":"99966c745e5f45f4976c9a95bb5da09d"},
{
          "id":"81f0d1ce753944c893d1937d90d26ed1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":341,
              "y":45},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f37daccbdc85421988788a4f53f19d26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":341,
                  "y":45},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f098ebdb6fe43fda0d1ff3462e50589",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":398,
              "y":49},
            "size":{
              "width":18,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18399c4f510a47d49c4220111156e319",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":398,
                  "y":49},
                "size":{
                  "width":18,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u116.png"}},
{
          "id":"8c9e7a1a304744b4b87a07ecc255c7bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":39},
            "size":{
              "width":102,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"998bc836e7b14144973bb170a20cb953",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":39},
                "size":{
                  "width":102,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 签约客户",
                      "objectsToFades":[{
                          "objectPath":["9cb26a63a6034d968597fd1f30bb1894"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/意向客户/u42.png"}},
{
          "id":"438bd48afdf1487991755ac21fc4156a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":116},
            "size":{
              "width":318,
              "height":72},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"839e49d5150b49be95ff20f05b5198cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":116},
                "size":{
                  "width":318,
                  "height":72},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部客户/u4.png"}},
{
          "id":"d0beeb9878744901afc215329f35bf8d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":123},
            "size":{
              "width":46,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7f379bf07cb44d0914bd767cf9b36a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":123},
                "size":{
                  "width":46,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部客户/u6.png"}},
{
          "id":"0cefd78d5fc04101a155f2a5dd24b5c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":297,
              "y":128},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"001953b19e064a648c0f30ec647c53fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":297,
                  "y":128},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0684bc915b2468aa538463c4b114784",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3333FF,
              "opacity":1},
            "location":{
              "x":297,
              "y":147},
            "size":{
              "width":73,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"097bb103d0a24a0f8a645c2082e78d77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3333FF,
                  "opacity":1},
                "location":{
                  "x":297,
                  "y":147},
                "size":{
                  "width":73,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7834de9dfac0476c8f4ff2d5ebc99e2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":187},
            "size":{
              "width":318,
              "height":72},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b45db627e2049e084ef90edf5fcd4ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":187},
                "size":{
                  "width":318,
                  "height":72},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部客户/u4.png"}},
{
          "id":"0834ec2f5f2e440da9327adfba23bd81",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":297,
              "y":197},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d071862a05ae4710b5f6937f7060ad1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":297,
                  "y":197},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"284f231f80d7419b896e460216185770",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3333FF,
              "opacity":1},
            "location":{
              "x":297,
              "y":216},
            "size":{
              "width":73,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc844e154bef4f759c5515f47397e981",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3333FF,
                  "opacity":1},
                "location":{
                  "x":297,
                  "y":216},
                "size":{
                  "width":73,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53e956b3f3ac4338a6b24fef28f24e75",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":199},
            "size":{
              "width":46,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40edcc27e20443d7a09d0b05889c3baf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":199},
                "size":{
                  "width":46,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部客户/u28.png"}},
{
          "id":"0bb326f897194c69be531bb93205e3e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":297,
              "y":166},
            "size":{
              "width":83,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0292656d74243b68911746f4da3d766",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":297,
                  "y":166},
                "size":{
                  "width":83,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ba8e631712b4cb0bd1be9e3e9f74d2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":297,
              "y":235},
            "size":{
              "width":23,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50b8aec22ef04879bbbea34b902aef24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":297,
                  "y":235},
                "size":{
                  "width":23,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed1016ffa010489cabe73946d50fd923",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":208,
              "y":78},
            "size":{
              "width":320,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"901ebccc06964488abebf2aab67287a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":208,
                  "y":78},
                "size":{
                  "width":320,
                  "height":39},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部客户/u114.png"}},
{
          "id":"cc094439f7da485da8e4720b87af7faa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":241,
              "y":84},
            "size":{
              "width":260,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"effb459c4baf4369a1bf53aa77938327",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":241,
                  "y":84},
                "size":{
                  "width":260,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部客户/u116.png"}},
{
          "id":"ad4243467dce4811ab67bcc7af2b1da5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":339,
              "y":94},
            "size":{
              "width":12,
              "height":13},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cea556d4736349b99b68258afb4fb002",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":339,
                  "y":94},
                "size":{
                  "width":12,
                  "height":13},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部客户/u118.png"}},
{
          "id":"9cb26a63a6034d968597fd1f30bb1894",
          "label":"签约客户",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":209,
              "y":80},
            "size":{
              "width":320,
              "height":282},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"55b6ad7f880a4a068f524fb29c190cba",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8705c692394140f589d53fa683f9091d",
                  "label":"",
                  "parentDynamicPanel":"9cb26a63a6034d968597fd1f30bb1894",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":320,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b8a5851b92db4b8e92c1fdde878954cf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9cb26a63a6034d968597fd1f30bb1894",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "location":{
                          "x":0,
                          "y":40},
                        "size":{
                          "width":320,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 全部客户",
                              "target":{
                                "targetType":"page",
                                "url":"全部客户.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/日程/u108.png"}},
{
                  "id":"13c71a19741f4dcdbc64721887186862",
                  "label":"",
                  "parentDynamicPanel":"9cb26a63a6034d968597fd1f30bb1894",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":320,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4d2deeb4626e4a069ffffd4aa7e0c3e5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9cb26a63a6034d968597fd1f30bb1894",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "location":{
                          "x":0,
                          "y":80},
                        "size":{
                          "width":320,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 意向客户",
                              "target":{
                                "targetType":"page",
                                "url":"意向客户.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/日程/u108.png"}},
{
                  "id":"4435ad27239f4d07961114b192db67ab",
                  "label":"",
                  "parentDynamicPanel":"9cb26a63a6034d968597fd1f30bb1894",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":0,
                      "y":119},
                    "size":{
                      "width":320,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"934129b6c5d8497e8909b4b5eeef7bb4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9cb26a63a6034d968597fd1f30bb1894",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "location":{
                          "x":0,
                          "y":119},
                        "size":{
                          "width":320,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 意向客户",
                              "target":{
                                "targetType":"page",
                                "url":"意向客户.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/日程/u108.png"}},
{
                  "id":"b027ad41aeb8467f908a2d4017bef744",
                  "label":"",
                  "parentDynamicPanel":"9cb26a63a6034d968597fd1f30bb1894",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":0,
                      "y":159},
                    "size":{
                      "width":320,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2cdf621fbd7c45d9bd7cd831a615e892",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9cb26a63a6034d968597fd1f30bb1894",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "location":{
                          "x":0,
                          "y":159},
                        "size":{
                          "width":320,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 意向客户",
                              "target":{
                                "targetType":"page",
                                "url":"意向客户.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/日程/u108.png"}},
{
                  "id":"3846a9fd80484a67b60e7602a1d016e8",
                  "label":"",
                  "parentDynamicPanel":"9cb26a63a6034d968597fd1f30bb1894",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":0,
                      "y":199},
                    "size":{
                      "width":320,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9258de71b8f443f0b74ac27f249d894d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9cb26a63a6034d968597fd1f30bb1894",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "location":{
                          "x":0,
                          "y":199},
                        "size":{
                          "width":320,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 意向客户",
                              "target":{
                                "targetType":"page",
                                "url":"意向客户.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/日程/u108.png"}},
{
                  "id":"14f06672504e4e4ab1c4165f7554acf5",
                  "label":"",
                  "parentDynamicPanel":"9cb26a63a6034d968597fd1f30bb1894",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "size":{
                      "width":320,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"99823eb37a494d86a2e7ea4c918f8209",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9cb26a63a6034d968597fd1f30bb1894",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "size":{
                          "width":320,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 全部客户",
                              "target":{
                                "targetType":"page",
                                "url":"全部客户.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/日程/u108.png"}},
{
                  "id":"66b1da07c43f4c1d92157bf3d5edc32b",
                  "label":"",
                  "parentDynamicPanel":"9cb26a63a6034d968597fd1f30bb1894",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":287,
                      "y":88},
                    "size":{
                      "width":23,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"52b7e532e743483ebfbc8aa314e69e86",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9cb26a63a6034d968597fd1f30bb1894",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":287,
                          "y":88},
                        "size":{
                          "width":23,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/日程/u112.png"}}]}]},
{
          "id":"6d926e153f614cdabd8792d3fd31b809",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":42},
            "size":{
              "width":22,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fa3f51b59c249978e911fad34a106bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":42},
                "size":{
                  "width":22,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 添加意向客户",
                      "target":{
                        "targetType":"page",
                        "url":"添加意向客户.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/日程/u120.png"}}]}},
  "masters":{
    "99966c745e5f45f4976c9a95bb5da09d":{
      "packageId":"99966c745e5f45f4976c9a95bb5da09d",
      "type":"Axure:Master",
      "name":"客户管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"21a821cb16b54306b9015940b180a62a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":178,
                "y":27},
              "size":{
                "width":29,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fbbf13530b6b49e787465f7a571acfa3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":178,
                    "y":27},
                  "size":{
                    "width":29,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u63.png"}},
{
            "id":"a1fe460a89ae47ee97b68852bf32ac45",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"33px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "location":{
                "x":1,
                "y":14},
              "size":{
                "width":170,
                "height":91}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3fd417b58ca349ebb4d4981f6122bf5d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"33px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "location":{
                    "x":1,
                    "y":14},
                  "size":{
                    "width":170,
                    "height":91}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u65.png"}},
{
            "id":"1cd1a7f0e67241bb8ba5d7b6b62eb716",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":105},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da48e42ab03e4ab6ac48b84208588f1f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":105},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 日程",
                        "target":{
                          "targetType":"page",
                          "url":"日程.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/日程/u69.png"}},
{
            "id":"54902604f47c44048a587be91b30756f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":121},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e83528ad13b64bee8a10ef3f6e9855d1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":121},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u52.png"}},
{
            "id":"5d12d74c96df4882b31e6343bf1cd305",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":1,
                "y":149},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1248eaabc571433aa2b244f86e20a54b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":1,
                    "y":149},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 全部客户",
                        "target":{
                          "targetType":"page",
                          "url":"全部客户.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/日程/u93.png"}},
{
            "id":"628f6484e12940bd99afc1b51bc88af1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":153,
                "y":167},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"87f2cd1c7a074a59862f829ccf129058",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":153,
                    "y":167},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u71.png"}},
{
            "id":"d807acd0e9984e3598688184ce6e1493",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":165},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13798a5a4cd948f9a2ad5920e11adaf8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":165},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u52.png"}},
{
            "id":"b1af99fc529d45739c179d593305efd1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":194},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3adca718259f4cef84f7784c75e861be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":194},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u69.png"}},
{
            "id":"065baa2c43d44a8fa95af24921c91cfb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":153,
                "y":211},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9ad0f25db1cc4d209e4c95fd3fe655fa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":153,
                    "y":211},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u71.png"}},
{
            "id":"377aac317b9340359789438e770fa200",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":211},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7039944031114272ba855fd709db50c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":211},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u52.png"}},
{
            "id":"4b324441b48e47dd9c143d09e20ab94f",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":145},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u81_line.png"}},
{
            "id":"b6f7194cec7e43ceaa66a9050ef10c72",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":239},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9cf03b547ff4121ac3aa6afe8c798e7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":239},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u69.png"}},
{
            "id":"e5a0a46b28064b71885cd7878f644bd4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":153,
                "y":257},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"16f4a3dba55e4ef4a4a0812359f0e9a2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":153,
                    "y":257},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u71.png"}},
{
            "id":"177bb9e0bb5a4b52b7d1b0fb22d3ddb0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":255},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a54d9d6efa24743a08b7d6759498e65",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":255},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u52.png"}},
{
            "id":"1d965cb0186a4f4891af930d058faba0",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":233},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u81_line.png"}},
{
            "id":"8ee97f95eac44c908349b0f7fe786fa3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":285},
              "size":{
                "width":170,
                "height":266}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f815ced99d8f44a3a9a4953dc461a0c3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":285},
                  "size":{
                    "width":170,
                    "height":266}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u90.png"}},
{
            "id":"345f63b7e52c4a00ac36d1ef82074e39",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":279},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u81_line.png"}},
{
            "id":"d3621adbffe44a69bba07a4030de9746",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":189},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u81_line.png"}}]}}},
  "objectPaths":{
    "39090e407f514b7dbd88b1597b2f0156":{
      "scriptId":"u0"},
    "2e72745642fc44ab92d4ad66f0c67999":{
      "scriptId":"u1"},
    "bd21b2e128e24650b387abf9194a15c8":{
      "scriptId":"u2"},
    "a6684ec3aa584ec7b468fbc098f282f1":{
      "scriptId":"u3"},
    "0b73a3308bea4b9cada008035fa11766":{
      "scriptId":"u4"},
    "926597ad5a784d59bfcc3c831e1ad353":{
      "scriptId":"u5",
      "21a821cb16b54306b9015940b180a62a":{
        "scriptId":"u6"},
      "fbbf13530b6b49e787465f7a571acfa3":{
        "scriptId":"u7"},
      "a1fe460a89ae47ee97b68852bf32ac45":{
        "scriptId":"u8"},
      "3fd417b58ca349ebb4d4981f6122bf5d":{
        "scriptId":"u9"},
      "1cd1a7f0e67241bb8ba5d7b6b62eb716":{
        "scriptId":"u10"},
      "da48e42ab03e4ab6ac48b84208588f1f":{
        "scriptId":"u11"},
      "54902604f47c44048a587be91b30756f":{
        "scriptId":"u12"},
      "e83528ad13b64bee8a10ef3f6e9855d1":{
        "scriptId":"u13"},
      "5d12d74c96df4882b31e6343bf1cd305":{
        "scriptId":"u14"},
      "1248eaabc571433aa2b244f86e20a54b":{
        "scriptId":"u15"},
      "628f6484e12940bd99afc1b51bc88af1":{
        "scriptId":"u16"},
      "87f2cd1c7a074a59862f829ccf129058":{
        "scriptId":"u17"},
      "d807acd0e9984e3598688184ce6e1493":{
        "scriptId":"u18"},
      "13798a5a4cd948f9a2ad5920e11adaf8":{
        "scriptId":"u19"},
      "b1af99fc529d45739c179d593305efd1":{
        "scriptId":"u20"},
      "3adca718259f4cef84f7784c75e861be":{
        "scriptId":"u21"},
      "065baa2c43d44a8fa95af24921c91cfb":{
        "scriptId":"u22"},
      "9ad0f25db1cc4d209e4c95fd3fe655fa":{
        "scriptId":"u23"},
      "377aac317b9340359789438e770fa200":{
        "scriptId":"u24"},
      "7039944031114272ba855fd709db50c7":{
        "scriptId":"u25"},
      "4b324441b48e47dd9c143d09e20ab94f":{
        "scriptId":"u26"},
      "b6f7194cec7e43ceaa66a9050ef10c72":{
        "scriptId":"u27"},
      "b9cf03b547ff4121ac3aa6afe8c798e7":{
        "scriptId":"u28"},
      "e5a0a46b28064b71885cd7878f644bd4":{
        "scriptId":"u29"},
      "16f4a3dba55e4ef4a4a0812359f0e9a2":{
        "scriptId":"u30"},
      "177bb9e0bb5a4b52b7d1b0fb22d3ddb0":{
        "scriptId":"u31"},
      "0a54d9d6efa24743a08b7d6759498e65":{
        "scriptId":"u32"},
      "1d965cb0186a4f4891af930d058faba0":{
        "scriptId":"u33"},
      "8ee97f95eac44c908349b0f7fe786fa3":{
        "scriptId":"u34"},
      "f815ced99d8f44a3a9a4953dc461a0c3":{
        "scriptId":"u35"},
      "345f63b7e52c4a00ac36d1ef82074e39":{
        "scriptId":"u36"},
      "d3621adbffe44a69bba07a4030de9746":{
        "scriptId":"u37"}},
    "81f0d1ce753944c893d1937d90d26ed1":{
      "scriptId":"u38"},
    "f37daccbdc85421988788a4f53f19d26":{
      "scriptId":"u39"},
    "9f098ebdb6fe43fda0d1ff3462e50589":{
      "scriptId":"u40"},
    "18399c4f510a47d49c4220111156e319":{
      "scriptId":"u41"},
    "8c9e7a1a304744b4b87a07ecc255c7bb":{
      "scriptId":"u42"},
    "998bc836e7b14144973bb170a20cb953":{
      "scriptId":"u43"},
    "438bd48afdf1487991755ac21fc4156a":{
      "scriptId":"u44"},
    "839e49d5150b49be95ff20f05b5198cd":{
      "scriptId":"u45"},
    "d0beeb9878744901afc215329f35bf8d":{
      "scriptId":"u46"},
    "d7f379bf07cb44d0914bd767cf9b36a4":{
      "scriptId":"u47"},
    "0cefd78d5fc04101a155f2a5dd24b5c8":{
      "scriptId":"u48"},
    "001953b19e064a648c0f30ec647c53fe":{
      "scriptId":"u49"},
    "f0684bc915b2468aa538463c4b114784":{
      "scriptId":"u50"},
    "097bb103d0a24a0f8a645c2082e78d77":{
      "scriptId":"u51"},
    "7834de9dfac0476c8f4ff2d5ebc99e2a":{
      "scriptId":"u52"},
    "1b45db627e2049e084ef90edf5fcd4ee":{
      "scriptId":"u53"},
    "0834ec2f5f2e440da9327adfba23bd81":{
      "scriptId":"u54"},
    "d071862a05ae4710b5f6937f7060ad1d":{
      "scriptId":"u55"},
    "284f231f80d7419b896e460216185770":{
      "scriptId":"u56"},
    "dc844e154bef4f759c5515f47397e981":{
      "scriptId":"u57"},
    "53e956b3f3ac4338a6b24fef28f24e75":{
      "scriptId":"u58"},
    "40edcc27e20443d7a09d0b05889c3baf":{
      "scriptId":"u59"},
    "0bb326f897194c69be531bb93205e3e1":{
      "scriptId":"u60"},
    "e0292656d74243b68911746f4da3d766":{
      "scriptId":"u61"},
    "8ba8e631712b4cb0bd1be9e3e9f74d2b":{
      "scriptId":"u62"},
    "50b8aec22ef04879bbbea34b902aef24":{
      "scriptId":"u63"},
    "ed1016ffa010489cabe73946d50fd923":{
      "scriptId":"u64"},
    "901ebccc06964488abebf2aab67287a2":{
      "scriptId":"u65"},
    "cc094439f7da485da8e4720b87af7faa":{
      "scriptId":"u66"},
    "effb459c4baf4369a1bf53aa77938327":{
      "scriptId":"u67"},
    "ad4243467dce4811ab67bcc7af2b1da5":{
      "scriptId":"u68"},
    "cea556d4736349b99b68258afb4fb002":{
      "scriptId":"u69"},
    "9cb26a63a6034d968597fd1f30bb1894":{
      "scriptId":"u70"},
    "8705c692394140f589d53fa683f9091d":{
      "scriptId":"u71"},
    "b8a5851b92db4b8e92c1fdde878954cf":{
      "scriptId":"u72"},
    "13c71a19741f4dcdbc64721887186862":{
      "scriptId":"u73"},
    "4d2deeb4626e4a069ffffd4aa7e0c3e5":{
      "scriptId":"u74"},
    "4435ad27239f4d07961114b192db67ab":{
      "scriptId":"u75"},
    "934129b6c5d8497e8909b4b5eeef7bb4":{
      "scriptId":"u76"},
    "b027ad41aeb8467f908a2d4017bef744":{
      "scriptId":"u77"},
    "2cdf621fbd7c45d9bd7cd831a615e892":{
      "scriptId":"u78"},
    "3846a9fd80484a67b60e7602a1d016e8":{
      "scriptId":"u79"},
    "9258de71b8f443f0b74ac27f249d894d":{
      "scriptId":"u80"},
    "14f06672504e4e4ab1c4165f7554acf5":{
      "scriptId":"u81"},
    "99823eb37a494d86a2e7ea4c918f8209":{
      "scriptId":"u82"},
    "66b1da07c43f4c1d92157bf3d5edc32b":{
      "scriptId":"u83"},
    "52b7e532e743483ebfbc8aa314e69e86":{
      "scriptId":"u84"},
    "6d926e153f614cdabd8792d3fd31b809":{
      "scriptId":"u85"},
    "7fa3f51b59c249978e911fad34a106bf":{
      "scriptId":"u86"}}});