$axure.loadCurrentPage({
  "url":"我.html",
  "generationDate":new Date(1414464499509.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"82d7d16275c34c73b089f920c52bb06c",
    "type":"Axure:Page",
    "name":"我",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ec2686c2663e4ba99c14a56209e80267",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":10},
            "size":{
              "width":794,
              "height":1487}},
          "adaptiveStyles":{
},
          "masterId":"984fa132bdee4430802a486dd3e5c298"},
{
          "id":"9264ff094b77447cb01e7761ee859bb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"bold",
            "location":{
              "x":182,
              "y":403},
            "size":{
              "width":638,
              "height":134}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16ba69fffdbb4de88c90980be7339295",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"bold",
                "location":{
                  "x":182,
                  "y":403},
                "size":{
                  "width":638,
                  "height":134}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我/u21.png"}},
{
          "id":"382db7f900014ca9a8543fabe37376b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":221,
              "y":566},
            "size":{
              "width":116,
              "height":116},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"234c5f3a3c2b41bcb417d4e0de56e69b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":221,
                  "y":566},
                "size":{
                  "width":116,
                  "height":116},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我/u23.png"}},
{
          "id":"7c8f6179b65247bf878796e8337f876c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":360,
              "y":566},
            "size":{
              "width":116,
              "height":116},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1666c545fca4432fae0e98eb324981c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":360,
                  "y":566},
                "size":{
                  "width":116,
                  "height":116},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我/u23.png"}},
{
          "id":"bf050bc8d9414d439b696fbdecad2ffc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":640,
              "y":566},
            "size":{
              "width":116,
              "height":116},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b896ccf48dd4cfe85a0a5f2dc1b2bd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":640,
                  "y":566},
                "size":{
                  "width":116,
                  "height":116},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我/u23.png"}},
{
          "id":"2cd48e2c1ace4034bdd010696e728d3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":500,
              "y":566},
            "size":{
              "width":116,
              "height":116},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbe270fef30048ae8241e12d46af3569",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":500,
                  "y":566},
                "size":{
                  "width":116,
                  "height":116},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我/u23.png"}},
{
          "id":"ca1ee0a762b14987a30066f70b593b3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"66px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":361,
              "y":706},
            "size":{
              "width":116,
              "height":116},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ab148186e534d8ea46a5438cc9c4275",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"66px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":361,
                  "y":706},
                "size":{
                  "width":116,
                  "height":116},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我/u23.png"}},
{
          "id":"08774fd26f9f4147bb85561ccd573d83",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":221,
              "y":706},
            "size":{
              "width":116,
              "height":116},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34443d39484846e4836cf3b37e1afe51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":221,
                  "y":706},
                "size":{
                  "width":116,
                  "height":116},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我/u23.png"}},
{
          "id":"c087b72bbc1b4adc85f1d1861e323ed5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"33px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF8F8F8},
            "location":{
              "x":181,
              "y":317},
            "size":{
              "width":639,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35fe9d21b9924718978fb24b22e9bb1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"33px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF8F8F8},
                "location":{
                  "x":181,
                  "y":317},
                "size":{
                  "width":639,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u20.png"}},
{
          "id":"9e1fe30341c1486eb9e0e9e4683b429f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"bold",
            "location":{
              "x":201,
              "y":341},
            "size":{
              "width":38,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d30daeed51944d17b651f5b41536160b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"bold",
                "location":{
                  "x":201,
                  "y":341},
                "size":{
                  "width":38,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/装修流程/u32.png"}},
{
          "id":"0b3b716868f0460ba13f4f3457458f33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6633,
              "opacity":1},
            "location":{
              "x":747,
              "y":352},
            "size":{
              "width":52,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b1b3100cccb4267b35f1b99a4554021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6633,
                  "opacity":1},
                "location":{
                  "x":747,
                  "y":352},
                "size":{
                  "width":52,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆页",
                      "target":{
                        "targetType":"page",
                        "url":"登陆页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a91ce9769c54c6db55a986716edae45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":431},
            "size":{
              "width":78,
              "height":78},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b1b58132f054b089284d1fb58d1165c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":431},
                "size":{
                  "width":78,
                  "height":78},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我/u41.png"}}]}},
  "masters":{
    "984fa132bdee4430802a486dd3e5c298":{
      "packageId":"984fa132bdee4430802a486dd3e5c298",
      "type":"Axure:Master",
      "name":"shoujixin",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0924992c31c149048016d672e5c7f726",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":794,
                "height":1487},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18279859f5f846ce8c3645a511e3061b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":794,
                    "height":1487},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u0.jpg"}},
{
            "id":"70f92109e52a40af94df453ebb3e8fd2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":307},
              "size":{
                "width":640,
                "height":822},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1a0f733bad824f2595138b3ed7ed226f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":80,
                    "y":307},
                  "size":{
                    "width":640,
                    "height":822},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u2.png"}},
{
            "id":"afaeff7a64e54c80962de48a01e9fe2c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":1129},
              "size":{
                "width":640,
                "height":97},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"74df996240be4f2eae72b660a9d138d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":80,
                    "y":1129},
                  "size":{
                    "width":640,
                    "height":97},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u4.png"}},
{
            "id":"ad28bbac596b43b58a7b09fd8c61d066",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":368,
                "y":1139},
              "size":{
                "width":39,
                "height":36},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fd172ca0c7684ee3a771250caa2a4708",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":368,
                    "y":1139},
                  "size":{
                    "width":39,
                    "height":36},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u6.png"}},
{
            "id":"00913d450cdc4fcaa0b8e0987daf0158",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":580,
                "y":1141},
              "size":{
                "width":39,
                "height":33},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"23e12321df4e4b8e918b93a4238c0b2e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":580,
                    "y":1141},
                  "size":{
                    "width":39,
                    "height":33},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u8.png"}},
{
            "id":"6aff273e7ae443acaad54ef5d53ef650",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":175,
                "y":1143},
              "size":{
                "width":38,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"895a51871df84fdeb64de494f9ded835",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":175,
                    "y":1143},
                  "size":{
                    "width":38,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u10.png"}},
{
            "id":"f64805ae112045e2acbffd535c1532ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":327,
                "y":1134},
              "size":{
                "width":123,
                "height":92},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"46456e5bf1a64ccf8f309dbbddbdde36",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":327,
                    "y":1134},
                  "size":{
                    "width":123,
                    "height":92},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"153adc10da0545eb85d07f4f4553ba83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":539,
                "y":1134},
              "size":{
                "width":123,
                "height":92},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2071049e0e8d4b418468c9a8514ed7e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":539,
                    "y":1134},
                  "size":{
                    "width":123,
                    "height":92},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登陆页",
                        "target":{
                          "targetType":"page",
                          "url":"登陆页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bb67617ebb764a5ba40a60393669df03",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":132,
                "y":1129},
              "size":{
                "width":123,
                "height":92},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"35fcb7f3ba564c56a8900c8c914f3812",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":132,
                    "y":1129},
                  "size":{
                    "width":123,
                    "height":92},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 聊天",
                        "target":{
                          "targetType":"page",
                          "url":"聊天.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ca7ebea22b8a48e9a088034eb7d63cfb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFF0000},
              "location":{
                "x":223,
                "y":1139},
              "size":{
                "width":11,
                "height":11},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24509502b78240de82bb50d987c9e129",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF0000},
                  "location":{
                    "x":223,
                    "y":1139},
                  "size":{
                    "width":11,
                    "height":11},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/确定施工方式简介/u19.png"}}]}}},
  "objectPaths":{
    "ec2686c2663e4ba99c14a56209e80267":{
      "scriptId":"u0",
      "0924992c31c149048016d672e5c7f726":{
        "scriptId":"u1"},
      "18279859f5f846ce8c3645a511e3061b":{
        "scriptId":"u2"},
      "70f92109e52a40af94df453ebb3e8fd2":{
        "scriptId":"u3"},
      "1a0f733bad824f2595138b3ed7ed226f":{
        "scriptId":"u4"},
      "afaeff7a64e54c80962de48a01e9fe2c":{
        "scriptId":"u5"},
      "74df996240be4f2eae72b660a9d138d3":{
        "scriptId":"u6"},
      "ad28bbac596b43b58a7b09fd8c61d066":{
        "scriptId":"u7"},
      "fd172ca0c7684ee3a771250caa2a4708":{
        "scriptId":"u8"},
      "00913d450cdc4fcaa0b8e0987daf0158":{
        "scriptId":"u9"},
      "23e12321df4e4b8e918b93a4238c0b2e":{
        "scriptId":"u10"},
      "6aff273e7ae443acaad54ef5d53ef650":{
        "scriptId":"u11"},
      "895a51871df84fdeb64de494f9ded835":{
        "scriptId":"u12"},
      "f64805ae112045e2acbffd535c1532ea":{
        "scriptId":"u13"},
      "46456e5bf1a64ccf8f309dbbddbdde36":{
        "scriptId":"u14"},
      "153adc10da0545eb85d07f4f4553ba83":{
        "scriptId":"u15"},
      "2071049e0e8d4b418468c9a8514ed7e2":{
        "scriptId":"u16"},
      "bb67617ebb764a5ba40a60393669df03":{
        "scriptId":"u17"},
      "35fcb7f3ba564c56a8900c8c914f3812":{
        "scriptId":"u18"},
      "ca7ebea22b8a48e9a088034eb7d63cfb":{
        "scriptId":"u19"},
      "24509502b78240de82bb50d987c9e129":{
        "scriptId":"u20"}},
    "9264ff094b77447cb01e7761ee859bb2":{
      "scriptId":"u21"},
    "16ba69fffdbb4de88c90980be7339295":{
      "scriptId":"u22"},
    "382db7f900014ca9a8543fabe37376b4":{
      "scriptId":"u23"},
    "234c5f3a3c2b41bcb417d4e0de56e69b":{
      "scriptId":"u24"},
    "7c8f6179b65247bf878796e8337f876c":{
      "scriptId":"u25"},
    "1666c545fca4432fae0e98eb324981c6":{
      "scriptId":"u26"},
    "bf050bc8d9414d439b696fbdecad2ffc":{
      "scriptId":"u27"},
    "0b896ccf48dd4cfe85a0a5f2dc1b2bd2":{
      "scriptId":"u28"},
    "2cd48e2c1ace4034bdd010696e728d3f":{
      "scriptId":"u29"},
    "fbe270fef30048ae8241e12d46af3569":{
      "scriptId":"u30"},
    "ca1ee0a762b14987a30066f70b593b3c":{
      "scriptId":"u31"},
    "1ab148186e534d8ea46a5438cc9c4275":{
      "scriptId":"u32"},
    "08774fd26f9f4147bb85561ccd573d83":{
      "scriptId":"u33"},
    "34443d39484846e4836cf3b37e1afe51":{
      "scriptId":"u34"},
    "c087b72bbc1b4adc85f1d1861e323ed5":{
      "scriptId":"u35"},
    "35fe9d21b9924718978fb24b22e9bb1b":{
      "scriptId":"u36"},
    "9e1fe30341c1486eb9e0e9e4683b429f":{
      "scriptId":"u37"},
    "d30daeed51944d17b651f5b41536160b":{
      "scriptId":"u38"},
    "0b3b716868f0460ba13f4f3457458f33":{
      "scriptId":"u39"},
    "9b1b3100cccb4267b35f1b99a4554021":{
      "scriptId":"u40"},
    "1a91ce9769c54c6db55a986716edae45":{
      "scriptId":"u41"},
    "4b1b58132f054b089284d1fb58d1165c":{
      "scriptId":"u42"}}});