$axure.loadCurrentPage({
  "url":"客户个人信息.html",
  "generationDate":new Date(1417673125722.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0293044c8b7f4b8293e648c8e1feeb57",
    "type":"Axure:Page",
    "name":"客户个人信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0efa155a16844225b55ab50cdfd9a426",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":25},
            "size":{
              "width":320,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29f345572e224c8fa1a25ec2b258109c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":25},
                "size":{
                  "width":320,
                  "height":495}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u0.png"}},
{
          "id":"6d582b4edd554188b78ef19a98b0635e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":70,
              "y":25},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c6517be97524332a3940ba0e711ab03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":70,
                  "y":25},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u2.png"}},
{
          "id":"768fd70819b84b12a398e3bcf4b1cc85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":85},
            "size":{
              "width":46,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1992e5d90394a77ad5e2eb3a7b4cd74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":85},
                "size":{
                  "width":46,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u56.png"}},
{
          "id":"e82a9cfdf3f44c92ba96e10b2ed75bca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":87},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d0c0b2a4b8949358d2b7b8a988ac911",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":87},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94507a81ab4b424ebdb3e9a674ad159e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":135},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/客户个人信息/u8_line.png"}},
{
          "id":"e8436c102828400d836e2266bc4da174",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":167,
              "y":109},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f76109f44eed48e8a786721ac0253bac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":167,
                  "y":109},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b92caf5fb0f44b948a83f42e86a48f99",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":77,
              "y":290},
            "size":{
              "width":302,
              "height":230},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"468b8b91c1814635bf48f8169f2ba46e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":77,
                  "y":290},
                "size":{
                  "width":302,
                  "height":230},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户个人信息/u11.png"}},
{
          "id":"830c3effe489488792796cba62c4291e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":182},
            "size":{
              "width":179,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7b7707328fd4abb94dfc0ef1696ae4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":182},
                "size":{
                  "width":179,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a00415da43be4237bcbd070d04353ed9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":145},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcaa02689f554e58b22fcd63890ca87d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":145},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e14950edb1c240d48b01b0066cc0c335",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":145},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ffc03af62b6493984466dcc2a882f72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":145},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e74ba203776e48588ab999dab6628f19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":208},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1de4dabd83444ff8dd72b193f94d0d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":208},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c90f6bb387dd48718478fb38adae8811",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":446},
            "size":{
              "width":209,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1cee661ec2c46348a09f2255fe86afe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":446},
                "size":{
                  "width":209,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be64bd6ad66d46449e55c1a602ebe3ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":530},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66bd694bd24947a8954925b4cedf43d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":530},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4ba94f6589146838ef30131a1cd573c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":162},
            "size":{
              "width":306,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/客户个人信息/u25_line.png"}},
{
          "id":"6eb856c478494df7b60c9e4afd9ea68f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":424},
            "size":{
              "width":156,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3450ec3162b42259eef7f69ac29cc8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":424},
                "size":{
                  "width":156,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed20e90a5b0249f78ec11b88ad0f3268",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":234},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"348aac572a804008acd50341ec75ac47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":234},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e1ca646700d48f0bcbe5706c1153a6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":274},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea78f61ed39e4b47a3af5327d6aa63cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":274},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5d95b5bb1cc4da187982a01781d0b8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":300},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7c8cb1b6a364c2e99cc7060a656f4a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":300},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"beb9027fed3a41dd93b8bfff3d8cdf6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":324},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c979c88cdf048579dafbf52ddd3b37a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":324},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"427f9c925e4247b29b54ab2ca128088d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":350},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8febe5b80b1c49da83179341ee3cb1cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":350},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e09a8cbb1cf473ab3e5563ec9112200",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":376},
            "size":{
              "width":131,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cd7c2e5c1934beea217d80db0ee2d0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":376},
                "size":{
                  "width":131,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a377efecd3064e8289d439f55eef1fba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":402},
            "size":{
              "width":93,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f5d48bd3b9c435b8df3631b80bc80bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":402},
                "size":{
                  "width":93,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8edb84d5551b4c588cc55e410eb263c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":470},
            "size":{
              "width":269,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0efa72f7737f45c9bb25f008f06d3655",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":470},
                "size":{
                  "width":269,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e01a31bf6584013a7d28fd9b4e669fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":134,
              "y":528},
            "size":{
              "width":200,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a78a655ff2b5434a87316b249955b597",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":134,
                  "y":528},
                "size":{
                  "width":200,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户个人信息/u44.png"}},
{
          "id":"189df6b79a764004bf25bda6a1bcd512",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":234},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cad7f8a506e3404cbe7c1c6e997fb717",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":224,
                  "y":234},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82b0f5fb491c4d57b55e8260e70b5ca0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":208},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62fc654161b349bc917f28b407a15b27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":208},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70acda7847934c54a33ef4560339dc33",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":0},
            "size":{
              "width":323,
              "height":708}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"369494b34662401d980c390eba0fdca9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":0},
                "size":{
                  "width":323,
                  "height":708}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户个人信息/u50.jpg"}},
{
          "id":"42d871ed134f4de9aec5d2983628efad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF66CC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "location":{
              "x":197,
              "y":103},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69a04b4158704f63a28b0d5f854e2a8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF66CC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "location":{
                  "x":197,
                  "y":103},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户个人信息/u52.png"}},
{
          "id":"9b3c9735bd4345ba8cff2e4bd828275a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":70,
              "y":25},
            "size":{
              "width":33,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c379c942ddb84006b99107a332956b99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":70,
                  "y":25},
                "size":{
                  "width":33,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全部客户",
                      "target":{
                        "targetType":"page",
                        "url":"全部客户.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13c2b4dccb9f4d5d9f33f5c475fbe9cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":590},
            "size":{
              "width":370,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ab447e564394c4aa7a60755a43a1a4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":590},
                "size":{
                  "width":370,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户个人信息/u56.png"}},
{
          "id":"0777f4a5d2314b9a9c8c0e1f175c0e4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":155,
              "y":135},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1db10cff7dba4517b2d531d79f67cd52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":155,
                  "y":135},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户个人信息/u58.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0efa155a16844225b55ab50cdfd9a426":{
      "scriptId":"u0"},
    "29f345572e224c8fa1a25ec2b258109c":{
      "scriptId":"u1"},
    "6d582b4edd554188b78ef19a98b0635e":{
      "scriptId":"u2"},
    "0c6517be97524332a3940ba0e711ab03":{
      "scriptId":"u3"},
    "768fd70819b84b12a398e3bcf4b1cc85":{
      "scriptId":"u4"},
    "c1992e5d90394a77ad5e2eb3a7b4cd74":{
      "scriptId":"u5"},
    "e82a9cfdf3f44c92ba96e10b2ed75bca":{
      "scriptId":"u6"},
    "9d0c0b2a4b8949358d2b7b8a988ac911":{
      "scriptId":"u7"},
    "94507a81ab4b424ebdb3e9a674ad159e":{
      "scriptId":"u8"},
    "e8436c102828400d836e2266bc4da174":{
      "scriptId":"u9"},
    "f76109f44eed48e8a786721ac0253bac":{
      "scriptId":"u10"},
    "b92caf5fb0f44b948a83f42e86a48f99":{
      "scriptId":"u11"},
    "468b8b91c1814635bf48f8169f2ba46e":{
      "scriptId":"u12"},
    "830c3effe489488792796cba62c4291e":{
      "scriptId":"u13"},
    "f7b7707328fd4abb94dfc0ef1696ae4d":{
      "scriptId":"u14"},
    "a00415da43be4237bcbd070d04353ed9":{
      "scriptId":"u15"},
    "dcaa02689f554e58b22fcd63890ca87d":{
      "scriptId":"u16"},
    "e14950edb1c240d48b01b0066cc0c335":{
      "scriptId":"u17"},
    "4ffc03af62b6493984466dcc2a882f72":{
      "scriptId":"u18"},
    "e74ba203776e48588ab999dab6628f19":{
      "scriptId":"u19"},
    "d1de4dabd83444ff8dd72b193f94d0d2":{
      "scriptId":"u20"},
    "c90f6bb387dd48718478fb38adae8811":{
      "scriptId":"u21"},
    "a1cee661ec2c46348a09f2255fe86afe":{
      "scriptId":"u22"},
    "be64bd6ad66d46449e55c1a602ebe3ae":{
      "scriptId":"u23"},
    "66bd694bd24947a8954925b4cedf43d0":{
      "scriptId":"u24"},
    "a4ba94f6589146838ef30131a1cd573c":{
      "scriptId":"u25"},
    "6eb856c478494df7b60c9e4afd9ea68f":{
      "scriptId":"u26"},
    "d3450ec3162b42259eef7f69ac29cc8a":{
      "scriptId":"u27"},
    "ed20e90a5b0249f78ec11b88ad0f3268":{
      "scriptId":"u28"},
    "348aac572a804008acd50341ec75ac47":{
      "scriptId":"u29"},
    "4e1ca646700d48f0bcbe5706c1153a6a":{
      "scriptId":"u30"},
    "ea78f61ed39e4b47a3af5327d6aa63cb":{
      "scriptId":"u31"},
    "c5d95b5bb1cc4da187982a01781d0b8e":{
      "scriptId":"u32"},
    "b7c8cb1b6a364c2e99cc7060a656f4a2":{
      "scriptId":"u33"},
    "beb9027fed3a41dd93b8bfff3d8cdf6e":{
      "scriptId":"u34"},
    "2c979c88cdf048579dafbf52ddd3b37a":{
      "scriptId":"u35"},
    "427f9c925e4247b29b54ab2ca128088d":{
      "scriptId":"u36"},
    "8febe5b80b1c49da83179341ee3cb1cf":{
      "scriptId":"u37"},
    "8e09a8cbb1cf473ab3e5563ec9112200":{
      "scriptId":"u38"},
    "6cd7c2e5c1934beea217d80db0ee2d0d":{
      "scriptId":"u39"},
    "a377efecd3064e8289d439f55eef1fba":{
      "scriptId":"u40"},
    "5f5d48bd3b9c435b8df3631b80bc80bf":{
      "scriptId":"u41"},
    "8edb84d5551b4c588cc55e410eb263c7":{
      "scriptId":"u42"},
    "0efa72f7737f45c9bb25f008f06d3655":{
      "scriptId":"u43"},
    "8e01a31bf6584013a7d28fd9b4e669fb":{
      "scriptId":"u44"},
    "a78a655ff2b5434a87316b249955b597":{
      "scriptId":"u45"},
    "189df6b79a764004bf25bda6a1bcd512":{
      "scriptId":"u46"},
    "cad7f8a506e3404cbe7c1c6e997fb717":{
      "scriptId":"u47"},
    "82b0f5fb491c4d57b55e8260e70b5ca0":{
      "scriptId":"u48"},
    "62fc654161b349bc917f28b407a15b27":{
      "scriptId":"u49"},
    "70acda7847934c54a33ef4560339dc33":{
      "scriptId":"u50"},
    "369494b34662401d980c390eba0fdca9":{
      "scriptId":"u51"},
    "42d871ed134f4de9aec5d2983628efad":{
      "scriptId":"u52"},
    "69a04b4158704f63a28b0d5f854e2a8d":{
      "scriptId":"u53"},
    "9b3c9735bd4345ba8cff2e4bd828275a":{
      "scriptId":"u54"},
    "c379c942ddb84006b99107a332956b99":{
      "scriptId":"u55"},
    "13c2b4dccb9f4d5d9f33f5c475fbe9cc":{
      "scriptId":"u56"},
    "2ab447e564394c4aa7a60755a43a1a4f":{
      "scriptId":"u57"},
    "0777f4a5d2314b9a9c8c0e1f175c0e4c":{
      "scriptId":"u58"},
    "1db10cff7dba4517b2d531d79f67cd52":{
      "scriptId":"u59"}}});