$axure.loadCurrentPage({
  "url":"主页.html",
  "generationDate":new Date(1415687652239.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"385bd680c71e4c63a5b607fdff0694f2",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c9b7b6bcf0f54f7386ca294a2b5d74a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":102,
              "y":11},
            "size":{
              "width":794,
              "height":1487},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e697df1d13a419fb8ec260a496d0859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":102,
                  "y":11},
                "size":{
                  "width":794,
                  "height":1487},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.jpg"}},
{
          "id":"30ad2d69caea4944bfab741cdb4a26b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":182,
              "y":318},
            "size":{
              "width":640,
              "height":822},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb31086dc71d47f6993c63f78f04fa67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":182,
                  "y":318},
                "size":{
                  "width":640,
                  "height":822},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u2.png"}},
{
          "id":"7c17a9ca88f541c1baeaf4cf9931beaf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":182,
              "y":1140},
            "size":{
              "width":640,
              "height":97},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c98443f582b24bfda07bc0ba42e04110",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":182,
                  "y":1140},
                "size":{
                  "width":640,
                  "height":97},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"5470dc241d304d14a66100a57ba36e58",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":1150},
            "size":{
              "width":39,
              "height":36},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9972ad6003774ff7b1cae00a17230273",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":1150},
                "size":{
                  "width":39,
                  "height":36},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u6.png"}},
{
          "id":"06f7a2ef7d624eabae7f6239d590f17f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":682,
              "y":1152},
            "size":{
              "width":39,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8895e31dd54474e92709ac79f996675",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":682,
                  "y":1152},
                "size":{
                  "width":39,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"6c5cdfc1f0ec473ca937dcc7b526729a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":1154},
            "size":{
              "width":38,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19b4769b45564530afe3b4a6df06c74f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":1154},
                "size":{
                  "width":38,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u10.png"}},
{
          "id":"6ed0d3b38adc4071a45264fe0f796e3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":429,
              "y":1145},
            "size":{
              "width":123,
              "height":92},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c9ab44cb0e74de6a0feffc4001e8e6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":429,
                  "y":1145},
                "size":{
                  "width":123,
                  "height":92},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1f03d0ee8114d48b6f25cbb720711fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":641,
              "y":1145},
            "size":{
              "width":123,
              "height":92},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e7147c17ef94953a29ab1fe75499733",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":641,
                  "y":1145},
                "size":{
                  "width":123,
                  "height":92},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆页",
                      "target":{
                        "targetType":"page",
                        "url":"登陆页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3edd4aabb44f4b518d8b63ec51e96e74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":234,
              "y":1140},
            "size":{
              "width":123,
              "height":92},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28854cdef59c4ae8b85636233b084e1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":234,
                  "y":1140},
                "size":{
                  "width":123,
                  "height":92},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天列表",
                      "target":{
                        "targetType":"page",
                        "url":"聊天列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e6f2167cea44f4da0ff493e672f298d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":445},
            "size":{
              "width":517,
              "height":571},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2804d261850e4597888e168bb8dda44e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":445},
                "size":{
                  "width":517,
                  "height":571},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u18.png"}},
{
          "id":"4f54513848034e23840ac6954e8d416e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"33px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF8F8F8},
            "location":{
              "x":183,
              "y":317},
            "size":{
              "width":639,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0944686498a48ca840c07ec2262593b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"33px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF8F8F8},
                "location":{
                  "x":183,
                  "y":317},
                "size":{
                  "width":639,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u20.png"}},
{
          "id":"00fb6cfdeefb444ebf0d3da7f56ac1d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":416,
              "y":656},
            "size":{
              "width":180,
              "height":163},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"141575521d844bdc8dcb112c85308b0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":416,
                  "y":656},
                "size":{
                  "width":180,
                  "height":163},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 流程新",
                      "target":{
                        "targetType":"page",
                        "url":"流程新.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7ef9c5a85cc4a0b8e6240a3a32e4b23",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"21px",
            "location":{
              "x":330,
              "y":505},
            "size":{
              "width":149,
              "height":168},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f59ce34a9234499bc36a1ecf9a0fa3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"21px",
                "location":{
                  "x":330,
                  "y":505},
                "size":{
                  "width":149,
                  "height":168},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蓝景丽家",
                      "target":{
                        "targetType":"page",
                        "url":"蓝景丽家.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c9b7b6bcf0f54f7386ca294a2b5d74a5":{
      "scriptId":"u0"},
    "6e697df1d13a419fb8ec260a496d0859":{
      "scriptId":"u1"},
    "30ad2d69caea4944bfab741cdb4a26b6":{
      "scriptId":"u2"},
    "bb31086dc71d47f6993c63f78f04fa67":{
      "scriptId":"u3"},
    "7c17a9ca88f541c1baeaf4cf9931beaf":{
      "scriptId":"u4"},
    "c98443f582b24bfda07bc0ba42e04110":{
      "scriptId":"u5"},
    "5470dc241d304d14a66100a57ba36e58":{
      "scriptId":"u6"},
    "9972ad6003774ff7b1cae00a17230273":{
      "scriptId":"u7"},
    "06f7a2ef7d624eabae7f6239d590f17f":{
      "scriptId":"u8"},
    "f8895e31dd54474e92709ac79f996675":{
      "scriptId":"u9"},
    "6c5cdfc1f0ec473ca937dcc7b526729a":{
      "scriptId":"u10"},
    "19b4769b45564530afe3b4a6df06c74f":{
      "scriptId":"u11"},
    "6ed0d3b38adc4071a45264fe0f796e3e":{
      "scriptId":"u12"},
    "3c9ab44cb0e74de6a0feffc4001e8e6b":{
      "scriptId":"u13"},
    "b1f03d0ee8114d48b6f25cbb720711fb":{
      "scriptId":"u14"},
    "8e7147c17ef94953a29ab1fe75499733":{
      "scriptId":"u15"},
    "3edd4aabb44f4b518d8b63ec51e96e74":{
      "scriptId":"u16"},
    "28854cdef59c4ae8b85636233b084e1d":{
      "scriptId":"u17"},
    "9e6f2167cea44f4da0ff493e672f298d":{
      "scriptId":"u18"},
    "2804d261850e4597888e168bb8dda44e":{
      "scriptId":"u19"},
    "4f54513848034e23840ac6954e8d416e":{
      "scriptId":"u20"},
    "e0944686498a48ca840c07ec2262593b":{
      "scriptId":"u21"},
    "00fb6cfdeefb444ebf0d3da7f56ac1d3":{
      "scriptId":"u22"},
    "141575521d844bdc8dcb112c85308b0f":{
      "scriptId":"u23"},
    "b7ef9c5a85cc4a0b8e6240a3a32e4b23":{
      "scriptId":"u24"},
    "2f59ce34a9234499bc36a1ecf9a0fa3e":{
      "scriptId":"u25"}}});