$axure.loadCurrentPage({
  "url":"设计师个人信息.html",
  "generationDate":new Date(1417506161750),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"64f16ab3b79d4ffd8b4aa1c880f43dd2",
    "type":"Axure:Page",
    "name":"设计师个人信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1708b5d15ceb4c25994fc76bc32299f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":0},
            "size":{
              "width":350,
              "height":26},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"157b0ffeb38b48088f59e699ee66efed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":0},
                "size":{
                  "width":350,
                  "height":26},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天界面/u2.png"}},
{
          "id":"422bc911fda94a8d98be3ca485e5a3b5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":0},
            "size":{
              "width":46,
              "height":26},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c06d942ce1d44cce9318939eef488300",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":0},
                "size":{
                  "width":46,
                  "height":26},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天界面/u4.png"}},
{
          "id":"cf213cb45e844c0da9e3c4e7d8f9d8b5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":61},
            "size":{
              "width":46,
              "height":567},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20381c5871fc46d9bbf0ad1f4302c271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":61},
                "size":{
                  "width":46,
                  "height":567},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天界面/u8.png"}},
{
          "id":"8b5f5857c1aa4fb8b7e7b73f6b34b4cf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":399,
              "y":26},
            "size":{
              "width":1,
              "height":34},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e7d7dd224c24905b66fdd0775e5e0c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":399,
                  "y":26},
                "size":{
                  "width":1,
                  "height":34},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天界面/u10.png"}},
{
          "id":"5c9137c845964b21aa8f62e829da5d05",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":399,
              "y":61},
            "size":{
              "width":1,
              "height":567},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49fbaa9178614a88bec4b25625865213",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":399,
                  "y":61},
                "size":{
                  "width":1,
                  "height":567},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天界面/u12.png"}},
{
          "id":"a8abf4c5eea0449f976826c78642a779",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":399,
              "y":0},
            "size":{
              "width":1,
              "height":26},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"871a8afc898f421295cb80173cc9038c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":399,
                  "y":0},
                "size":{
                  "width":1,
                  "height":26},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天界面/u14.png"}},
{
          "id":"4d7f190d55b9492fb8ae6135cb4ef426",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":61},
            "size":{
              "width":350,
              "height":567},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21aade3f75d14968ad5a4329a389b3dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":61},
                "size":{
                  "width":350,
                  "height":567},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天界面/u16.png"}},
{
          "id":"cc944f99a83e4e74aa8ef8da3b338e1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "location":{
              "x":5,
              "y":60},
            "size":{
              "width":395,
              "height":1131},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac921458d81f4f78814e85245c196037",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "location":{
                  "x":5,
                  "y":60},
                "size":{
                  "width":395,
                  "height":1131},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师个人信息/u14.png"}},
{
          "id":"b3cc42de4d844ae3af8a4139b37d1591",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF454B57},
            "location":{
              "x":4,
              "y":25},
            "size":{
              "width":396,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10ed63e5db1344dd8545dd8bab5dfd09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF454B57},
                "location":{
                  "x":4,
                  "y":25},
                "size":{
                  "width":396,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师个人信息/u16.png"}},
{
          "id":"c44806eba0ba45ccb8713fc16fb1c6f4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":40},
            "size":{
              "width":14,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/收藏列表/u20_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/收藏列表/u20_line.png"}},
{
          "id":"192d96ee91ef489cb7098e29e70095fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "location":{
              "x":107,
              "y":122},
            "size":{
              "width":107,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2903a5db1eb449618bbb5b136c3ce373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "location":{
                  "x":107,
                  "y":122},
                "size":{
                  "width":107,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4704eda851704cc2a487e5bec8e4a8ce",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":26},
            "size":{
              "width":33,
              "height":33}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天界面",
                      "target":{
                        "targetType":"page",
                        "url":"聊天界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"931f7deb4e5e4b9e91e1c88629a5f35e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":107,
              "y":139},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74c6e8b7f3b54229b417d3fe9c9471a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":107,
                  "y":139},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c19b2c04564480f9cc0f029470e4bfe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":528},
            "size":{
              "width":384,
              "height":191},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"555a7fbedb004e66a7bb73b2f1adf0df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":528},
                "size":{
                  "width":384,
                  "height":191},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师个人信息/u24.png"}},
{
          "id":"ed129d5f4d054e8c9a514158fd6afc3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x56FFFFFF},
            "location":{
              "x":11,
              "y":696},
            "size":{
              "width":384,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd1737a63a0e41b880fbb12d150af305",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x56FFFFFF},
                "location":{
                  "x":11,
                  "y":696},
                "size":{
                  "width":384,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师个人信息/u26.png"}},
{
          "id":"5d427412f88f439da12dfa55f431cd4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":188},
            "size":{
              "width":394,
              "height":93},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21374b94f66d4c2f8de716ea9bfe1d6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":188},
                "size":{
                  "width":394,
                  "height":93},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师个人信息/u28.png"}},
{
          "id":"f0cc63052461443395b7d22039dd1536",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":18,
              "y":199},
            "size":{
              "width":235,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"423c53766e9b49adaeb274f6eb8eaed2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":199},
                "size":{
                  "width":235,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a438d7a4946c4fe6bf3dcaa816d8316a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":18,
              "y":226},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2ba82f386ed4e7d8edf4f6118fdde45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":226},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7954ba78e4b46ae862179cd1bfbe266",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":18,
              "y":257},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48cdbe1a8aa34a46b84a0c7f48d98a21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":257},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0db00753755949acbf54e02e2a819eee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":5,
              "y":278},
            "size":{
              "width":395,
              "height":104},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beae3a0f1a9240efb81b259fec215ceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":5,
                  "y":278},
                "size":{
                  "width":395,
                  "height":104},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师个人信息/u36.png"}},
{
          "id":"b0e26c68812f4604962c405eb439c614",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":214},
            "size":{
              "width":364,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/设计师个人信息/u38_line.png"}},
{
          "id":"0814032c336546d8ab222318311fa01d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":245},
            "size":{
              "width":364,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/设计师个人信息/u38_line.png"}},
{
          "id":"518b85b5b59a4cf0b5d680562219b500",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":309},
            "size":{
              "width":364,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/设计师个人信息/u38_line.png"}},
{
          "id":"3b90687646e44b86a267433651eabfc3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":342},
            "size":{
              "width":364,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/设计师个人信息/u38_line.png"}},
{
          "id":"5e5107b576694e739503339737aa8601",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":19,
              "y":291},
            "size":{
              "width":162,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f370b92490a4391a70e4196cc1ec093",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":291},
                "size":{
                  "width":162,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69a2838622ef42a786064b669c9ede68",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":19,
              "y":321},
            "size":{
              "width":247,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac8ccfda772a412d9e373db2f8c93ada",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":321},
                "size":{
                  "width":247,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b689a60f2ba473e99097d962a9ed542",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":19,
              "y":355},
            "size":{
              "width":284,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a72c2109300c4a1ca4b54f8acdd2d0e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":355},
                "size":{
                  "width":284,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee505070d05b43c8ba3fd6dba9227b7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":5,
              "y":379},
            "size":{
              "width":395,
              "height":98},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb7d5701fc784dd6a19469ceab05a98c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":5,
                  "y":379},
                "size":{
                  "width":395,
                  "height":98},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师个人信息/u48.png"}},
{
          "id":"1da80be29ca3421bb18e7987f544be59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":19,
              "y":389},
            "size":{
              "width":360,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30b3aa00b20147a7879a352e02ca70f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":389},
                "size":{
                  "width":360,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f641f570d51449f2a0d9bfeaf8425258",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":80,
              "y":391},
            "size":{
              "width":295,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42a35daee85e4dd8ad60d374f1d275e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":391},
                "size":{
                  "width":295,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"568bfb1eaf434c9282a33b65bff23bd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7A666666},
            "location":{
              "x":3,
              "y":492},
            "size":{
              "width":398,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e30fb87f54b34f9d9a16a51012a92c70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7A666666},
                "location":{
                  "x":3,
                  "y":492},
                "size":{
                  "width":398,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师个人信息/u54.png"}},
{
          "id":"6e69e06fba1e467a86177e7ab232a34e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":16,
              "y":501},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"051dfcdfcbf2444eb37be937faa7d3c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":501},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9fb69d44a8c94dd9a18403e3905b27ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":724},
            "size":{
              "width":383,
              "height":191},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2fc483a7faf4e6ab488772cf6fe4127",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":724},
                "size":{
                  "width":383,
                  "height":191},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师个人信息/u24.png"}},
{
          "id":"9386727c690e426a9dacf92a1577c063",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x56FFFFFF},
            "location":{
              "x":11,
              "y":892},
            "size":{
              "width":383,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b65e9a9008f47008fa262626ea09978",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x56FFFFFF},
                "location":{
                  "x":11,
                  "y":892},
                "size":{
                  "width":383,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师个人信息/u60.png"}},
{
          "id":"61227f64c9d54037b839733cb174fbf3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":18,
              "y":73},
            "size":{
              "width":79,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46603286d4a04002999e70aa2d7a647d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":18,
                  "y":73},
                "size":{
                  "width":79,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师个人信息/u62.png"}},
{
          "id":"78ead1c7eb8741c6a8acee5410d40ec7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":75},
            "size":{
              "width":92,
              "height":92},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b4bb8de81bc401cb0bbdc7acd420e48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":75},
                "size":{
                  "width":92,
                  "height":92},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师个人信息/u64.png"}},
{
          "id":"55f69f93e255477484bb4f727f4ae713",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":275},
            "size":{
              "width":364,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/设计师个人信息/u38_line.png"}},
{
          "id":"278d7ff5561c444bb526951f5f9ec140",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":373},
            "size":{
              "width":364,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/设计师个人信息/u38_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1708b5d15ceb4c25994fc76bc32299f5":{
      "scriptId":"u0"},
    "157b0ffeb38b48088f59e699ee66efed":{
      "scriptId":"u1"},
    "422bc911fda94a8d98be3ca485e5a3b5":{
      "scriptId":"u2"},
    "c06d942ce1d44cce9318939eef488300":{
      "scriptId":"u3"},
    "cf213cb45e844c0da9e3c4e7d8f9d8b5":{
      "scriptId":"u4"},
    "20381c5871fc46d9bbf0ad1f4302c271":{
      "scriptId":"u5"},
    "8b5f5857c1aa4fb8b7e7b73f6b34b4cf":{
      "scriptId":"u6"},
    "3e7d7dd224c24905b66fdd0775e5e0c7":{
      "scriptId":"u7"},
    "5c9137c845964b21aa8f62e829da5d05":{
      "scriptId":"u8"},
    "49fbaa9178614a88bec4b25625865213":{
      "scriptId":"u9"},
    "a8abf4c5eea0449f976826c78642a779":{
      "scriptId":"u10"},
    "871a8afc898f421295cb80173cc9038c":{
      "scriptId":"u11"},
    "4d7f190d55b9492fb8ae6135cb4ef426":{
      "scriptId":"u12"},
    "21aade3f75d14968ad5a4329a389b3dd":{
      "scriptId":"u13"},
    "cc944f99a83e4e74aa8ef8da3b338e1a":{
      "scriptId":"u14"},
    "ac921458d81f4f78814e85245c196037":{
      "scriptId":"u15"},
    "b3cc42de4d844ae3af8a4139b37d1591":{
      "scriptId":"u16"},
    "10ed63e5db1344dd8545dd8bab5dfd09":{
      "scriptId":"u17"},
    "c44806eba0ba45ccb8713fc16fb1c6f4":{
      "scriptId":"u18"},
    "192d96ee91ef489cb7098e29e70095fa":{
      "scriptId":"u19"},
    "2903a5db1eb449618bbb5b136c3ce373":{
      "scriptId":"u20"},
    "4704eda851704cc2a487e5bec8e4a8ce":{
      "scriptId":"u21"},
    "931f7deb4e5e4b9e91e1c88629a5f35e":{
      "scriptId":"u22"},
    "74c6e8b7f3b54229b417d3fe9c9471a4":{
      "scriptId":"u23"},
    "8c19b2c04564480f9cc0f029470e4bfe":{
      "scriptId":"u24"},
    "555a7fbedb004e66a7bb73b2f1adf0df":{
      "scriptId":"u25"},
    "ed129d5f4d054e8c9a514158fd6afc3f":{
      "scriptId":"u26"},
    "cd1737a63a0e41b880fbb12d150af305":{
      "scriptId":"u27"},
    "5d427412f88f439da12dfa55f431cd4d":{
      "scriptId":"u28"},
    "21374b94f66d4c2f8de716ea9bfe1d6b":{
      "scriptId":"u29"},
    "f0cc63052461443395b7d22039dd1536":{
      "scriptId":"u30"},
    "423c53766e9b49adaeb274f6eb8eaed2":{
      "scriptId":"u31"},
    "a438d7a4946c4fe6bf3dcaa816d8316a":{
      "scriptId":"u32"},
    "a2ba82f386ed4e7d8edf4f6118fdde45":{
      "scriptId":"u33"},
    "c7954ba78e4b46ae862179cd1bfbe266":{
      "scriptId":"u34"},
    "48cdbe1a8aa34a46b84a0c7f48d98a21":{
      "scriptId":"u35"},
    "0db00753755949acbf54e02e2a819eee":{
      "scriptId":"u36"},
    "beae3a0f1a9240efb81b259fec215ceb":{
      "scriptId":"u37"},
    "b0e26c68812f4604962c405eb439c614":{
      "scriptId":"u38"},
    "0814032c336546d8ab222318311fa01d":{
      "scriptId":"u39"},
    "518b85b5b59a4cf0b5d680562219b500":{
      "scriptId":"u40"},
    "3b90687646e44b86a267433651eabfc3":{
      "scriptId":"u41"},
    "5e5107b576694e739503339737aa8601":{
      "scriptId":"u42"},
    "0f370b92490a4391a70e4196cc1ec093":{
      "scriptId":"u43"},
    "69a2838622ef42a786064b669c9ede68":{
      "scriptId":"u44"},
    "ac8ccfda772a412d9e373db2f8c93ada":{
      "scriptId":"u45"},
    "7b689a60f2ba473e99097d962a9ed542":{
      "scriptId":"u46"},
    "a72c2109300c4a1ca4b54f8acdd2d0e7":{
      "scriptId":"u47"},
    "ee505070d05b43c8ba3fd6dba9227b7d":{
      "scriptId":"u48"},
    "eb7d5701fc784dd6a19469ceab05a98c":{
      "scriptId":"u49"},
    "1da80be29ca3421bb18e7987f544be59":{
      "scriptId":"u50"},
    "30b3aa00b20147a7879a352e02ca70f0":{
      "scriptId":"u51"},
    "f641f570d51449f2a0d9bfeaf8425258":{
      "scriptId":"u52"},
    "42a35daee85e4dd8ad60d374f1d275e0":{
      "scriptId":"u53"},
    "568bfb1eaf434c9282a33b65bff23bd9":{
      "scriptId":"u54"},
    "e30fb87f54b34f9d9a16a51012a92c70":{
      "scriptId":"u55"},
    "6e69e06fba1e467a86177e7ab232a34e":{
      "scriptId":"u56"},
    "051dfcdfcbf2444eb37be937faa7d3c3":{
      "scriptId":"u57"},
    "9fb69d44a8c94dd9a18403e3905b27ce":{
      "scriptId":"u58"},
    "a2fc483a7faf4e6ab488772cf6fe4127":{
      "scriptId":"u59"},
    "9386727c690e426a9dacf92a1577c063":{
      "scriptId":"u60"},
    "9b65e9a9008f47008fa262626ea09978":{
      "scriptId":"u61"},
    "61227f64c9d54037b839733cb174fbf3":{
      "scriptId":"u62"},
    "46603286d4a04002999e70aa2d7a647d":{
      "scriptId":"u63"},
    "78ead1c7eb8741c6a8acee5410d40ec7":{
      "scriptId":"u64"},
    "0b4bb8de81bc401cb0bbdc7acd420e48":{
      "scriptId":"u65"},
    "55f69f93e255477484bb4f727f4ae713":{
      "scriptId":"u66"},
    "278d7ff5561c444bb526951f5f9ec140":{
      "scriptId":"u67"}}});