$axure.loadCurrentPage({
  "url":"日程.html",
  "generationDate":new Date(1417146909522.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"aa3a545979054015893753848d8d72bc",
    "type":"Axure:Page",
    "name":"日程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"91f939e3eff646d58de889eef25ba9a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":30},
            "size":{
              "width":320,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03e1c94465c4421999db2e871e774cae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":30},
                "size":{
                  "width":320,
                  "height":495}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u0.png"}},
{
          "id":"3b37b3b9711240e4911a8a3ae0ad1936",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":230,
              "y":30},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c0e976cd98641f38dca7cd9bc7f7c4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":230,
                  "y":30},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u2.png"}},
{
          "id":"e29c07640c654a0382edf213d82c2673",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":106},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26fcbe594377420ebaa3a69b6fbfa373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":106},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df278e7ea3e94690b06ec25bd52c7c58",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":210},
            "size":{
              "width":322,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/日程/u6_line.png"}},
{
          "id":"241f74d4139c40798d0e0b49acc1bba5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":115},
            "size":{
              "width":320,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92ee519f11a54867bb44272b0280c301",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":115},
                "size":{
                  "width":320,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 日程编辑页",
                      "target":{
                        "targetType":"page",
                        "url":"日程编辑页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/日程/u7.png"}},
{
          "id":"87243394703a45a482876c050be7588e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":194,
              "y":156},
            "size":{
              "width":320,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e07cf2b4b464009b2e85e502c7527c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":194,
                  "y":156},
                "size":{
                  "width":320,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u7.png"}},
{
          "id":"ef368364355341a589f081a6c4228e4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":127},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4389dc85a1db48d598632c1f65dfb770",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":127},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"64100268635a4071bc64080c2c5d9c5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":495,
              "y":127},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c15dc7904a8a4332bab80c7c30af1e0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":495,
                  "y":127},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"7b6fbda40cd8489394118a0418070a07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":472,
              "y":168},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94de50f612234d2badc8ea7336f6678a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":472,
                  "y":168},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"c13398db537344cd8b7b7d5fadcb5815",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":94},
            "size":{
              "width":320,
              "height":10},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/日程/u17_line.png"}},
{
          "id":"44e9023c14e348f8bbd8df82e28533ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":358,
              "y":90},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccbf2b084b644a8a9ed53503f75c071e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":358,
                  "y":90},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u18.png"}},
{
          "id":"ceb9128bdbe14cf79804ceea635c8d25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":358,
              "y":209},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e845ffc98984b8f98c52839dbf79896",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":358,
                  "y":209},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u18.png"}},
{
          "id":"556cffd89d82440dba8f6f494165aba0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":235},
            "size":{
              "width":320,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1118e346b12342f28e927ebe6bed86be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":235},
                "size":{
                  "width":320,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u7.png"}},
{
          "id":"b35ca67ce5c0463dbf3bfbb2da852bc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":276},
            "size":{
              "width":320,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ee1af9c0d984323ae8acb72c550fb1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":276},
                "size":{
                  "width":320,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u7.png"}},
{
          "id":"3b5b413371a04fce9bba7acdc04a4792",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":247},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb0faa909e9947d08d93aee13d735a3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":514,
                  "y":247},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"bd537973a99d4c68a141a84131730a7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":247},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2dc95b80b6647e6869e141987bb8ae5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":497,
                  "y":247},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"6ba3505233d643afabd9839c193ecd89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":286},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb9a8442e3f5429298762ce859a13e70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":514,
                  "y":286},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"e16d2262bdb54031be4d2e66fc905146",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":317},
            "size":{
              "width":320,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8096199e85a740d698f1c858ff6bf89b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":317},
                "size":{
                  "width":320,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u7.png"}},
{
          "id":"61ed7673177b421fbf1812da7035f72f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":358},
            "size":{
              "width":320,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ac831a02f43491b992f2ec537222b78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":358},
                "size":{
                  "width":320,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u7.png"}},
{
          "id":"aad7a67d4cae49df95fbff079fdc9c9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":329},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1095b9b3508e438ea16e450d314d2ad6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":329},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"0a6380d508404ebcb6d9531b91f7fa97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":495,
              "y":329},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8442f2ab173e4728820a47368a4e6345",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":495,
                  "y":329},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"9e1de39b033e41a3824960d16049cb5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":368},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b18a89c4cc1f4a4b801a1f0cd17aa3d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":368},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"e6bde289913a4400b1c9de6394455035",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":286},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e65eb6dc8ec74340b38f23dd14c0ee3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":496,
                  "y":286},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"84608fdd3dfc437ba4a7388a8fe4ff2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":478,
              "y":247},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"704c92c3c3124eee9bff1bab2932d0ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":478,
                  "y":247},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"b7a5b9db1f624506a65d4020b3d0171d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":508,
              "y":156},
            "size":{
              "width":43,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd525f5729e94877840bc0013855d3c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "location":{
                  "x":508,
                  "y":156},
                "size":{
                  "width":43,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u46.png"}},
{
          "id":"74067c76b6a140ef81405802f0f18a99",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":167},
            "size":{
              "width":60,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c3f33888fb34f6b9655e445382b100e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":167},
                "size":{
                  "width":60,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u48.png"}},
{
          "id":"b76e0815acc7403bb2109565426540d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":538,
              "y":132},
            "size":{
              "width":5,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34177d2f216a4e8ea380f5fb781ee647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":538,
                  "y":132},
                "size":{
                  "width":5,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u50.png"}},
{
          "id":"78a5f749425c4d258390dacaeecb408a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":496,
              "y":172},
            "size":{
              "width":6,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d40b5bd39f5f40afba4256328bd5c30e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":496,
                  "y":172},
                "size":{
                  "width":6,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u52.png"}},
{
          "id":"52d0f21baff545bb92e3635ac55cde04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":538,
              "y":250},
            "size":{
              "width":5,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a9fd5b16e4f412885bc4055ddbc4565",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":538,
                  "y":250},
                "size":{
                  "width":5,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u50.png"}},
{
          "id":"d10a957f776f44b8a5a2fb0b431e3146",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":538,
              "y":290},
            "size":{
              "width":5,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bca5903cb4f841669a3af904eec89122",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":538,
                  "y":290},
                "size":{
                  "width":5,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u50.png"}},
{
          "id":"a3c546888b1c40ee8992d323a2d0b353",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":538,
              "y":333},
            "size":{
              "width":5,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc7d48d3eaa64a9ca31376c25d2e5fba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":538,
                  "y":333},
                "size":{
                  "width":5,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u50.png"}},
{
          "id":"fd85fb147a5c4a66b7deb63aafb36124",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":538,
              "y":373},
            "size":{
              "width":5,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ac9619a5e0d4335911772700b3384ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":538,
                  "y":373},
                "size":{
                  "width":5,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u50.png"}},
{
          "id":"6744292ddf6943b29b80f7b1b4573230",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":30}},
          "adaptiveStyles":{
},
          "masterId":"f6b2d51cbd59488987ab163e210c4e6c"},
{
          "id":"e0b25e6e70d543e18bdc2e291721b426",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":447,
              "y":249},
            "size":{
              "width":26,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffac3f5d153644d0b0c8db2b3462c425",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":447,
                  "y":249},
                "size":{
                  "width":26,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01d5face22b54faa8d7c011ecaa63b00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":459,
              "y":289},
            "size":{
              "width":33,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d0c637a3fa14e11b3b0db8dfaffb042",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":459,
                  "y":289},
                "size":{
                  "width":33,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a20bb5df6934ae49d0e672989554a27",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":459,
              "y":332},
            "size":{
              "width":33,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5834b39aa93c47ae8f991fec0209a89c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":459,
                  "y":332},
                "size":{
                  "width":33,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91dbef326fbb4fe1b77821d2718510bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":465,
              "y":128},
            "size":{
              "width":26,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f771f91371d44b08ac7d7b2c1f15f46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":465,
                  "y":128},
                "size":{
                  "width":26,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2a005c48947409a91d93f677476059e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":434,
              "y":169},
            "size":{
              "width":33,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aae5fc5684b94d33b886375e4354ab79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":434,
                  "y":169},
                "size":{
                  "width":33,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2b70eca2167435b853a33dd7a7d0aa4",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":230,
              "y":79},
            "size":{
              "width":320,
              "height":120},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"dc4a98dd7a324cf38370c6950169e2be",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7191cfc5f2d94628b38a9bb2414d9514",
                  "label":"",
                  "parentDynamicPanel":"b2b70eca2167435b853a33dd7a7d0aa4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "size":{
                      "width":320,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e560a9683e7d4eafb3a87938355ac738",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b2b70eca2167435b853a33dd7a7d0aa4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "size":{
                          "width":320,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 日程",
                              "target":{
                                "targetType":"page",
                                "url":"日程.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/日程/u108.png"}},
{
                  "id":"c64661c86ad4480e85bdbc1373df4e57",
                  "label":"",
                  "parentDynamicPanel":"b2b70eca2167435b853a33dd7a7d0aa4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":320,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ac2ed54abd2740eb8ce64331524fe3a0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b2b70eca2167435b853a33dd7a7d0aa4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "location":{
                          "x":0,
                          "y":40},
                        "size":{
                          "width":320,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 日程-通知",
                              "target":{
                                "targetType":"page",
                                "url":"日程-通知.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/日程/u108.png"}},
{
                  "id":"7c51860b40134448978f0959ab7e1875",
                  "label":"",
                  "parentDynamicPanel":"b2b70eca2167435b853a33dd7a7d0aa4",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":287,
                      "y":10.5},
                    "size":{
                      "width":23,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f3928355876f4087ac4400f48a776267",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b2b70eca2167435b853a33dd7a7d0aa4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":287,
                          "y":10.5},
                        "size":{
                          "width":23,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/日程/u112.png"}}]}]},
{
          "id":"cfb69f4bcf824e0b95971695d3847262",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":376,
              "y":47},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd36858040fc4bc88a2e5e0bae84f004",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":376,
                  "y":47},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c462be48c3b4482091f1560f9359be89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":405,
              "y":50},
            "size":{
              "width":18,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42d032e3d674448e83dac7c6f81e43ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":405,
                  "y":50},
                "size":{
                  "width":18,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u116.png"}},
{
          "id":"df697cce50de481aa66af2290d36477f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":42},
            "size":{
              "width":68,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e7cf8bab90e40bba730378a19de368f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":358,
                  "y":42},
                "size":{
                  "width":68,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (动态面板)",
                      "objectsToFades":[{
                          "objectPath":["b2b70eca2167435b853a33dd7a7d0aa4"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/日程/u118.png"}},
{
          "id":"8f7af22138fd4d84a024bcc5e194596c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":516,
              "y":42},
            "size":{
              "width":22,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b46133669da45bf9f2a1325a41f7fa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":516,
                  "y":42},
                "size":{
                  "width":22,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 日程编辑页",
                      "target":{
                        "targetType":"page",
                        "url":"日程编辑页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/日程/u120.png"}}]}},
  "masters":{
    "f6b2d51cbd59488987ab163e210c4e6c":{
      "packageId":"f6b2d51cbd59488987ab163e210c4e6c",
      "type":"Axure:Master",
      "name":"列表",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"dae76d0dfcf54aca9e40bb161edb6a41",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":178,
                "y":14},
              "size":{
                "width":29,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"95feba4a48624ff89029c81df6ab7c57",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":178,
                    "y":14},
                  "size":{
                    "width":29,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u63.png"}},
{
            "id":"758dd316b6df4c56b83285fbc7f7a258",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"33px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "location":{
                "x":1,
                "y":0},
              "size":{
                "width":170,
                "height":91}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe36c7cde2a44338987cc4c491eeeed6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"33px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "location":{
                    "x":1,
                    "y":0},
                  "size":{
                    "width":170,
                    "height":91}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u65.png"}},
{
            "id":"0299043647d24119a9bca14500f004e6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":107},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"338b0f5ea7fc4e8d97e30348f8fb2051",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":107},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u52.png"}},
{
            "id":"ae1a6dea114c4545a42b48138af75d6a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":135},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"201649212c084e68a84cd004442c1225",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":135},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 全部客户",
                        "target":{
                          "targetType":"page",
                          "url":"全部客户.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/日程/u69.png"}},
{
            "id":"03bc4eae5b1d45ed9104bb33ba87821b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":153,
                "y":152},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d5f4ba8dc7234dffa63daf3e1f7ae6a6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":153,
                    "y":152},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u71.png"}},
{
            "id":"997015b6a72342009171d9a893106262",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":151},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e7167221aa864a03b6e64dcfebdbc846",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":151},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u52.png"}},
{
            "id":"bdcac488db754e66812e3825d9959dc8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":180},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"186c2a1e4f524656a85e85b9eb49b494",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":180},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u69.png"}},
{
            "id":"f426564ac00946f8ac1ec33f872f413d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":153,
                "y":197},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"09dd8257b5ea4de5bfa9021576d29a9a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":153,
                    "y":197},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u71.png"}},
{
            "id":"67115d8110874886a628a5985eb66e5f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":196},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3660cf58811c40dab652fd6ce89472fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":196},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u52.png"}},
{
            "id":"98bf1deced44427aabd6f05d891dd57a",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":174},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u81_line.png"}},
{
            "id":"6dea99e2ddd04eaabc3aed7310cba1a1",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":130},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u81_line.png"}},
{
            "id":"d522c292a80c41bda0fe53184dc3ddec",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":225},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"41605b20f86a45f492009f0159f00c1a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":225},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u69.png"}},
{
            "id":"f8ce832044244c85800be57fd1bd7aae",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":153,
                "y":242},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7987ebc9e10e4288a3fc81e743b679c0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":153,
                    "y":242},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u71.png"}},
{
            "id":"9464b2fd4b694506a18075b564875180",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":241},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"71be189bc6f24a678c5827fb56c6a4d4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":241},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u52.png"}},
{
            "id":"64b138e1370a462093888f4a1e4c20f6",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":219},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u81_line.png"}},
{
            "id":"2ddbffad457041a89049b993402ca4fb",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":270},
              "size":{
                "width":170,
                "height":266}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8fc057e52ca348a9bf8daae017a39ae3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":270},
                  "size":{
                    "width":170,
                    "height":266}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u90.png"}},
{
            "id":"5c912b3120934e429477c55b9d6ac5dd",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":264},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u81_line.png"}},
{
            "id":"bc8ab89ff012487ab1aa2427f191d1a9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":1,
                "y":90},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"941b986d92554280b7262587679c90d6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":1,
                    "y":90},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 日程",
                        "target":{
                          "targetType":"page",
                          "url":"日程.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/日程/u93.png"}},
{
            "id":"90af0bce6c2e45b9842496222f7c13da",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":154,
                "y":108},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3e63693131c547e3af907128c0fd1bd4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":154,
                    "y":108},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u52.png"}}]}}},
  "objectPaths":{
    "91f939e3eff646d58de889eef25ba9a5":{
      "scriptId":"u0"},
    "03e1c94465c4421999db2e871e774cae":{
      "scriptId":"u1"},
    "3b37b3b9711240e4911a8a3ae0ad1936":{
      "scriptId":"u2"},
    "0c0e976cd98641f38dca7cd9bc7f7c4d":{
      "scriptId":"u3"},
    "e29c07640c654a0382edf213d82c2673":{
      "scriptId":"u4"},
    "26fcbe594377420ebaa3a69b6fbfa373":{
      "scriptId":"u5"},
    "df278e7ea3e94690b06ec25bd52c7c58":{
      "scriptId":"u6"},
    "241f74d4139c40798d0e0b49acc1bba5":{
      "scriptId":"u7"},
    "92ee519f11a54867bb44272b0280c301":{
      "scriptId":"u8"},
    "87243394703a45a482876c050be7588e":{
      "scriptId":"u9"},
    "6e07cf2b4b464009b2e85e502c7527c5":{
      "scriptId":"u10"},
    "ef368364355341a589f081a6c4228e4c":{
      "scriptId":"u11"},
    "4389dc85a1db48d598632c1f65dfb770":{
      "scriptId":"u12"},
    "64100268635a4071bc64080c2c5d9c5d":{
      "scriptId":"u13"},
    "c15dc7904a8a4332bab80c7c30af1e0d":{
      "scriptId":"u14"},
    "7b6fbda40cd8489394118a0418070a07":{
      "scriptId":"u15"},
    "94de50f612234d2badc8ea7336f6678a":{
      "scriptId":"u16"},
    "c13398db537344cd8b7b7d5fadcb5815":{
      "scriptId":"u17"},
    "44e9023c14e348f8bbd8df82e28533ac":{
      "scriptId":"u18"},
    "ccbf2b084b644a8a9ed53503f75c071e":{
      "scriptId":"u19"},
    "ceb9128bdbe14cf79804ceea635c8d25":{
      "scriptId":"u20"},
    "1e845ffc98984b8f98c52839dbf79896":{
      "scriptId":"u21"},
    "556cffd89d82440dba8f6f494165aba0":{
      "scriptId":"u22"},
    "1118e346b12342f28e927ebe6bed86be":{
      "scriptId":"u23"},
    "b35ca67ce5c0463dbf3bfbb2da852bc7":{
      "scriptId":"u24"},
    "0ee1af9c0d984323ae8acb72c550fb1f":{
      "scriptId":"u25"},
    "3b5b413371a04fce9bba7acdc04a4792":{
      "scriptId":"u26"},
    "eb0faa909e9947d08d93aee13d735a3e":{
      "scriptId":"u27"},
    "bd537973a99d4c68a141a84131730a7f":{
      "scriptId":"u28"},
    "e2dc95b80b6647e6869e141987bb8ae5":{
      "scriptId":"u29"},
    "6ba3505233d643afabd9839c193ecd89":{
      "scriptId":"u30"},
    "cb9a8442e3f5429298762ce859a13e70":{
      "scriptId":"u31"},
    "e16d2262bdb54031be4d2e66fc905146":{
      "scriptId":"u32"},
    "8096199e85a740d698f1c858ff6bf89b":{
      "scriptId":"u33"},
    "61ed7673177b421fbf1812da7035f72f":{
      "scriptId":"u34"},
    "5ac831a02f43491b992f2ec537222b78":{
      "scriptId":"u35"},
    "aad7a67d4cae49df95fbff079fdc9c9e":{
      "scriptId":"u36"},
    "1095b9b3508e438ea16e450d314d2ad6":{
      "scriptId":"u37"},
    "0a6380d508404ebcb6d9531b91f7fa97":{
      "scriptId":"u38"},
    "8442f2ab173e4728820a47368a4e6345":{
      "scriptId":"u39"},
    "9e1de39b033e41a3824960d16049cb5f":{
      "scriptId":"u40"},
    "b18a89c4cc1f4a4b801a1f0cd17aa3d2":{
      "scriptId":"u41"},
    "e6bde289913a4400b1c9de6394455035":{
      "scriptId":"u42"},
    "e65eb6dc8ec74340b38f23dd14c0ee3d":{
      "scriptId":"u43"},
    "84608fdd3dfc437ba4a7388a8fe4ff2a":{
      "scriptId":"u44"},
    "704c92c3c3124eee9bff1bab2932d0ec":{
      "scriptId":"u45"},
    "b7a5b9db1f624506a65d4020b3d0171d":{
      "scriptId":"u46"},
    "cd525f5729e94877840bc0013855d3c8":{
      "scriptId":"u47"},
    "74067c76b6a140ef81405802f0f18a99":{
      "scriptId":"u48"},
    "6c3f33888fb34f6b9655e445382b100e":{
      "scriptId":"u49"},
    "b76e0815acc7403bb2109565426540d8":{
      "scriptId":"u50"},
    "34177d2f216a4e8ea380f5fb781ee647":{
      "scriptId":"u51"},
    "78a5f749425c4d258390dacaeecb408a":{
      "scriptId":"u52"},
    "d40b5bd39f5f40afba4256328bd5c30e":{
      "scriptId":"u53"},
    "52d0f21baff545bb92e3635ac55cde04":{
      "scriptId":"u54"},
    "4a9fd5b16e4f412885bc4055ddbc4565":{
      "scriptId":"u55"},
    "d10a957f776f44b8a5a2fb0b431e3146":{
      "scriptId":"u56"},
    "bca5903cb4f841669a3af904eec89122":{
      "scriptId":"u57"},
    "a3c546888b1c40ee8992d323a2d0b353":{
      "scriptId":"u58"},
    "cc7d48d3eaa64a9ca31376c25d2e5fba":{
      "scriptId":"u59"},
    "fd85fb147a5c4a66b7deb63aafb36124":{
      "scriptId":"u60"},
    "2ac9619a5e0d4335911772700b3384ad":{
      "scriptId":"u61"},
    "6744292ddf6943b29b80f7b1b4573230":{
      "scriptId":"u62",
      "dae76d0dfcf54aca9e40bb161edb6a41":{
        "scriptId":"u63"},
      "95feba4a48624ff89029c81df6ab7c57":{
        "scriptId":"u64"},
      "758dd316b6df4c56b83285fbc7f7a258":{
        "scriptId":"u65"},
      "fe36c7cde2a44338987cc4c491eeeed6":{
        "scriptId":"u66"},
      "0299043647d24119a9bca14500f004e6":{
        "scriptId":"u67"},
      "338b0f5ea7fc4e8d97e30348f8fb2051":{
        "scriptId":"u68"},
      "ae1a6dea114c4545a42b48138af75d6a":{
        "scriptId":"u69"},
      "201649212c084e68a84cd004442c1225":{
        "scriptId":"u70"},
      "03bc4eae5b1d45ed9104bb33ba87821b":{
        "scriptId":"u71"},
      "d5f4ba8dc7234dffa63daf3e1f7ae6a6":{
        "scriptId":"u72"},
      "997015b6a72342009171d9a893106262":{
        "scriptId":"u73"},
      "e7167221aa864a03b6e64dcfebdbc846":{
        "scriptId":"u74"},
      "bdcac488db754e66812e3825d9959dc8":{
        "scriptId":"u75"},
      "186c2a1e4f524656a85e85b9eb49b494":{
        "scriptId":"u76"},
      "f426564ac00946f8ac1ec33f872f413d":{
        "scriptId":"u77"},
      "09dd8257b5ea4de5bfa9021576d29a9a":{
        "scriptId":"u78"},
      "67115d8110874886a628a5985eb66e5f":{
        "scriptId":"u79"},
      "3660cf58811c40dab652fd6ce89472fb":{
        "scriptId":"u80"},
      "98bf1deced44427aabd6f05d891dd57a":{
        "scriptId":"u81"},
      "6dea99e2ddd04eaabc3aed7310cba1a1":{
        "scriptId":"u82"},
      "d522c292a80c41bda0fe53184dc3ddec":{
        "scriptId":"u83"},
      "41605b20f86a45f492009f0159f00c1a":{
        "scriptId":"u84"},
      "f8ce832044244c85800be57fd1bd7aae":{
        "scriptId":"u85"},
      "7987ebc9e10e4288a3fc81e743b679c0":{
        "scriptId":"u86"},
      "9464b2fd4b694506a18075b564875180":{
        "scriptId":"u87"},
      "71be189bc6f24a678c5827fb56c6a4d4":{
        "scriptId":"u88"},
      "64b138e1370a462093888f4a1e4c20f6":{
        "scriptId":"u89"},
      "2ddbffad457041a89049b993402ca4fb":{
        "scriptId":"u90"},
      "8fc057e52ca348a9bf8daae017a39ae3":{
        "scriptId":"u91"},
      "5c912b3120934e429477c55b9d6ac5dd":{
        "scriptId":"u92"},
      "bc8ab89ff012487ab1aa2427f191d1a9":{
        "scriptId":"u93"},
      "941b986d92554280b7262587679c90d6":{
        "scriptId":"u94"},
      "90af0bce6c2e45b9842496222f7c13da":{
        "scriptId":"u95"},
      "3e63693131c547e3af907128c0fd1bd4":{
        "scriptId":"u96"}},
    "e0b25e6e70d543e18bdc2e291721b426":{
      "scriptId":"u97"},
    "ffac3f5d153644d0b0c8db2b3462c425":{
      "scriptId":"u98"},
    "01d5face22b54faa8d7c011ecaa63b00":{
      "scriptId":"u99"},
    "1d0c637a3fa14e11b3b0db8dfaffb042":{
      "scriptId":"u100"},
    "2a20bb5df6934ae49d0e672989554a27":{
      "scriptId":"u101"},
    "5834b39aa93c47ae8f991fec0209a89c":{
      "scriptId":"u102"},
    "91dbef326fbb4fe1b77821d2718510bb":{
      "scriptId":"u103"},
    "8f771f91371d44b08ac7d7b2c1f15f46":{
      "scriptId":"u104"},
    "c2a005c48947409a91d93f677476059e":{
      "scriptId":"u105"},
    "aae5fc5684b94d33b886375e4354ab79":{
      "scriptId":"u106"},
    "b2b70eca2167435b853a33dd7a7d0aa4":{
      "scriptId":"u107"},
    "7191cfc5f2d94628b38a9bb2414d9514":{
      "scriptId":"u108"},
    "e560a9683e7d4eafb3a87938355ac738":{
      "scriptId":"u109"},
    "c64661c86ad4480e85bdbc1373df4e57":{
      "scriptId":"u110"},
    "ac2ed54abd2740eb8ce64331524fe3a0":{
      "scriptId":"u111"},
    "7c51860b40134448978f0959ab7e1875":{
      "scriptId":"u112"},
    "f3928355876f4087ac4400f48a776267":{
      "scriptId":"u113"},
    "cfb69f4bcf824e0b95971695d3847262":{
      "scriptId":"u114"},
    "dd36858040fc4bc88a2e5e0bae84f004":{
      "scriptId":"u115"},
    "c462be48c3b4482091f1560f9359be89":{
      "scriptId":"u116"},
    "42d032e3d674448e83dac7c6f81e43ad":{
      "scriptId":"u117"},
    "df697cce50de481aa66af2290d36477f":{
      "scriptId":"u118"},
    "8e7cf8bab90e40bba730378a19de368f":{
      "scriptId":"u119"},
    "8f7af22138fd4d84a024bcc5e194596c":{
      "scriptId":"u120"},
    "6b46133669da45bf9f2a1325a41f7fa2":{
      "scriptId":"u121"}}});