$axure.loadCurrentPage({
  "url":"聊天列表.html",
  "generationDate":new Date(1413514451491.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5c9df59c341e416294806f7e40707102",
    "type":"Axure:Page",
    "name":"聊天列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dd9a02480b8b4fe48197880365d6d6c5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":10},
            "size":{
              "width":794,
              "height":1487}},
          "adaptiveStyles":{
},
          "masterId":"984fa132bdee4430802a486dd3e5c298"},
{
          "id":"f2e9ca8eaae545719c63bab44fdff94b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"33px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF8F8F8},
            "location":{
              "x":181,
              "y":317},
            "size":{
              "width":639,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7327ccdc453144f8b9cbc0d21155d61d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"33px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF8F8F8},
                "location":{
                  "x":181,
                  "y":317},
                "size":{
                  "width":639,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u20.png"}},
{
          "id":"0dcde9b18f8a4071bd3589e35656fb26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"bold",
            "location":{
              "x":201,
              "y":341},
            "size":{
              "width":38,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"992e0c0d9cb54d4a8cb46a2367f825c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"bold",
                "location":{
                  "x":201,
                  "y":341},
                "size":{
                  "width":38,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/装修流程/u32.png"}},
{
          "id":"028662f769324396bfdc2071381b5117",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":181,
              "y":403},
            "size":{
              "width":639,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3b6ddf579aa4f32b00dbc6b4f547fd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":181,
                  "y":403},
                "size":{
                  "width":639,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天",
                      "target":{
                        "targetType":"page",
                        "url":"聊天.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82fe33def53742408da0e2723c55ff12",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":241,
              "y":541},
            "size":{
              "width":86,
              "height":86},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"992bf8ee858f4e179812efd341a5b631",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":241,
                  "y":541},
                "size":{
                  "width":86,
                  "height":86},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u52.png"}},
{
          "id":"69f54752daf04528b32d436f971a48fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":241,
              "y":420},
            "size":{
              "width":86,
              "height":86},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaded439f4cf4cabbba89513580efca3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":241,
                  "y":420},
                "size":{
                  "width":86,
                  "height":86},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u48.png"}},
{
          "id":"2dd5dc4746c34285bca980801c1a2f6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":181,
              "y":523},
            "size":{
              "width":639,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a17ff52daf264cb087b4aebd00215528",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":181,
                  "y":523},
                "size":{
                  "width":639,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ac4d5d082b94574be6be47ce3675e01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":181,
              "y":763},
            "size":{
              "width":639,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7353dab2c3f41f88021e6058b0571b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":181,
                  "y":763},
                "size":{
                  "width":639,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08bc320d1f5d425187957190a8901250",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":181,
              "y":883},
            "size":{
              "width":639,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7ab876a69854637bb25fb068523985e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":181,
                  "y":883},
                "size":{
                  "width":639,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d2445df40e1406f9caeafe5c63871ef",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":518},
            "size":{
              "width":639,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/聊天列表/u37_line.png"}},
{
          "id":"61bd41d085e44f86a04d20be896a4058",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":638},
            "size":{
              "width":639,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/聊天列表/u37_line.png"}},
{
          "id":"2670d80b0edb435e9f90b82688ac19d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "location":{
              "x":352,
              "y":432},
            "size":{
              "width":150,
              "height":28},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e02cd3197eb445e693d36cd2fcb8a40d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "location":{
                  "x":352,
                  "y":432},
                "size":{
                  "width":150,
                  "height":28},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0822e1b09a0546469436d9b3465956c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "location":{
              "x":352,
              "y":554},
            "size":{
              "width":150,
              "height":28},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a268e56ea76943fa8595b3c15a7470a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "location":{
                  "x":352,
                  "y":554},
                "size":{
                  "width":150,
                  "height":28},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4758d64f6c3a436e8254db9aedbd9517",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":352,
              "y":475},
            "size":{
              "width":292,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91afc9d4abc144fb8110662dad187b35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":352,
                  "y":475},
                "size":{
                  "width":292,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8699ff6e989a47569124130901e30357",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":352,
              "y":596},
            "size":{
              "width":292,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dbc8afc49d7452a8f7095d932cddff7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":352,
                  "y":596},
                "size":{
                  "width":292,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2d4fc5624ba4c86a210822ac5938aae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":739,
              "y":420},
            "size":{
              "width":65,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6581590a11924d5d9383f1ff797d2f3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":739,
                  "y":420},
                "size":{
                  "width":65,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f104f57fcaba4889b3986690a5755efd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":740,
              "y":541},
            "size":{
              "width":65,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9fa2028772549da93bcc9aedeabf3f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":740,
                  "y":541},
                "size":{
                  "width":65,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "984fa132bdee4430802a486dd3e5c298":{
      "packageId":"984fa132bdee4430802a486dd3e5c298",
      "type":"Axure:Master",
      "name":"shoujixin",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0924992c31c149048016d672e5c7f726",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":794,
                "height":1487},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18279859f5f846ce8c3645a511e3061b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":794,
                    "height":1487},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u0.jpg"}},
{
            "id":"70f92109e52a40af94df453ebb3e8fd2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":307},
              "size":{
                "width":640,
                "height":822},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1a0f733bad824f2595138b3ed7ed226f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":80,
                    "y":307},
                  "size":{
                    "width":640,
                    "height":822},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u2.png"}},
{
            "id":"afaeff7a64e54c80962de48a01e9fe2c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":1129},
              "size":{
                "width":640,
                "height":97},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"74df996240be4f2eae72b660a9d138d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":80,
                    "y":1129},
                  "size":{
                    "width":640,
                    "height":97},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u4.png"}},
{
            "id":"ad28bbac596b43b58a7b09fd8c61d066",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":368,
                "y":1139},
              "size":{
                "width":39,
                "height":36},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fd172ca0c7684ee3a771250caa2a4708",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":368,
                    "y":1139},
                  "size":{
                    "width":39,
                    "height":36},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u6.png"}},
{
            "id":"00913d450cdc4fcaa0b8e0987daf0158",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":580,
                "y":1141},
              "size":{
                "width":39,
                "height":33},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"23e12321df4e4b8e918b93a4238c0b2e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":580,
                    "y":1141},
                  "size":{
                    "width":39,
                    "height":33},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u8.png"}},
{
            "id":"6aff273e7ae443acaad54ef5d53ef650",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":175,
                "y":1143},
              "size":{
                "width":38,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"895a51871df84fdeb64de494f9ded835",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":175,
                    "y":1143},
                  "size":{
                    "width":38,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u10.png"}},
{
            "id":"f64805ae112045e2acbffd535c1532ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":327,
                "y":1134},
              "size":{
                "width":123,
                "height":92},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"46456e5bf1a64ccf8f309dbbddbdde36",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":327,
                    "y":1134},
                  "size":{
                    "width":123,
                    "height":92},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"153adc10da0545eb85d07f4f4553ba83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":539,
                "y":1134},
              "size":{
                "width":123,
                "height":92},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2071049e0e8d4b418468c9a8514ed7e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":539,
                    "y":1134},
                  "size":{
                    "width":123,
                    "height":92},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登陆页",
                        "target":{
                          "targetType":"page",
                          "url":"登陆页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bb67617ebb764a5ba40a60393669df03",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":132,
                "y":1129},
              "size":{
                "width":123,
                "height":92},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"35fcb7f3ba564c56a8900c8c914f3812",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":132,
                    "y":1129},
                  "size":{
                    "width":123,
                    "height":92},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 聊天",
                        "target":{
                          "targetType":"page",
                          "url":"聊天.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ca7ebea22b8a48e9a088034eb7d63cfb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFF0000},
              "location":{
                "x":223,
                "y":1139},
              "size":{
                "width":11,
                "height":11},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24509502b78240de82bb50d987c9e129",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF0000},
                  "location":{
                    "x":223,
                    "y":1139},
                  "size":{
                    "width":11,
                    "height":11},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/确定施工方式简介/u19.png"}}]}}},
  "objectPaths":{
    "dd9a02480b8b4fe48197880365d6d6c5":{
      "scriptId":"u0",
      "0924992c31c149048016d672e5c7f726":{
        "scriptId":"u1"},
      "18279859f5f846ce8c3645a511e3061b":{
        "scriptId":"u2"},
      "70f92109e52a40af94df453ebb3e8fd2":{
        "scriptId":"u3"},
      "1a0f733bad824f2595138b3ed7ed226f":{
        "scriptId":"u4"},
      "afaeff7a64e54c80962de48a01e9fe2c":{
        "scriptId":"u5"},
      "74df996240be4f2eae72b660a9d138d3":{
        "scriptId":"u6"},
      "ad28bbac596b43b58a7b09fd8c61d066":{
        "scriptId":"u7"},
      "fd172ca0c7684ee3a771250caa2a4708":{
        "scriptId":"u8"},
      "00913d450cdc4fcaa0b8e0987daf0158":{
        "scriptId":"u9"},
      "23e12321df4e4b8e918b93a4238c0b2e":{
        "scriptId":"u10"},
      "6aff273e7ae443acaad54ef5d53ef650":{
        "scriptId":"u11"},
      "895a51871df84fdeb64de494f9ded835":{
        "scriptId":"u12"},
      "f64805ae112045e2acbffd535c1532ea":{
        "scriptId":"u13"},
      "46456e5bf1a64ccf8f309dbbddbdde36":{
        "scriptId":"u14"},
      "153adc10da0545eb85d07f4f4553ba83":{
        "scriptId":"u15"},
      "2071049e0e8d4b418468c9a8514ed7e2":{
        "scriptId":"u16"},
      "bb67617ebb764a5ba40a60393669df03":{
        "scriptId":"u17"},
      "35fcb7f3ba564c56a8900c8c914f3812":{
        "scriptId":"u18"},
      "ca7ebea22b8a48e9a088034eb7d63cfb":{
        "scriptId":"u19"},
      "24509502b78240de82bb50d987c9e129":{
        "scriptId":"u20"}},
    "f2e9ca8eaae545719c63bab44fdff94b":{
      "scriptId":"u21"},
    "7327ccdc453144f8b9cbc0d21155d61d":{
      "scriptId":"u22"},
    "0dcde9b18f8a4071bd3589e35656fb26":{
      "scriptId":"u23"},
    "992e0c0d9cb54d4a8cb46a2367f825c0":{
      "scriptId":"u24"},
    "028662f769324396bfdc2071381b5117":{
      "scriptId":"u25"},
    "f3b6ddf579aa4f32b00dbc6b4f547fd1":{
      "scriptId":"u26"},
    "82fe33def53742408da0e2723c55ff12":{
      "scriptId":"u27"},
    "992bf8ee858f4e179812efd341a5b631":{
      "scriptId":"u28"},
    "69f54752daf04528b32d436f971a48fc":{
      "scriptId":"u29"},
    "aaded439f4cf4cabbba89513580efca3":{
      "scriptId":"u30"},
    "2dd5dc4746c34285bca980801c1a2f6b":{
      "scriptId":"u31"},
    "a17ff52daf264cb087b4aebd00215528":{
      "scriptId":"u32"},
    "2ac4d5d082b94574be6be47ce3675e01":{
      "scriptId":"u33"},
    "e7353dab2c3f41f88021e6058b0571b2":{
      "scriptId":"u34"},
    "08bc320d1f5d425187957190a8901250":{
      "scriptId":"u35"},
    "a7ab876a69854637bb25fb068523985e":{
      "scriptId":"u36"},
    "3d2445df40e1406f9caeafe5c63871ef":{
      "scriptId":"u37"},
    "61bd41d085e44f86a04d20be896a4058":{
      "scriptId":"u38"},
    "2670d80b0edb435e9f90b82688ac19d7":{
      "scriptId":"u39"},
    "e02cd3197eb445e693d36cd2fcb8a40d":{
      "scriptId":"u40"},
    "0822e1b09a0546469436d9b3465956c8":{
      "scriptId":"u41"},
    "a268e56ea76943fa8595b3c15a7470a4":{
      "scriptId":"u42"},
    "4758d64f6c3a436e8254db9aedbd9517":{
      "scriptId":"u43"},
    "91afc9d4abc144fb8110662dad187b35":{
      "scriptId":"u44"},
    "8699ff6e989a47569124130901e30357":{
      "scriptId":"u45"},
    "2dbc8afc49d7452a8f7095d932cddff7":{
      "scriptId":"u46"},
    "f2d4fc5624ba4c86a210822ac5938aae":{
      "scriptId":"u47"},
    "6581590a11924d5d9383f1ff797d2f3f":{
      "scriptId":"u48"},
    "f104f57fcaba4889b3986690a5755efd":{
      "scriptId":"u49"},
    "f9fa2028772549da93bcc9aedeabf3f0":{
      "scriptId":"u50"}}});