$axure.loadCurrentPage({
  "url":"日程-通知.html",
  "generationDate":new Date(1417677944788.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cbaec6cdb13b4542839f55f9b31c9d6b",
    "type":"Axure:Page",
    "name":"日程-通知",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3b554b586437494d83767717f9346bd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":29},
            "size":{
              "width":320,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3f731d5265841e2b84d5f8cbaa9c5cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":29},
                "size":{
                  "width":320,
                  "height":495}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u0.png"}},
{
          "id":"51180033920c4b3f99c6b5ef48a5b242",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":230,
              "y":29},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd5b2ea1aaac4d2a87ab66bc25ce5e39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":230,
                  "y":29},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u2.png"}},
{
          "id":"98c22352590c4fa18f6ebe831f1067f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":191},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6f7164f4e9b48febae1372e6bd3303b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":191},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce38ff898c804ef99a548be3ea560f64",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":203},
            "size":{
              "width":322,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/日程/u6_line.png"}},
{
          "id":"daa9689a756049e6ba66af3539f96e5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":151},
            "size":{
              "width":320,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f9e396d51af46abbb01d29e97b62038",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":151},
                "size":{
                  "width":320,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u7.png"}},
{
          "id":"f141a2fe2e084e57980f5fe9cd612dfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":163},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9637effa47834aa5bb71848e1e083a31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":508,
                  "y":163},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"e488d754fce44fc49e0e10033c0765f7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":90},
            "size":{
              "width":320,
              "height":10},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/日程/u17_line.png"}},
{
          "id":"3fd0750483d341aabb387bdf8b7c3fbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":358,
              "y":86},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67f609e63cd94e32baa7f2bdd913baca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":358,
                  "y":86},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u18.png"}},
{
          "id":"7842edcb85da437c98e4907c86fb0c70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":358,
              "y":202},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fe8a9e4bb674bc285dcbaf8a1c8e1b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":358,
                  "y":202},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u18.png"}},
{
          "id":"e9d3d281e2b54cb69ff2a21854931fe3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":228},
            "size":{
              "width":320,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b534e876ff824ea3b282cf6e8a7c5699",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":228},
                "size":{
                  "width":320,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u7.png"}},
{
          "id":"608b209bbf9b4645b13320abb96a9608",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":269},
            "size":{
              "width":320,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55986294ed664a978421b7c8a2049029",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":269},
                "size":{
                  "width":320,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u7.png"}},
{
          "id":"1538cf60c65449bba790fae7e88ac775",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":240},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b864d3fe384d4ba5abea9b495a0434e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":514,
                  "y":240},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"d587ff001b454e329de0272d11331938",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":240},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5b8add2dc9845acb65617277d1a0a39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":497,
                  "y":240},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"50b1417c3ded4683a2a9921cf2dd1825",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":279},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba6f7a3cb2aa4cea808657fbc6dce7aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":514,
                  "y":279},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"6819db06e1c5454397838deee0dfca32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":310},
            "size":{
              "width":320,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e30f005737d44817bbab2b3be0205a95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":310},
                "size":{
                  "width":320,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u7.png"}},
{
          "id":"09a97326a80247f59a4b69227fcdc5b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":322},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56d8cd511d384019bd6f6e5da43986c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":322},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"1579cab6c35344f18e92e02063c0d165",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":495,
              "y":322},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55b110cfed9e445497520cb0061fe916",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":495,
                  "y":322},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"e8555e01813a47c98cdc4a740016b0fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":279},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"715ffb0ab54d49f1aa483815b0811487",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":496,
                  "y":279},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"42d858adafa2499dbecd03aaa2be6424",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":478,
              "y":240},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c288fe5ca90d465aa51421053d5e250c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":478,
                  "y":240},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"aa8ac3a39fde441ebdc20fb53cde8835",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":534,
              "y":168},
            "size":{
              "width":6,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fad5b5fdf60f4a809bb1c368f57a0adf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":534,
                  "y":168},
                "size":{
                  "width":6,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u52.png"}},
{
          "id":"24e3b87f21544d6cbbbffb063fa9a41c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":538,
              "y":243},
            "size":{
              "width":5,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c33b786bd9a344e4a187e84737d97148",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":538,
                  "y":243},
                "size":{
                  "width":5,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u50.png"}},
{
          "id":"a51a58a20e0e4048829d9068c9b2ad1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":538,
              "y":283},
            "size":{
              "width":5,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"563845b8dc7b4d86ac8ac546caecad36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":538,
                  "y":283},
                "size":{
                  "width":5,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u50.png"}},
{
          "id":"db3b81a67b404052bb03b9643d42e9e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":538,
              "y":326},
            "size":{
              "width":5,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6591e1c52f364ab0a5258a1826441058",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":538,
                  "y":326},
                "size":{
                  "width":5,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u50.png"}},
{
          "id":"b4438ab5162f4668aa93728df5a40721",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":110},
            "size":{
              "width":320,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d1f3981d28e45d692c8c68dcf04faaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":110},
                "size":{
                  "width":320,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u7.png"}},
{
          "id":"f35da490cf0a4ce387fe220900aecf1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":122},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d84d66ddec944ce9ed2168b9d548f64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":122},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"97dbd7be4da445688d34b120641fdd1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":495,
              "y":122},
            "size":{
              "width":17,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6d9d5cb0e824a64a557557e5cdf76dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":495,
                  "y":122},
                "size":{
                  "width":17,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u11.png"}},
{
          "id":"a70420193efe46a1968d8257afc45463",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":538,
              "y":127},
            "size":{
              "width":5,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54153b447cb24f36b65571143859a25c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":538,
                  "y":127},
                "size":{
                  "width":5,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u50.png"}},
{
          "id":"15bfe9e4253645169ebda41bf7758ae2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":30}},
          "adaptiveStyles":{
},
          "masterId":"f6b2d51cbd59488987ab163e210c4e6c"},
{
          "id":"7af09691262a45af949ec64bb8e07072",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":376,
              "y":47},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07eb3d35c99241c988b4078ee36acf47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":376,
                  "y":47},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9e19612b67f43ccbd3966ad8936d205",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":405,
              "y":50},
            "size":{
              "width":18,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d8a5ed5fe734ac0917f39802b3c021f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":405,
                  "y":50},
                "size":{
                  "width":18,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u116.png"}},
{
          "id":"50da87cdc6a949259d4630d603544d4c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":41},
            "size":{
              "width":73,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9405fa2504b54ed4864df2c5f43188a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":41},
                "size":{
                  "width":73,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 通知",
                      "objectsToFades":[{
                          "objectPath":["0114e1a6c3a84ad787fe52184b217e8c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/日程-通知/u91.png"}},
{
          "id":"0114e1a6c3a84ad787fe52184b217e8c",
          "label":"通知",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":230,
              "y":80},
            "size":{
              "width":320,
              "height":120},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d4c9fcb581b54de0a5d087d13e36515b",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"50916cebc92f4bafa51c132f0bbf1a25",
                  "label":"",
                  "parentDynamicPanel":"0114e1a6c3a84ad787fe52184b217e8c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "size":{
                      "width":320,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"55f8758a3ce04853b19ddeda91b4b218",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0114e1a6c3a84ad787fe52184b217e8c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "size":{
                          "width":320,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 日程",
                              "target":{
                                "targetType":"page",
                                "url":"日程.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/日程/u108.png"}},
{
                  "id":"dac03a734bd3487aa3fa94e9507e08a1",
                  "label":"",
                  "parentDynamicPanel":"0114e1a6c3a84ad787fe52184b217e8c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":320,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"deca63670e864bd69e1ff2be027536f4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0114e1a6c3a84ad787fe52184b217e8c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "location":{
                          "x":0,
                          "y":40},
                        "size":{
                          "width":320,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 日程-通知",
                              "target":{
                                "targetType":"page",
                                "url":"日程-通知.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/日程/u108.png"}},
{
                  "id":"36d1787a978f43f488c72c74ee9ff188",
                  "label":"",
                  "parentDynamicPanel":"0114e1a6c3a84ad787fe52184b217e8c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":287,
                      "y":48},
                    "size":{
                      "width":23,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f33e6ef6c2d543cd9d9c03ea7829bb18",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0114e1a6c3a84ad787fe52184b217e8c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":287,
                          "y":48},
                        "size":{
                          "width":23,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/日程/u112.png"}}]}]},
{
          "id":"b85e60dd5ecc48e1b0dcd252a5e63782",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":29},
            "size":{
              "width":320,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dcd0dbefc684c7a89e9bade870bee25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":29},
                "size":{
                  "width":320,
                  "height":495}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u0.png"}},
{
          "id":"eb4070c56e704861a7bafd4c49e67bf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":580,
              "y":29},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31305d00523c4697a0321ec22d460464",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":580,
                  "y":29},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u2.png"}},
{
          "id":"0682b2cecbde44f895725c56b8f7de29",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":715,
              "y":41},
            "size":{
              "width":73,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09b2720cabd445d69bf72f11be92e71a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":715,
                  "y":41},
                "size":{
                  "width":73,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 通知",
                      "objectsToFades":[{
                          "objectPath":["0114e1a6c3a84ad787fe52184b217e8c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/日程-通知/u91.png"}},
{
          "id":"effbe9c5f40d416c97d30d4754fbf5c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":707,
              "y":267},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67b6d581f4fc4166825e78e7c0f63f20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":707,
                  "y":267},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "f6b2d51cbd59488987ab163e210c4e6c":{
      "packageId":"f6b2d51cbd59488987ab163e210c4e6c",
      "type":"Axure:Master",
      "name":"列表",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"dae76d0dfcf54aca9e40bb161edb6a41",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":178,
                "y":14},
              "size":{
                "width":29,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"95feba4a48624ff89029c81df6ab7c57",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":178,
                    "y":14},
                  "size":{
                    "width":29,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u63.png"}},
{
            "id":"758dd316b6df4c56b83285fbc7f7a258",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"33px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "location":{
                "x":1,
                "y":0},
              "size":{
                "width":170,
                "height":91}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe36c7cde2a44338987cc4c491eeeed6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"33px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "location":{
                    "x":1,
                    "y":0},
                  "size":{
                    "width":170,
                    "height":91}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u65.png"}},
{
            "id":"0299043647d24119a9bca14500f004e6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":107},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"338b0f5ea7fc4e8d97e30348f8fb2051",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":107},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u52.png"}},
{
            "id":"ae1a6dea114c4545a42b48138af75d6a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":135},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"201649212c084e68a84cd004442c1225",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":135},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 全部客户",
                        "target":{
                          "targetType":"page",
                          "url":"全部客户.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/日程/u69.png"}},
{
            "id":"03bc4eae5b1d45ed9104bb33ba87821b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":153,
                "y":152},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d5f4ba8dc7234dffa63daf3e1f7ae6a6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":153,
                    "y":152},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u71.png"}},
{
            "id":"997015b6a72342009171d9a893106262",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":151},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e7167221aa864a03b6e64dcfebdbc846",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":151},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u52.png"}},
{
            "id":"bdcac488db754e66812e3825d9959dc8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":180},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"186c2a1e4f524656a85e85b9eb49b494",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":180},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u69.png"}},
{
            "id":"f426564ac00946f8ac1ec33f872f413d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":153,
                "y":197},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"09dd8257b5ea4de5bfa9021576d29a9a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":153,
                    "y":197},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u71.png"}},
{
            "id":"67115d8110874886a628a5985eb66e5f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":196},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3660cf58811c40dab652fd6ce89472fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":196},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u52.png"}},
{
            "id":"98bf1deced44427aabd6f05d891dd57a",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":174},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u81_line.png"}},
{
            "id":"6dea99e2ddd04eaabc3aed7310cba1a1",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":130},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u81_line.png"}},
{
            "id":"d522c292a80c41bda0fe53184dc3ddec",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":225},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"41605b20f86a45f492009f0159f00c1a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":225},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u69.png"}},
{
            "id":"f8ce832044244c85800be57fd1bd7aae",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":153,
                "y":242},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7987ebc9e10e4288a3fc81e743b679c0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":153,
                    "y":242},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u71.png"}},
{
            "id":"9464b2fd4b694506a18075b564875180",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":241},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"71be189bc6f24a678c5827fb56c6a4d4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":241},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u52.png"}},
{
            "id":"64b138e1370a462093888f4a1e4c20f6",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":219},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u81_line.png"}},
{
            "id":"2ddbffad457041a89049b993402ca4fb",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":270},
              "size":{
                "width":170,
                "height":266}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8fc057e52ca348a9bf8daae017a39ae3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":270},
                  "size":{
                    "width":170,
                    "height":266}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u90.png"}},
{
            "id":"5c912b3120934e429477c55b9d6ac5dd",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":264},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u81_line.png"}},
{
            "id":"bc8ab89ff012487ab1aa2427f191d1a9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":1,
                "y":90},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"941b986d92554280b7262587679c90d6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":1,
                    "y":90},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 日程",
                        "target":{
                          "targetType":"page",
                          "url":"日程.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/日程/u93.png"}},
{
            "id":"90af0bce6c2e45b9842496222f7c13da",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":154,
                "y":108},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3e63693131c547e3af907128c0fd1bd4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":154,
                    "y":108},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u52.png"}}]}}},
  "objectPaths":{
    "3b554b586437494d83767717f9346bd3":{
      "scriptId":"u0"},
    "d3f731d5265841e2b84d5f8cbaa9c5cd":{
      "scriptId":"u1"},
    "51180033920c4b3f99c6b5ef48a5b242":{
      "scriptId":"u2"},
    "dd5b2ea1aaac4d2a87ab66bc25ce5e39":{
      "scriptId":"u3"},
    "98c22352590c4fa18f6ebe831f1067f2":{
      "scriptId":"u4"},
    "b6f7164f4e9b48febae1372e6bd3303b":{
      "scriptId":"u5"},
    "ce38ff898c804ef99a548be3ea560f64":{
      "scriptId":"u6"},
    "daa9689a756049e6ba66af3539f96e5f":{
      "scriptId":"u7"},
    "6f9e396d51af46abbb01d29e97b62038":{
      "scriptId":"u8"},
    "f141a2fe2e084e57980f5fe9cd612dfa":{
      "scriptId":"u9"},
    "9637effa47834aa5bb71848e1e083a31":{
      "scriptId":"u10"},
    "e488d754fce44fc49e0e10033c0765f7":{
      "scriptId":"u11"},
    "3fd0750483d341aabb387bdf8b7c3fbe":{
      "scriptId":"u12"},
    "67f609e63cd94e32baa7f2bdd913baca":{
      "scriptId":"u13"},
    "7842edcb85da437c98e4907c86fb0c70":{
      "scriptId":"u14"},
    "9fe8a9e4bb674bc285dcbaf8a1c8e1b2":{
      "scriptId":"u15"},
    "e9d3d281e2b54cb69ff2a21854931fe3":{
      "scriptId":"u16"},
    "b534e876ff824ea3b282cf6e8a7c5699":{
      "scriptId":"u17"},
    "608b209bbf9b4645b13320abb96a9608":{
      "scriptId":"u18"},
    "55986294ed664a978421b7c8a2049029":{
      "scriptId":"u19"},
    "1538cf60c65449bba790fae7e88ac775":{
      "scriptId":"u20"},
    "b864d3fe384d4ba5abea9b495a0434e9":{
      "scriptId":"u21"},
    "d587ff001b454e329de0272d11331938":{
      "scriptId":"u22"},
    "f5b8add2dc9845acb65617277d1a0a39":{
      "scriptId":"u23"},
    "50b1417c3ded4683a2a9921cf2dd1825":{
      "scriptId":"u24"},
    "ba6f7a3cb2aa4cea808657fbc6dce7aa":{
      "scriptId":"u25"},
    "6819db06e1c5454397838deee0dfca32":{
      "scriptId":"u26"},
    "e30f005737d44817bbab2b3be0205a95":{
      "scriptId":"u27"},
    "09a97326a80247f59a4b69227fcdc5b5":{
      "scriptId":"u28"},
    "56d8cd511d384019bd6f6e5da43986c0":{
      "scriptId":"u29"},
    "1579cab6c35344f18e92e02063c0d165":{
      "scriptId":"u30"},
    "55b110cfed9e445497520cb0061fe916":{
      "scriptId":"u31"},
    "e8555e01813a47c98cdc4a740016b0fa":{
      "scriptId":"u32"},
    "715ffb0ab54d49f1aa483815b0811487":{
      "scriptId":"u33"},
    "42d858adafa2499dbecd03aaa2be6424":{
      "scriptId":"u34"},
    "c288fe5ca90d465aa51421053d5e250c":{
      "scriptId":"u35"},
    "aa8ac3a39fde441ebdc20fb53cde8835":{
      "scriptId":"u36"},
    "fad5b5fdf60f4a809bb1c368f57a0adf":{
      "scriptId":"u37"},
    "24e3b87f21544d6cbbbffb063fa9a41c":{
      "scriptId":"u38"},
    "c33b786bd9a344e4a187e84737d97148":{
      "scriptId":"u39"},
    "a51a58a20e0e4048829d9068c9b2ad1e":{
      "scriptId":"u40"},
    "563845b8dc7b4d86ac8ac546caecad36":{
      "scriptId":"u41"},
    "db3b81a67b404052bb03b9643d42e9e1":{
      "scriptId":"u42"},
    "6591e1c52f364ab0a5258a1826441058":{
      "scriptId":"u43"},
    "b4438ab5162f4668aa93728df5a40721":{
      "scriptId":"u44"},
    "3d1f3981d28e45d692c8c68dcf04faaa":{
      "scriptId":"u45"},
    "f35da490cf0a4ce387fe220900aecf1f":{
      "scriptId":"u46"},
    "7d84d66ddec944ce9ed2168b9d548f64":{
      "scriptId":"u47"},
    "97dbd7be4da445688d34b120641fdd1c":{
      "scriptId":"u48"},
    "c6d9d5cb0e824a64a557557e5cdf76dc":{
      "scriptId":"u49"},
    "a70420193efe46a1968d8257afc45463":{
      "scriptId":"u50"},
    "54153b447cb24f36b65571143859a25c":{
      "scriptId":"u51"},
    "15bfe9e4253645169ebda41bf7758ae2":{
      "scriptId":"u52",
      "dae76d0dfcf54aca9e40bb161edb6a41":{
        "scriptId":"u53"},
      "95feba4a48624ff89029c81df6ab7c57":{
        "scriptId":"u54"},
      "758dd316b6df4c56b83285fbc7f7a258":{
        "scriptId":"u55"},
      "fe36c7cde2a44338987cc4c491eeeed6":{
        "scriptId":"u56"},
      "0299043647d24119a9bca14500f004e6":{
        "scriptId":"u57"},
      "338b0f5ea7fc4e8d97e30348f8fb2051":{
        "scriptId":"u58"},
      "ae1a6dea114c4545a42b48138af75d6a":{
        "scriptId":"u59"},
      "201649212c084e68a84cd004442c1225":{
        "scriptId":"u60"},
      "03bc4eae5b1d45ed9104bb33ba87821b":{
        "scriptId":"u61"},
      "d5f4ba8dc7234dffa63daf3e1f7ae6a6":{
        "scriptId":"u62"},
      "997015b6a72342009171d9a893106262":{
        "scriptId":"u63"},
      "e7167221aa864a03b6e64dcfebdbc846":{
        "scriptId":"u64"},
      "bdcac488db754e66812e3825d9959dc8":{
        "scriptId":"u65"},
      "186c2a1e4f524656a85e85b9eb49b494":{
        "scriptId":"u66"},
      "f426564ac00946f8ac1ec33f872f413d":{
        "scriptId":"u67"},
      "09dd8257b5ea4de5bfa9021576d29a9a":{
        "scriptId":"u68"},
      "67115d8110874886a628a5985eb66e5f":{
        "scriptId":"u69"},
      "3660cf58811c40dab652fd6ce89472fb":{
        "scriptId":"u70"},
      "98bf1deced44427aabd6f05d891dd57a":{
        "scriptId":"u71"},
      "6dea99e2ddd04eaabc3aed7310cba1a1":{
        "scriptId":"u72"},
      "d522c292a80c41bda0fe53184dc3ddec":{
        "scriptId":"u73"},
      "41605b20f86a45f492009f0159f00c1a":{
        "scriptId":"u74"},
      "f8ce832044244c85800be57fd1bd7aae":{
        "scriptId":"u75"},
      "7987ebc9e10e4288a3fc81e743b679c0":{
        "scriptId":"u76"},
      "9464b2fd4b694506a18075b564875180":{
        "scriptId":"u77"},
      "71be189bc6f24a678c5827fb56c6a4d4":{
        "scriptId":"u78"},
      "64b138e1370a462093888f4a1e4c20f6":{
        "scriptId":"u79"},
      "2ddbffad457041a89049b993402ca4fb":{
        "scriptId":"u80"},
      "8fc057e52ca348a9bf8daae017a39ae3":{
        "scriptId":"u81"},
      "5c912b3120934e429477c55b9d6ac5dd":{
        "scriptId":"u82"},
      "bc8ab89ff012487ab1aa2427f191d1a9":{
        "scriptId":"u83"},
      "941b986d92554280b7262587679c90d6":{
        "scriptId":"u84"},
      "90af0bce6c2e45b9842496222f7c13da":{
        "scriptId":"u85"},
      "3e63693131c547e3af907128c0fd1bd4":{
        "scriptId":"u86"}},
    "7af09691262a45af949ec64bb8e07072":{
      "scriptId":"u87"},
    "07eb3d35c99241c988b4078ee36acf47":{
      "scriptId":"u88"},
    "e9e19612b67f43ccbd3966ad8936d205":{
      "scriptId":"u89"},
    "3d8a5ed5fe734ac0917f39802b3c021f":{
      "scriptId":"u90"},
    "50da87cdc6a949259d4630d603544d4c":{
      "scriptId":"u91"},
    "9405fa2504b54ed4864df2c5f43188a3":{
      "scriptId":"u92"},
    "0114e1a6c3a84ad787fe52184b217e8c":{
      "scriptId":"u93"},
    "50916cebc92f4bafa51c132f0bbf1a25":{
      "scriptId":"u94"},
    "55f8758a3ce04853b19ddeda91b4b218":{
      "scriptId":"u95"},
    "dac03a734bd3487aa3fa94e9507e08a1":{
      "scriptId":"u96"},
    "deca63670e864bd69e1ff2be027536f4":{
      "scriptId":"u97"},
    "36d1787a978f43f488c72c74ee9ff188":{
      "scriptId":"u98"},
    "f33e6ef6c2d543cd9d9c03ea7829bb18":{
      "scriptId":"u99"},
    "b85e60dd5ecc48e1b0dcd252a5e63782":{
      "scriptId":"u100"},
    "7dcd0dbefc684c7a89e9bade870bee25":{
      "scriptId":"u101"},
    "eb4070c56e704861a7bafd4c49e67bf9":{
      "scriptId":"u102"},
    "31305d00523c4697a0321ec22d460464":{
      "scriptId":"u103"},
    "0682b2cecbde44f895725c56b8f7de29":{
      "scriptId":"u104"},
    "09b2720cabd445d69bf72f11be92e71a":{
      "scriptId":"u105"},
    "effbe9c5f40d416c97d30d4754fbf5c9":{
      "scriptId":"u106"},
    "67b6d581f4fc4166825e78e7c0f63f20":{
      "scriptId":"u107"}}});