$axure.loadCurrentPage({
  "url":"历史.html",
  "generationDate":new Date(1417146909918.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f8682f86d0f544a3b44c74c0a184be19",
    "type":"Axure:Page",
    "name":"历史",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"45c286d292c84448951fbd89a5aa83ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":45},
            "size":{
              "width":320,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38d48fc795b74f2691fca82dea93b0c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":45},
                "size":{
                  "width":320,
                  "height":495}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u0.png"}},
{
          "id":"9a2097bd278d46dc9ac8eba5ea9713a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":30,
              "y":20},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48209333595e419886d4c65f4f0e993e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":30,
                  "y":20},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u2.png"}},
{
          "id":"6bc11e2053924be2b829b5d60a35e97d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":38},
            "size":{
              "width":35,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5aee3c961ed40279d319bc628a95c05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":38},
                "size":{
                  "width":35,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全部客户",
                      "target":{
                        "targetType":"page",
                        "url":"全部客户.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f89bc28f2fd4cfcb7b607f2d8006b4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":69},
            "size":{
              "width":320,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a96a0b142ca14527942943496855b861",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":69},
                "size":{
                  "width":320,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u6.png"}},
{
          "id":"e62ec371797543f5bc1f93d648313d6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":114},
            "size":{
              "width":280,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d22bab30e8144639b3e8c024a5060ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":114},
                "size":{
                  "width":280,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u8.png"}},
{
          "id":"d758fe6946ba44d5996e57f091c7ac05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":159},
            "size":{
              "width":320,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5271d09e5c845fcbf4377c25eba35a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":159},
                "size":{
                  "width":320,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u6.png"}},
{
          "id":"8e1e989d0b244fe08ceaed84d628fd47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":204},
            "size":{
              "width":320,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5c03622c5da4326b3e0001fc65ab8fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":204},
                "size":{
                  "width":320,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u6.png"}},
{
          "id":"1c75fa2616814ae0b0e0a0a01841e4ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":249},
            "size":{
              "width":320,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5ac6315a0eb49febf8f4d808b58dd8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":249},
                "size":{
                  "width":320,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u6.png"}},
{
          "id":"4c52f31eaec14c72ad6dc07792981d05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":294},
            "size":{
              "width":320,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4ac786c804f47a5962f1947983fb661",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":294},
                "size":{
                  "width":320,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u6.png"}},
{
          "id":"c869ee4ddd6044a887bf2206a7d4bf6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":339},
            "size":{
              "width":320,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7a6a7a169f14fa68323694119f7a11a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":339},
                "size":{
                  "width":320,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u6.png"}},
{
          "id":"fe4f162bbd7f42f8b58e65e76d02f564",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":384},
            "size":{
              "width":320,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d936dd7fecd46df85b71d1d283086c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":384},
                "size":{
                  "width":320,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u6.png"}},
{
          "id":"283e33037802493cb6c7626ee6210390",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":429},
            "size":{
              "width":320,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf2fce67579a43319b44c8c2babc8095",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":429},
                "size":{
                  "width":320,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u6.png"}},
{
          "id":"5791fa1cd7ec4d8fb1d46688246492a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":474},
            "size":{
              "width":320,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20bb28d1450f45fe91849ff60c1dfa3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":474},
                "size":{
                  "width":320,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u6.png"}},
{
          "id":"ca77d32c17c14d188baa842cdc6fdb0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":310,
              "y":114},
            "size":{
              "width":40,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe74a70503af40bfb958c6f016c9c708",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "location":{
                  "x":310,
                  "y":114},
                "size":{
                  "width":40,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u26.png"}},
{
          "id":"e504bde314a641519a03ae4b49935275",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":68},
            "size":{
              "width":320,
              "height":472}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b073db29765421bbdcbc01a9391ac57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":68},
                "size":{
                  "width":320,
                  "height":472}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u28.png"}},
{
          "id":"42478b1a038b4d09972d82c87c89cd77",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":380,
              "y":69},
            "size":{
              "width":320,
              "height":450},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"807e7ca0fa334d58bf20de9745bdf80e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":380,
                  "y":69},
                "size":{
                  "width":320,
                  "height":450},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u30.png"}},
{
          "id":"43d4639f047e47f4b478e30a642ede86",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":380,
              "y":68},
            "size":{
              "width":320,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6cb68f975ae41b2bba220eacdaaf0cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":380,
                  "y":68},
                "size":{
                  "width":320,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u32.png"}},
{
          "id":"fbe1176324684e46ac4c4099d7444482",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":276,
              "y":82},
            "size":{
              "width":66,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef46fb6e334b4cad96dbfdbf0b4b8b9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":276,
                  "y":82},
                "size":{
                  "width":66,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u34.png"}},
{
          "id":"ac763dab567e4746b64d802a32eccb80",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":244,
              "y":128},
            "size":{
              "width":56,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffa552321aad45fc9cb9338fad649884",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":244,
                  "y":128},
                "size":{
                  "width":56,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u36.png"}},
{
          "id":"4de7980df1654a5992958d1976c2fb3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":277,
              "y":172},
            "size":{
              "width":66,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f66756354de0491db1936bc2ff5fc6e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":277,
                  "y":172},
                "size":{
                  "width":66,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u34.png"}},
{
          "id":"53e37ad4108d4e02b7bf1f0b24976257",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":380,
              "y":102},
            "size":{
              "width":320,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d947320a0a54666a32fc874e100e0b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":380,
                  "y":102},
                "size":{
                  "width":320,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u40.png"}},
{
          "id":"ff1e361a63754c53a7a70907e91e0594",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":380,
              "y":136},
            "size":{
              "width":320,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c152ac65376940ce943cbb2083aefe58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":380,
                  "y":136},
                "size":{
                  "width":320,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u40.png"}},
{
          "id":"435d500a8849494a9d383912a0a1b6a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":380,
              "y":171},
            "size":{
              "width":320,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a706e058ab8f4ff28d7d73aa3c0fc1c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":380,
                  "y":171},
                "size":{
                  "width":320,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史/u40.png"}},
{
          "id":"5cd6ce6867e049db96b4ebda17a2b58e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":380,
              "y":20},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77d4eb910e6541b384a4288698a2fc4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":380,
                  "y":20},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u2.png"}},
{
          "id":"0b954df777074e159dc429f6e8150cf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":397,
              "y":38},
            "size":{
              "width":35,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eac91ab7aedf41eeb2d7b12722a0bd13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":397,
                  "y":38},
                "size":{
                  "width":35,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "45c286d292c84448951fbd89a5aa83ce":{
      "scriptId":"u0"},
    "38d48fc795b74f2691fca82dea93b0c3":{
      "scriptId":"u1"},
    "9a2097bd278d46dc9ac8eba5ea9713a0":{
      "scriptId":"u2"},
    "48209333595e419886d4c65f4f0e993e":{
      "scriptId":"u3"},
    "6bc11e2053924be2b829b5d60a35e97d":{
      "scriptId":"u4"},
    "e5aee3c961ed40279d319bc628a95c05":{
      "scriptId":"u5"},
    "2f89bc28f2fd4cfcb7b607f2d8006b4a":{
      "scriptId":"u6"},
    "a96a0b142ca14527942943496855b861":{
      "scriptId":"u7"},
    "e62ec371797543f5bc1f93d648313d6a":{
      "scriptId":"u8"},
    "7d22bab30e8144639b3e8c024a5060ba":{
      "scriptId":"u9"},
    "d758fe6946ba44d5996e57f091c7ac05":{
      "scriptId":"u10"},
    "b5271d09e5c845fcbf4377c25eba35a5":{
      "scriptId":"u11"},
    "8e1e989d0b244fe08ceaed84d628fd47":{
      "scriptId":"u12"},
    "a5c03622c5da4326b3e0001fc65ab8fc":{
      "scriptId":"u13"},
    "1c75fa2616814ae0b0e0a0a01841e4ee":{
      "scriptId":"u14"},
    "a5ac6315a0eb49febf8f4d808b58dd8a":{
      "scriptId":"u15"},
    "4c52f31eaec14c72ad6dc07792981d05":{
      "scriptId":"u16"},
    "f4ac786c804f47a5962f1947983fb661":{
      "scriptId":"u17"},
    "c869ee4ddd6044a887bf2206a7d4bf6b":{
      "scriptId":"u18"},
    "b7a6a7a169f14fa68323694119f7a11a":{
      "scriptId":"u19"},
    "fe4f162bbd7f42f8b58e65e76d02f564":{
      "scriptId":"u20"},
    "5d936dd7fecd46df85b71d1d283086c2":{
      "scriptId":"u21"},
    "283e33037802493cb6c7626ee6210390":{
      "scriptId":"u22"},
    "cf2fce67579a43319b44c8c2babc8095":{
      "scriptId":"u23"},
    "5791fa1cd7ec4d8fb1d46688246492a0":{
      "scriptId":"u24"},
    "20bb28d1450f45fe91849ff60c1dfa3e":{
      "scriptId":"u25"},
    "ca77d32c17c14d188baa842cdc6fdb0e":{
      "scriptId":"u26"},
    "fe74a70503af40bfb958c6f016c9c708":{
      "scriptId":"u27"},
    "e504bde314a641519a03ae4b49935275":{
      "scriptId":"u28"},
    "3b073db29765421bbdcbc01a9391ac57":{
      "scriptId":"u29"},
    "42478b1a038b4d09972d82c87c89cd77":{
      "scriptId":"u30"},
    "807e7ca0fa334d58bf20de9745bdf80e":{
      "scriptId":"u31"},
    "43d4639f047e47f4b478e30a642ede86":{
      "scriptId":"u32"},
    "d6cb68f975ae41b2bba220eacdaaf0cb":{
      "scriptId":"u33"},
    "fbe1176324684e46ac4c4099d7444482":{
      "scriptId":"u34"},
    "ef46fb6e334b4cad96dbfdbf0b4b8b9c":{
      "scriptId":"u35"},
    "ac763dab567e4746b64d802a32eccb80":{
      "scriptId":"u36"},
    "ffa552321aad45fc9cb9338fad649884":{
      "scriptId":"u37"},
    "4de7980df1654a5992958d1976c2fb3c":{
      "scriptId":"u38"},
    "f66756354de0491db1936bc2ff5fc6e1":{
      "scriptId":"u39"},
    "53e37ad4108d4e02b7bf1f0b24976257":{
      "scriptId":"u40"},
    "5d947320a0a54666a32fc874e100e0b3":{
      "scriptId":"u41"},
    "ff1e361a63754c53a7a70907e91e0594":{
      "scriptId":"u42"},
    "c152ac65376940ce943cbb2083aefe58":{
      "scriptId":"u43"},
    "435d500a8849494a9d383912a0a1b6a9":{
      "scriptId":"u44"},
    "a706e058ab8f4ff28d7d73aa3c0fc1c5":{
      "scriptId":"u45"},
    "5cd6ce6867e049db96b4ebda17a2b58e":{
      "scriptId":"u46"},
    "77d4eb910e6541b384a4288698a2fc4d":{
      "scriptId":"u47"},
    "0b954df777074e159dc429f6e8150cf0":{
      "scriptId":"u48"},
    "eac91ab7aedf41eeb2d7b12722a0bd13":{
      "scriptId":"u49"}}});