$axure.loadCurrentPage({
  "url":"设计师信息页.html",
  "generationDate":new Date(1417146910753.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"130da927337d4c769f3fe9297bc2fd0f",
    "type":"Axure:Page",
    "name":"设计师信息页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fb91858b2a3643b9b947767740053427",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":30},
            "size":{
              "width":320,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40544ef39a58483fa029201a2eb441a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":30},
                "size":{
                  "width":320,
                  "height":495}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u0.png"}},
{
          "id":"991966f26b3048a3acd3dc9ac72064d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":70,
              "y":30},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75b70e6105f14559a47943db626d6ee7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":70,
                  "y":30},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u2.png"}},
{
          "id":"fa78acaf5a2546c7af792ae510ecafdd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":90},
            "size":{
              "width":46,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3f21c652514d35a9f2ca41a02aa7e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":90},
                "size":{
                  "width":46,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u56.png"}},
{
          "id":"301b72c479284cd08f9418d05deed289",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":92},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb44c36d7f1d4866bb8a29b916143cbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":92},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbf629b150924c8b9d4a93bbca2b93f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":114},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7964a4c512b742229e5970bcdf96b5a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":114},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e922da664ae14dab8c1093c21168aba7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":140},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/设计师信息页/u10_line.png"}},
{
          "id":"601c14c2b24145dcb75a9eccdc31fa71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":78,
              "y":145},
            "size":{
              "width":306,
              "height":115},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d670bddf0e2d4cce8b8874764b0b8966",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":78,
                  "y":145},
                "size":{
                  "width":306,
                  "height":115},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师信息页/u11.png"}},
{
          "id":"462fa1e6196d4861b54e51e90b8b0490",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":204},
            "size":{
              "width":131,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5038935058d74987abad508e9858a865",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":93,
                  "y":204},
                "size":{
                  "width":131,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56236badecec44b3a7634a3b149453c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":179},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2135517bba744d4391faa849a6dc5866",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":179},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a003fb55f9024b0696810d34ebe17850",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":178},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"701b99fa34d6486cac07797360bb81cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":93,
                  "y":178},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c9f11dedf894f18b0f268e8937ee9fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":230},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d6ea42d705f431e97095c704b8e3e32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":93,
                  "y":230},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c1086b6342a4a0998e365e7931dbf63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":77,
              "y":266},
            "size":{
              "width":306,
              "height":259},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d55bfbab6325477db32e61f0646067eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":77,
                  "y":266},
                "size":{
                  "width":306,
                  "height":259},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师信息页/u21.png"}},
{
          "id":"c54b8a2fba0d4dc8b20277812b71fd7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":150},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"209d8de37f384bc1ae1405c7ba763da2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":93,
                  "y":150},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a8dfe7b50c945a1b6429bda384e2e83",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":166},
            "size":{
              "width":306,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/设计师信息页/u25_line.png"}},
{
          "id":"7ef1e11739614cf58d5030eb7cca3c4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":276},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cee20403b3544b9aec1f6369329da95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":93,
                  "y":276},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c418abad953f429982afef9bbde47fd8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":292},
            "size":{
              "width":306,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/设计师信息页/u25_line.png"}},
{
          "id":"3f8cc4d8825b4c388ab2630ba27d107a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":312},
            "size":{
              "width":267,
              "height":181}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a07787e610b4333a5e514d8406cb396",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":93,
                  "y":312},
                "size":{
                  "width":267,
                  "height":181}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师信息页/u29.jpg"}},
{
          "id":"1af5e9a5d5824115a6d9d61b061362bf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":67.5,
              "y":30},
            "size":{
              "width":325,
              "height":689}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a66c0e480df4e12880bf8e780ed58ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67.5,
                  "y":30},
                "size":{
                  "width":325,
                  "height":689}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计师信息页/u31.jpg"}},
{
          "id":"846125e9ccf04380962ac551ea839f1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":70,
              "y":30},
            "size":{
              "width":33,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"645da3cd282343c091c794d96f36df00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":70,
                  "y":30},
                "size":{
                  "width":33,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全部客户",
                      "target":{
                        "targetType":"page",
                        "url":"全部客户.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "fb91858b2a3643b9b947767740053427":{
      "scriptId":"u0"},
    "40544ef39a58483fa029201a2eb441a2":{
      "scriptId":"u1"},
    "991966f26b3048a3acd3dc9ac72064d7":{
      "scriptId":"u2"},
    "75b70e6105f14559a47943db626d6ee7":{
      "scriptId":"u3"},
    "fa78acaf5a2546c7af792ae510ecafdd":{
      "scriptId":"u4"},
    "7c3f21c652514d35a9f2ca41a02aa7e6":{
      "scriptId":"u5"},
    "301b72c479284cd08f9418d05deed289":{
      "scriptId":"u6"},
    "bb44c36d7f1d4866bb8a29b916143cbb":{
      "scriptId":"u7"},
    "bbf629b150924c8b9d4a93bbca2b93f3":{
      "scriptId":"u8"},
    "7964a4c512b742229e5970bcdf96b5a4":{
      "scriptId":"u9"},
    "e922da664ae14dab8c1093c21168aba7":{
      "scriptId":"u10"},
    "601c14c2b24145dcb75a9eccdc31fa71":{
      "scriptId":"u11"},
    "d670bddf0e2d4cce8b8874764b0b8966":{
      "scriptId":"u12"},
    "462fa1e6196d4861b54e51e90b8b0490":{
      "scriptId":"u13"},
    "5038935058d74987abad508e9858a865":{
      "scriptId":"u14"},
    "56236badecec44b3a7634a3b149453c4":{
      "scriptId":"u15"},
    "2135517bba744d4391faa849a6dc5866":{
      "scriptId":"u16"},
    "a003fb55f9024b0696810d34ebe17850":{
      "scriptId":"u17"},
    "701b99fa34d6486cac07797360bb81cf":{
      "scriptId":"u18"},
    "4c9f11dedf894f18b0f268e8937ee9fd":{
      "scriptId":"u19"},
    "1d6ea42d705f431e97095c704b8e3e32":{
      "scriptId":"u20"},
    "1c1086b6342a4a0998e365e7931dbf63":{
      "scriptId":"u21"},
    "d55bfbab6325477db32e61f0646067eb":{
      "scriptId":"u22"},
    "c54b8a2fba0d4dc8b20277812b71fd7b":{
      "scriptId":"u23"},
    "209d8de37f384bc1ae1405c7ba763da2":{
      "scriptId":"u24"},
    "5a8dfe7b50c945a1b6429bda384e2e83":{
      "scriptId":"u25"},
    "7ef1e11739614cf58d5030eb7cca3c4f":{
      "scriptId":"u26"},
    "2cee20403b3544b9aec1f6369329da95":{
      "scriptId":"u27"},
    "c418abad953f429982afef9bbde47fd8":{
      "scriptId":"u28"},
    "3f8cc4d8825b4c388ab2630ba27d107a":{
      "scriptId":"u29"},
    "9a07787e610b4333a5e514d8406cb396":{
      "scriptId":"u30"},
    "1af5e9a5d5824115a6d9d61b061362bf":{
      "scriptId":"u31"},
    "9a66c0e480df4e12880bf8e780ed58ef":{
      "scriptId":"u32"},
    "846125e9ccf04380962ac551ea839f1e":{
      "scriptId":"u33"},
    "645da3cd282343c091c794d96f36df00":{
      "scriptId":"u34"}}});