$axure.loadCurrentPage({
  "url":"签约客户.html",
  "generationDate":new Date(1416974249648.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c7f58e0d51b44fe69c913db5412abb73",
    "type":"Axure:Page",
    "name":"签约客户",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e50f4734ad1242b6b2499e63c1c9b674",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":207,
              "y":30},
            "size":{
              "width":320,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f36ad66ee4d456e9a0808077b5e97cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":207,
                  "y":30},
                "size":{
                  "width":320,
                  "height":495}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u0.png"}},
{
          "id":"2a6298ead607485fafc158da5bdb1289",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":207,
              "y":30},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b526f74204484c7482db92767e7fc181",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":207,
                  "y":30},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u2.png"}},
{
          "id":"357c981680954f66b924994b5db39620",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":78},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dcdbf9ce12a440084b37482d647f3d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":78},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u54.png"}},
{
          "id":"80a8916b2ae7457d98eecbcb45dd0733",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":85},
            "size":{
              "width":46,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df8197f9834a487da16396068858cb0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":85},
                "size":{
                  "width":46,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 客户个人信息",
                      "target":{
                        "targetType":"page",
                        "url":"客户个人信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/搜索/u56.png"}},
{
          "id":"594f904174cd45faaef8217a3bae7119",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":90},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cce823585dda4fbc90ffeeced1331071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":90},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f577e9d053ca4eddb30a92a499d0a2ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3333FF,
              "opacity":1},
            "location":{
              "x":295,
              "y":109},
            "size":{
              "width":79,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd0d715da76b4d63a4aa2fd932c5c080",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3333FF,
                  "opacity":1},
                "location":{
                  "x":295,
                  "y":109},
                "size":{
                  "width":79,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e69f2b2c76d4a4ea78b53413e8ce082",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":256,
              "y":83},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"325f7b9c16594b6aa9b7517dbdba4e2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":256,
                  "y":83},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约客户/u12.png"}},
{
          "id":"899fe6e7c3d54ec1852ea4439b9e07da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":178},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"665d0489f1c64a55bf1a346e94774799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":178},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u54.png"}},
{
          "id":"3434fa9b8c104353a41b2144ca756aa4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":185},
            "size":{
              "width":46,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c254f89362241249e162f18f8acea3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":185},
                "size":{
                  "width":46,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u56.png"}},
{
          "id":"51a959843a404d8bb336878545803f0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":190},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3706e65223e34d5d9a31d45621e53cc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":190},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c62793111555483ab9b545589b104ff0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3333FF,
              "opacity":1},
            "location":{
              "x":295,
              "y":209},
            "size":{
              "width":73,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6acf125021ab4667939580735684ccd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3333FF,
                  "opacity":1},
                "location":{
                  "x":295,
                  "y":209},
                "size":{
                  "width":73,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfba0c69b8b14236a01cf48113c0db68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":228},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac8e9a3e892a4be6b4272729c6562f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":228},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u54.png"}},
{
          "id":"dabbab12bc7847e29304cfd2d672422a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":240},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3081c146e6549a890f1e7c058846c85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":240},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad9023081645440cab13644786c95f48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3333FF,
              "opacity":1},
            "location":{
              "x":295,
              "y":259},
            "size":{
              "width":73,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80fbff81afea49d19c1da46cd9bd815f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3333FF,
                  "opacity":1},
                "location":{
                  "x":295,
                  "y":259},
                "size":{
                  "width":73,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42e870cd15cc42689b0b2f6525d0fc35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":236},
            "size":{
              "width":46,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4be4d3afd38427181e8338a8c6b4772",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":236},
                "size":{
                  "width":46,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u68.png"}},
{
          "id":"1e02fc5640b949a18c1d80ce657c7e50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":279},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dca72be8be94bf087232aff55d0b592",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":279},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u54.png"}},
{
          "id":"8bf90ad604a14a8b9891a012aae98301",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":286},
            "size":{
              "width":46,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"214a62a1d9424f8980aa9091f022654d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":286},
                "size":{
                  "width":46,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u56.png"}},
{
          "id":"23b1aa3b14d14b71893aeb516d494de7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":291},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e23e6ded27bd4a18ac9ee57082e50cb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":291},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4a6e7a1310542ae9f11272ffa553f4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3333FF,
              "opacity":1},
            "location":{
              "x":295,
              "y":310},
            "size":{
              "width":73,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb598067655246b2873dba3627352494",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3333FF,
                  "opacity":1},
                "location":{
                  "x":295,
                  "y":310},
                "size":{
                  "width":73,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25f7a301128645c7aa200b5460a04b2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":329},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3de48fe0cc7349359de0e05bb83f346d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":329},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u54.png"}},
{
          "id":"b1f60f37f27b42b6abf22db409d24c85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":341},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b79b83a41ee04437b09a939756221cb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":341},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c691c51f63434affa0f63e44e1d781b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3333FF,
              "opacity":1},
            "location":{
              "x":295,
              "y":360},
            "size":{
              "width":73,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0aa7461caa54e9d9503e3fdcc7857f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3333FF,
                  "opacity":1},
                "location":{
                  "x":295,
                  "y":360},
                "size":{
                  "width":73,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f22990fa848441a38805c1f0bf8410f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":337},
            "size":{
              "width":46,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afe1f3f7ad924ea9a0181eb31580abff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":337},
                "size":{
                  "width":46,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u68.png"}},
{
          "id":"06af502c12214633b0b886c48727ce4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":380},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"923650ed35c64924ab2b9a6253708c24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":380},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u54.png"}},
{
          "id":"cd5e4b5d31f64aeda1645ece6c0de449",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":387},
            "size":{
              "width":46,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"102066b9aa5b405cae82c4c9b02fe614",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":387},
                "size":{
                  "width":46,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u56.png"}},
{
          "id":"cc808d549f924548bccf313eb7305bd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":392},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68c2583fe6b84b0da97a6daf9806c5e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":392},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13a41fda43b34fba9ebfd5b525703dda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3333FF,
              "opacity":1},
            "location":{
              "x":295,
              "y":411},
            "size":{
              "width":73,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e27ed91655f8470181130eda687eae35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3333FF,
                  "opacity":1},
                "location":{
                  "x":295,
                  "y":411},
                "size":{
                  "width":73,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4507bf3ed62e4b4aba75dab8c9f32ea9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":430},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dc5d5e17d24487aae5feeb2435a5fcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":430},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u54.png"}},
{
          "id":"605798f1f74a411ea0e79bd5225ae9c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":442},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"454701d93d844bfca83e06ca44d81850",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":442},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e2b041433754c0db9065260cfbdb559",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3333FF,
              "opacity":1},
            "location":{
              "x":295,
              "y":461},
            "size":{
              "width":80,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cf3d727b7e44be18345fc0db0b55a42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3333FF,
                  "opacity":1},
                "location":{
                  "x":295,
                  "y":461},
                "size":{
                  "width":80,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2b9791f2b674f6992687bd7bbf9b63d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":438},
            "size":{
              "width":46,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8aa05429e68047a9a460ef40c6a6d385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":438},
                "size":{
                  "width":46,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u68.png"}},
{
          "id":"67db660f24ca49bc8f54484797b5c966",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":156},
            "size":{
              "width":10,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/签约客户/u62_line.png"}},
{
          "id":"b5c5e85714e948679b750b7296ce81ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":44},
            "size":{
              "width":20,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"880c68d432de47e2807f2628e97092e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":497,
                  "y":44},
                "size":{
                  "width":20,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 搜索",
                      "target":{
                        "targetType":"page",
                        "url":"搜索.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/签约客户/u63.png"}},
{
          "id":"69912a9eb7b3488693f2698d9d8e9c65",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":29}},
          "adaptiveStyles":{
},
          "masterId":"99966c745e5f45f4976c9a95bb5da09d"},
{
          "id":"8c8fb84f5f8047f0a2858ab24181ec40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":490,
              "y":103},
            "size":{
              "width":23,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2447a37bda34f7da956300d3d95e9a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":490,
                  "y":103},
                "size":{
                  "width":23,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约客户/u98.png"}},
{
          "id":"93a8316ba14140599f3063b95b7585f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":490,
              "y":199},
            "size":{
              "width":23,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1418112c836a4c1589ef4541308bb280",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":490,
                  "y":199},
                "size":{
                  "width":23,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约客户/u100.png"}},
{
          "id":"acf363125f934984b0f12019cbb8ea92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":490,
              "y":248},
            "size":{
              "width":23,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76d73a4a8f4d49dc9f6effc1fab9d645",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":490,
                  "y":248},
                "size":{
                  "width":23,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约客户/u100.png"}},
{
          "id":"c1b8db723f75491895e7e57830f163fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":490,
              "y":300},
            "size":{
              "width":23,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f39ea3c027a74b51bc70cfe5fcdeb9c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":490,
                  "y":300},
                "size":{
                  "width":23,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约客户/u100.png"}},
{
          "id":"f7d5db62ed174377bb9dcc9c9a70d773",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":490,
              "y":349},
            "size":{
              "width":23,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4a7f6b925ef4831bf5c64c8d37a0b6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":490,
                  "y":349},
                "size":{
                  "width":23,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约客户/u100.png"}},
{
          "id":"f92a23085f1147a59bdf5c0517b0d9de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":490,
              "y":401},
            "size":{
              "width":23,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3590cf40a3ea46738b532a2d800e0768",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":490,
                  "y":401},
                "size":{
                  "width":23,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约客户/u100.png"}},
{
          "id":"5734d828e7734ab4bbe12b727cf29a49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":490,
              "y":450},
            "size":{
              "width":23,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f65301fc1bcc4b948af267f26f0770e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":490,
                  "y":450},
                "size":{
                  "width":23,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约客户/u100.png"}},
{
          "id":"062d2a22586e450abf4173040d2fbaa6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":208,
              "y":128},
            "size":{
              "width":81,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94a5cbb891364f57994021f1fd266b49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":208,
                  "y":128},
                "size":{
                  "width":81,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天",
                      "target":{
                        "targetType":"page",
                        "url":"聊天.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/签约客户/u112.png"}},
{
          "id":"dc2f28e9107a49e28d12f4f5cfd51e9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":287,
              "y":128},
            "size":{
              "width":81,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22b73ca2c3014c5688b92bc61f7b41cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":287,
                  "y":128},
                "size":{
                  "width":81,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签约客户/u112.png"}},
{
          "id":"7b423e9e65504bca950705bb64cbd0fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":367,
              "y":128},
            "size":{
              "width":81,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d6e55175c3a4574a884898898c8d822",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":367,
                  "y":128},
                "size":{
                  "width":81,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 日程编辑页",
                      "target":{
                        "targetType":"page",
                        "url":"日程编辑页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/签约客户/u112.png"}},
{
          "id":"77bc1d9889f1433cbed558ec6931ef85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":446,
              "y":128},
            "size":{
              "width":81,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f692768612d45128cf2df0ac029d1e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":446,
                  "y":128},
                "size":{
                  "width":81,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 客户个人信息",
                      "target":{
                        "targetType":"page",
                        "url":"客户个人信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/签约客户/u112.png"}},
{
          "id":"9b3ff0cf86254ee399a43858e706a37c",
          "label":"签约客户",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":208,
              "y":78},
            "size":{
              "width":320,
              "height":120},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"fbd570bdda4e4837bb9dfef23f63506d",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"361dbf38fa0343388ed25c67659af92c",
                  "label":"",
                  "parentDynamicPanel":"9b3ff0cf86254ee399a43858e706a37c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "size":{
                      "width":320,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0e9c6e3fde974e6caf2138003fcb5245",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b3ff0cf86254ee399a43858e706a37c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "size":{
                          "width":320,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 签约客户",
                              "target":{
                                "targetType":"page",
                                "url":"签约客户.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/日程/u108.png"}},
{
                  "id":"992f15e13f184b768a8c90cd34ba6a9b",
                  "label":"",
                  "parentDynamicPanel":"9b3ff0cf86254ee399a43858e706a37c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":320,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"43ea929b0a044067a195ca6a7c9c233e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b3ff0cf86254ee399a43858e706a37c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "location":{
                          "x":0,
                          "y":40},
                        "size":{
                          "width":320,
                          "height":41},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 意向客户",
                              "target":{
                                "targetType":"page",
                                "url":"意向客户.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/日程/u108.png"}},
{
                  "id":"5cb4680f26444de49cb32e282f528017",
                  "label":"",
                  "parentDynamicPanel":"9b3ff0cf86254ee399a43858e706a37c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":287,
                      "y":10.5},
                    "size":{
                      "width":23,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"98c9f5377cc94d00a5bd216f66b3f156",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b3ff0cf86254ee399a43858e706a37c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":287,
                          "y":10.5},
                        "size":{
                          "width":23,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/日程/u112.png"}}]}]},
{
          "id":"5b710c3d5d4f4cdb8e04bde617c99c64",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":46},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5694d390dc774a4ca41e74ed29cb3940",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":338,
                  "y":46},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91d5c700a5b74bcc96ac645dd189b1d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":395,
              "y":50},
            "size":{
              "width":18,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b49e29de5bf481a982cb637fa181e5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":395,
                  "y":50},
                "size":{
                  "width":18,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/日程/u116.png"}},
{
          "id":"dcde77e942b241db99ecdc8ffe007ae0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":333,
              "y":40},
            "size":{
              "width":102,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55216295d5fd457ebad20715a4cf1bea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":333,
                  "y":40},
                "size":{
                  "width":102,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 签约客户",
                      "objectsToFades":[{
                          "objectPath":["9b3ff0cf86254ee399a43858e706a37c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/签约客户/u131.png"}}]}},
  "masters":{
    "99966c745e5f45f4976c9a95bb5da09d":{
      "packageId":"99966c745e5f45f4976c9a95bb5da09d",
      "type":"Axure:Master",
      "name":"客户管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"21a821cb16b54306b9015940b180a62a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":178,
                "y":14},
              "size":{
                "width":29,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fbbf13530b6b49e787465f7a571acfa3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":178,
                    "y":14},
                  "size":{
                    "width":29,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u65.png"}},
{
            "id":"a1fe460a89ae47ee97b68852bf32ac45",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "location":{
                "x":1,
                "y":0},
              "size":{
                "width":170,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3fd417b58ca349ebb4d4981f6122bf5d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "location":{
                    "x":1,
                    "y":0},
                  "size":{
                    "width":170,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u67.png"}},
{
            "id":"1cd1a7f0e67241bb8ba5d7b6b62eb716",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":50},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da48e42ab03e4ab6ac48b84208588f1f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":50},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 日程",
                        "target":{
                          "targetType":"page",
                          "url":"日程.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/日程/u73.png"}},
{
            "id":"54902604f47c44048a587be91b30756f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":66},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e83528ad13b64bee8a10ef3f6e9855d1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":66},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u54.png"}},
{
            "id":"5d12d74c96df4882b31e6343bf1cd305",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":1,
                "y":94},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1248eaabc571433aa2b244f86e20a54b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":1,
                    "y":94},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 签约客户",
                        "target":{
                          "targetType":"page",
                          "url":"签约客户.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/日程/u69.png"}},
{
            "id":"628f6484e12940bd99afc1b51bc88af1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":153,
                "y":112},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"87f2cd1c7a074a59862f829ccf129058",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":153,
                    "y":112},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u75.png"}},
{
            "id":"d807acd0e9984e3598688184ce6e1493",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":110},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13798a5a4cd948f9a2ad5920e11adaf8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":110},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u54.png"}},
{
            "id":"b1af99fc529d45739c179d593305efd1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":139},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3adca718259f4cef84f7784c75e861be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":139},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u73.png"}},
{
            "id":"065baa2c43d44a8fa95af24921c91cfb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":153,
                "y":156},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9ad0f25db1cc4d209e4c95fd3fe655fa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":153,
                    "y":156},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u75.png"}},
{
            "id":"377aac317b9340359789438e770fa200",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":156},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7039944031114272ba855fd709db50c7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":156},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u54.png"}},
{
            "id":"4b324441b48e47dd9c143d09e20ab94f",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":90},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u85_line.png"}},
{
            "id":"b6f7194cec7e43ceaa66a9050ef10c72",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":184},
              "size":{
                "width":170,
                "height":45}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9cf03b547ff4121ac3aa6afe8c798e7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":184},
                  "size":{
                    "width":170,
                    "height":45}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u73.png"}},
{
            "id":"e5a0a46b28064b71885cd7878f644bd4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":153,
                "y":202},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"16f4a3dba55e4ef4a4a0812359f0e9a2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":153,
                    "y":202},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u75.png"}},
{
            "id":"177bb9e0bb5a4b52b7d1b0fb22d3ddb0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":153,
                "y":200},
              "size":{
                "width":6,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a54d9d6efa24743a08b7d6759498e65",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":153,
                    "y":200},
                  "size":{
                    "width":6,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u54.png"}},
{
            "id":"1d965cb0186a4f4891af930d058faba0",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":178},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u85_line.png"}},
{
            "id":"8ee97f95eac44c908349b0f7fe786fa3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "location":{
                "x":1,
                "y":230},
              "size":{
                "width":170,
                "height":266}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f815ced99d8f44a3a9a4953dc461a0c3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "location":{
                    "x":1,
                    "y":230},
                  "size":{
                    "width":170,
                    "height":266}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/日程/u94.png"}},
{
            "id":"345f63b7e52c4a00ac36d1ef82074e39",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":224},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u85_line.png"}},
{
            "id":"d3621adbffe44a69bba07a4030de9746",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1,
                "y":134},
              "size":{
                "width":170,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1},
              "linePattern":"dotted"},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/日程/u85_line.png"}}]}}},
  "objectPaths":{
    "e50f4734ad1242b6b2499e63c1c9b674":{
      "scriptId":"u0"},
    "6f36ad66ee4d456e9a0808077b5e97cc":{
      "scriptId":"u1"},
    "2a6298ead607485fafc158da5bdb1289":{
      "scriptId":"u2"},
    "b526f74204484c7482db92767e7fc181":{
      "scriptId":"u3"},
    "357c981680954f66b924994b5db39620":{
      "scriptId":"u4"},
    "3dcdbf9ce12a440084b37482d647f3d9":{
      "scriptId":"u5"},
    "80a8916b2ae7457d98eecbcb45dd0733":{
      "scriptId":"u6"},
    "df8197f9834a487da16396068858cb0f":{
      "scriptId":"u7"},
    "594f904174cd45faaef8217a3bae7119":{
      "scriptId":"u8"},
    "cce823585dda4fbc90ffeeced1331071":{
      "scriptId":"u9"},
    "f577e9d053ca4eddb30a92a499d0a2ee":{
      "scriptId":"u10"},
    "dd0d715da76b4d63a4aa2fd932c5c080":{
      "scriptId":"u11"},
    "7e69f2b2c76d4a4ea78b53413e8ce082":{
      "scriptId":"u12"},
    "325f7b9c16594b6aa9b7517dbdba4e2c":{
      "scriptId":"u13"},
    "899fe6e7c3d54ec1852ea4439b9e07da":{
      "scriptId":"u14"},
    "665d0489f1c64a55bf1a346e94774799":{
      "scriptId":"u15"},
    "3434fa9b8c104353a41b2144ca756aa4":{
      "scriptId":"u16"},
    "7c254f89362241249e162f18f8acea3a":{
      "scriptId":"u17"},
    "51a959843a404d8bb336878545803f0e":{
      "scriptId":"u18"},
    "3706e65223e34d5d9a31d45621e53cc2":{
      "scriptId":"u19"},
    "c62793111555483ab9b545589b104ff0":{
      "scriptId":"u20"},
    "6acf125021ab4667939580735684ccd6":{
      "scriptId":"u21"},
    "dfba0c69b8b14236a01cf48113c0db68":{
      "scriptId":"u22"},
    "ac8e9a3e892a4be6b4272729c6562f8b":{
      "scriptId":"u23"},
    "dabbab12bc7847e29304cfd2d672422a":{
      "scriptId":"u24"},
    "d3081c146e6549a890f1e7c058846c85":{
      "scriptId":"u25"},
    "ad9023081645440cab13644786c95f48":{
      "scriptId":"u26"},
    "80fbff81afea49d19c1da46cd9bd815f":{
      "scriptId":"u27"},
    "42e870cd15cc42689b0b2f6525d0fc35":{
      "scriptId":"u28"},
    "b4be4d3afd38427181e8338a8c6b4772":{
      "scriptId":"u29"},
    "1e02fc5640b949a18c1d80ce657c7e50":{
      "scriptId":"u30"},
    "4dca72be8be94bf087232aff55d0b592":{
      "scriptId":"u31"},
    "8bf90ad604a14a8b9891a012aae98301":{
      "scriptId":"u32"},
    "214a62a1d9424f8980aa9091f022654d":{
      "scriptId":"u33"},
    "23b1aa3b14d14b71893aeb516d494de7":{
      "scriptId":"u34"},
    "e23e6ded27bd4a18ac9ee57082e50cb3":{
      "scriptId":"u35"},
    "d4a6e7a1310542ae9f11272ffa553f4a":{
      "scriptId":"u36"},
    "fb598067655246b2873dba3627352494":{
      "scriptId":"u37"},
    "25f7a301128645c7aa200b5460a04b2a":{
      "scriptId":"u38"},
    "3de48fe0cc7349359de0e05bb83f346d":{
      "scriptId":"u39"},
    "b1f60f37f27b42b6abf22db409d24c85":{
      "scriptId":"u40"},
    "b79b83a41ee04437b09a939756221cb0":{
      "scriptId":"u41"},
    "c691c51f63434affa0f63e44e1d781b0":{
      "scriptId":"u42"},
    "d0aa7461caa54e9d9503e3fdcc7857f7":{
      "scriptId":"u43"},
    "f22990fa848441a38805c1f0bf8410f8":{
      "scriptId":"u44"},
    "afe1f3f7ad924ea9a0181eb31580abff":{
      "scriptId":"u45"},
    "06af502c12214633b0b886c48727ce4a":{
      "scriptId":"u46"},
    "923650ed35c64924ab2b9a6253708c24":{
      "scriptId":"u47"},
    "cd5e4b5d31f64aeda1645ece6c0de449":{
      "scriptId":"u48"},
    "102066b9aa5b405cae82c4c9b02fe614":{
      "scriptId":"u49"},
    "cc808d549f924548bccf313eb7305bd2":{
      "scriptId":"u50"},
    "68c2583fe6b84b0da97a6daf9806c5e3":{
      "scriptId":"u51"},
    "13a41fda43b34fba9ebfd5b525703dda":{
      "scriptId":"u52"},
    "e27ed91655f8470181130eda687eae35":{
      "scriptId":"u53"},
    "4507bf3ed62e4b4aba75dab8c9f32ea9":{
      "scriptId":"u54"},
    "6dc5d5e17d24487aae5feeb2435a5fcd":{
      "scriptId":"u55"},
    "605798f1f74a411ea0e79bd5225ae9c1":{
      "scriptId":"u56"},
    "454701d93d844bfca83e06ca44d81850":{
      "scriptId":"u57"},
    "1e2b041433754c0db9065260cfbdb559":{
      "scriptId":"u58"},
    "8cf3d727b7e44be18345fc0db0b55a42":{
      "scriptId":"u59"},
    "f2b9791f2b674f6992687bd7bbf9b63d":{
      "scriptId":"u60"},
    "8aa05429e68047a9a460ef40c6a6d385":{
      "scriptId":"u61"},
    "67db660f24ca49bc8f54484797b5c966":{
      "scriptId":"u62"},
    "b5c5e85714e948679b750b7296ce81ac":{
      "scriptId":"u63"},
    "880c68d432de47e2807f2628e97092e8":{
      "scriptId":"u64"},
    "69912a9eb7b3488693f2698d9d8e9c65":{
      "scriptId":"u65",
      "21a821cb16b54306b9015940b180a62a":{
        "scriptId":"u66"},
      "fbbf13530b6b49e787465f7a571acfa3":{
        "scriptId":"u67"},
      "a1fe460a89ae47ee97b68852bf32ac45":{
        "scriptId":"u68"},
      "3fd417b58ca349ebb4d4981f6122bf5d":{
        "scriptId":"u69"},
      "1cd1a7f0e67241bb8ba5d7b6b62eb716":{
        "scriptId":"u70"},
      "da48e42ab03e4ab6ac48b84208588f1f":{
        "scriptId":"u71"},
      "54902604f47c44048a587be91b30756f":{
        "scriptId":"u72"},
      "e83528ad13b64bee8a10ef3f6e9855d1":{
        "scriptId":"u73"},
      "5d12d74c96df4882b31e6343bf1cd305":{
        "scriptId":"u74"},
      "1248eaabc571433aa2b244f86e20a54b":{
        "scriptId":"u75"},
      "628f6484e12940bd99afc1b51bc88af1":{
        "scriptId":"u76"},
      "87f2cd1c7a074a59862f829ccf129058":{
        "scriptId":"u77"},
      "d807acd0e9984e3598688184ce6e1493":{
        "scriptId":"u78"},
      "13798a5a4cd948f9a2ad5920e11adaf8":{
        "scriptId":"u79"},
      "b1af99fc529d45739c179d593305efd1":{
        "scriptId":"u80"},
      "3adca718259f4cef84f7784c75e861be":{
        "scriptId":"u81"},
      "065baa2c43d44a8fa95af24921c91cfb":{
        "scriptId":"u82"},
      "9ad0f25db1cc4d209e4c95fd3fe655fa":{
        "scriptId":"u83"},
      "377aac317b9340359789438e770fa200":{
        "scriptId":"u84"},
      "7039944031114272ba855fd709db50c7":{
        "scriptId":"u85"},
      "4b324441b48e47dd9c143d09e20ab94f":{
        "scriptId":"u86"},
      "b6f7194cec7e43ceaa66a9050ef10c72":{
        "scriptId":"u87"},
      "b9cf03b547ff4121ac3aa6afe8c798e7":{
        "scriptId":"u88"},
      "e5a0a46b28064b71885cd7878f644bd4":{
        "scriptId":"u89"},
      "16f4a3dba55e4ef4a4a0812359f0e9a2":{
        "scriptId":"u90"},
      "177bb9e0bb5a4b52b7d1b0fb22d3ddb0":{
        "scriptId":"u91"},
      "0a54d9d6efa24743a08b7d6759498e65":{
        "scriptId":"u92"},
      "1d965cb0186a4f4891af930d058faba0":{
        "scriptId":"u93"},
      "8ee97f95eac44c908349b0f7fe786fa3":{
        "scriptId":"u94"},
      "f815ced99d8f44a3a9a4953dc461a0c3":{
        "scriptId":"u95"},
      "345f63b7e52c4a00ac36d1ef82074e39":{
        "scriptId":"u96"},
      "d3621adbffe44a69bba07a4030de9746":{
        "scriptId":"u97"}},
    "8c8fb84f5f8047f0a2858ab24181ec40":{
      "scriptId":"u98"},
    "c2447a37bda34f7da956300d3d95e9a2":{
      "scriptId":"u99"},
    "93a8316ba14140599f3063b95b7585f7":{
      "scriptId":"u100"},
    "1418112c836a4c1589ef4541308bb280":{
      "scriptId":"u101"},
    "acf363125f934984b0f12019cbb8ea92":{
      "scriptId":"u102"},
    "76d73a4a8f4d49dc9f6effc1fab9d645":{
      "scriptId":"u103"},
    "c1b8db723f75491895e7e57830f163fd":{
      "scriptId":"u104"},
    "f39ea3c027a74b51bc70cfe5fcdeb9c6":{
      "scriptId":"u105"},
    "f7d5db62ed174377bb9dcc9c9a70d773":{
      "scriptId":"u106"},
    "f4a7f6b925ef4831bf5c64c8d37a0b6c":{
      "scriptId":"u107"},
    "f92a23085f1147a59bdf5c0517b0d9de":{
      "scriptId":"u108"},
    "3590cf40a3ea46738b532a2d800e0768":{
      "scriptId":"u109"},
    "5734d828e7734ab4bbe12b727cf29a49":{
      "scriptId":"u110"},
    "f65301fc1bcc4b948af267f26f0770e7":{
      "scriptId":"u111"},
    "062d2a22586e450abf4173040d2fbaa6":{
      "scriptId":"u112"},
    "94a5cbb891364f57994021f1fd266b49":{
      "scriptId":"u113"},
    "dc2f28e9107a49e28d12f4f5cfd51e9a":{
      "scriptId":"u114"},
    "22b73ca2c3014c5688b92bc61f7b41cc":{
      "scriptId":"u115"},
    "7b423e9e65504bca950705bb64cbd0fd":{
      "scriptId":"u116"},
    "9d6e55175c3a4574a884898898c8d822":{
      "scriptId":"u117"},
    "77bc1d9889f1433cbed558ec6931ef85":{
      "scriptId":"u118"},
    "6f692768612d45128cf2df0ac029d1e7":{
      "scriptId":"u119"},
    "9b3ff0cf86254ee399a43858e706a37c":{
      "scriptId":"u120"},
    "361dbf38fa0343388ed25c67659af92c":{
      "scriptId":"u121"},
    "0e9c6e3fde974e6caf2138003fcb5245":{
      "scriptId":"u122"},
    "992f15e13f184b768a8c90cd34ba6a9b":{
      "scriptId":"u123"},
    "43ea929b0a044067a195ca6a7c9c233e":{
      "scriptId":"u124"},
    "5cb4680f26444de49cb32e282f528017":{
      "scriptId":"u125"},
    "98c9f5377cc94d00a5bd216f66b3f156":{
      "scriptId":"u126"},
    "5b710c3d5d4f4cdb8e04bde617c99c64":{
      "scriptId":"u127"},
    "5694d390dc774a4ca41e74ed29cb3940":{
      "scriptId":"u128"},
    "91d5c700a5b74bcc96ac645dd189b1d3":{
      "scriptId":"u129"},
    "8b49e29de5bf481a982cb637fa181e5a":{
      "scriptId":"u130"},
    "dcde77e942b241db99ecdc8ffe007ae0":{
      "scriptId":"u131"},
    "55216295d5fd457ebad20715a4cf1bea":{
      "scriptId":"u132"}}});