$axure.loadCurrentPage({
  "url":"客户列表.html",
  "generationDate":new Date(1416883964025.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c7f58e0d51b44fe69c913db5412abb73",
    "type":"Axure:Page",
    "name":"客户列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e50f4734ad1242b6b2499e63c1c9b674",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":30},
            "size":{
              "width":320,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f36ad66ee4d456e9a0808077b5e97cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":30},
                "size":{
                  "width":320,
                  "height":495}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u0.png"}},
{
          "id":"2a6298ead607485fafc158da5bdb1289",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":70,
              "y":30},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b526f74204484c7482db92767e7fc181",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":70,
                  "y":30},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u2.png"}},
{
          "id":"a3b426fe26894011aaaac031e20a8e5f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":39},
            "size":{
              "width":30,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccf63a241bb94b6ba0fefa896e061226",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":39},
                "size":{
                  "width":30,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设计师信息页",
                      "target":{
                        "targetType":"page",
                        "url":"设计师信息页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/客户列表/u4.png"}},
{
          "id":"05791a2bf7d947e99ef8ae57b4d25467",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":70,
              "y":80},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59c297bc5ad74a828e659edc353cf530",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":70,
                  "y":80},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u6.png"}},
{
          "id":"77cfb08d81b34c74a72b57d8fb7ababd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":86},
            "size":{
              "width":260,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91fa4e1e5d7f4477b2d01436e188748f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":86},
                "size":{
                  "width":260,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u8.png"}},
{
          "id":"a605dce0d9154c28a33696ed1ff74e30",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":199,
              "y":93},
            "size":{
              "width":12,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3862508e0de462b913464b148c8ed51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":199,
                  "y":93},
                "size":{
                  "width":12,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u10.png"}},
{
          "id":"357c981680954f66b924994b5db39620",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":118},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dcdbf9ce12a440084b37482d647f3d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":118},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天",
                      "target":{
                        "targetType":"page",
                        "url":"聊天.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/客户列表/u12.png"}},
{
          "id":"80a8916b2ae7457d98eecbcb45dd0733",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":125},
            "size":{
              "width":46,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df8197f9834a487da16396068858cb0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":125},
                "size":{
                  "width":46,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 客户个人信息",
                      "target":{
                        "targetType":"page",
                        "url":"客户个人信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/客户列表/u14.png"}},
{
          "id":"594f904174cd45faaef8217a3bae7119",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":130},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cce823585dda4fbc90ffeeced1331071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":130},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f577e9d053ca4eddb30a92a499d0a2ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":158,
              "y":149},
            "size":{
              "width":133,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd0d715da76b4d63a4aa2fd932c5c080",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":158,
                  "y":149},
                "size":{
                  "width":133,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e69f2b2c76d4a4ea78b53413e8ce082",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":119,
              "y":123},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"325f7b9c16594b6aa9b7517dbdba4e2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":119,
                  "y":123},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u20.png"}},
{
          "id":"899fe6e7c3d54ec1852ea4439b9e07da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":218},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"665d0489f1c64a55bf1a346e94774799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":218},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u12.png"}},
{
          "id":"3434fa9b8c104353a41b2144ca756aa4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":225},
            "size":{
              "width":46,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c254f89362241249e162f18f8acea3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":225},
                "size":{
                  "width":46,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u14.png"}},
{
          "id":"51a959843a404d8bb336878545803f0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":230},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3706e65223e34d5d9a31d45621e53cc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":230},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c62793111555483ab9b545589b104ff0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":158,
              "y":249},
            "size":{
              "width":133,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6acf125021ab4667939580735684ccd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":158,
                  "y":249},
                "size":{
                  "width":133,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfba0c69b8b14236a01cf48113c0db68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":268},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac8e9a3e892a4be6b4272729c6562f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":268},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u12.png"}},
{
          "id":"dabbab12bc7847e29304cfd2d672422a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":280},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3081c146e6549a890f1e7c058846c85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":280},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad9023081645440cab13644786c95f48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":158,
              "y":299},
            "size":{
              "width":122,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80fbff81afea49d19c1da46cd9bd815f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":158,
                  "y":299},
                "size":{
                  "width":122,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42e870cd15cc42689b0b2f6525d0fc35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":276},
            "size":{
              "width":46,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4be4d3afd38427181e8338a8c6b4772",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":276},
                "size":{
                  "width":46,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u36.png"}},
{
          "id":"1e02fc5640b949a18c1d80ce657c7e50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":319},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dca72be8be94bf087232aff55d0b592",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":319},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u12.png"}},
{
          "id":"8bf90ad604a14a8b9891a012aae98301",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":326},
            "size":{
              "width":46,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"214a62a1d9424f8980aa9091f022654d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":326},
                "size":{
                  "width":46,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u14.png"}},
{
          "id":"23b1aa3b14d14b71893aeb516d494de7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":331},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e23e6ded27bd4a18ac9ee57082e50cb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":331},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4a6e7a1310542ae9f11272ffa553f4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":158,
              "y":350},
            "size":{
              "width":133,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb598067655246b2873dba3627352494",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":158,
                  "y":350},
                "size":{
                  "width":133,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25f7a301128645c7aa200b5460a04b2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":369},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3de48fe0cc7349359de0e05bb83f346d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":369},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u12.png"}},
{
          "id":"b1f60f37f27b42b6abf22db409d24c85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":381},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b79b83a41ee04437b09a939756221cb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":381},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c691c51f63434affa0f63e44e1d781b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":158,
              "y":400},
            "size":{
              "width":122,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0aa7461caa54e9d9503e3fdcc7857f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":158,
                  "y":400},
                "size":{
                  "width":122,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f22990fa848441a38805c1f0bf8410f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":377},
            "size":{
              "width":46,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afe1f3f7ad924ea9a0181eb31580abff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":377},
                "size":{
                  "width":46,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u36.png"}},
{
          "id":"06af502c12214633b0b886c48727ce4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":420},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"923650ed35c64924ab2b9a6253708c24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":420},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u12.png"}},
{
          "id":"cd5e4b5d31f64aeda1645ece6c0de449",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":427},
            "size":{
              "width":46,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"102066b9aa5b405cae82c4c9b02fe614",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":427},
                "size":{
                  "width":46,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u14.png"}},
{
          "id":"cc808d549f924548bccf313eb7305bd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":432},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68c2583fe6b84b0da97a6daf9806c5e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":432},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13a41fda43b34fba9ebfd5b525703dda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":158,
              "y":451},
            "size":{
              "width":133,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e27ed91655f8470181130eda687eae35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":158,
                  "y":451},
                "size":{
                  "width":133,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4507bf3ed62e4b4aba75dab8c9f32ea9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":470},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dc5d5e17d24487aae5feeb2435a5fcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":470},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u12.png"}},
{
          "id":"605798f1f74a411ea0e79bd5225ae9c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":482},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"454701d93d844bfca83e06ca44d81850",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":482},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e2b041433754c0db9065260cfbdb559",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":158,
              "y":501},
            "size":{
              "width":122,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cf3d727b7e44be18345fc0db0b55a42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":158,
                  "y":501},
                "size":{
                  "width":122,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2b9791f2b674f6992687bd7bbf9b63d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":478},
            "size":{
              "width":46,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8aa05429e68047a9a460ef40c6a6d385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":478},
                "size":{
                  "width":46,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u36.png"}},
{
          "id":"aac09d64ce724d3d957adc013d096d83",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":71,
              "y":482},
            "size":{
              "width":160,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bb2d46843a24a198d1b8efe984116ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":71,
                  "y":482},
                "size":{
                  "width":160,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u70.png"}},
{
          "id":"361e6db32c8c4431acec5577bf0df825",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF949494},
            "location":{
              "x":230,
              "y":482},
            "size":{
              "width":160,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebc7f977a8b54560aade6afa4db588d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "location":{
                  "x":230,
                  "y":482},
                "size":{
                  "width":160,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 已完工",
                      "target":{
                        "targetType":"page",
                        "url":"已完工.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/客户列表/u72.png"}},
{
          "id":"59fd01f9157a40319ed160e33bf943e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":339,
              "y":169},
            "size":{
              "width":50,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a43611ab0264283b45a0ce8c16acbd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":339,
                  "y":169},
                "size":{
                  "width":50,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u74.png"}},
{
          "id":"6392ced5b2514e8f97d2ce82cd9a790d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":169},
            "size":{
              "width":268,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49a917e965f846e6a14c6ca8addd5627",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":169},
                "size":{
                  "width":268,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u76.png"}},
{
          "id":"d548a71075a74339bcb0093ea4b70d29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":181},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fef995203b447baad0509750fffce21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":181},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6d36e2d0edd40fdb1d70cc8d0620b8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":108,
              "y":200},
            "size":{
              "width":122,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfea5032c15040e0b4f47273f4477876",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":108,
                  "y":200},
                "size":{
                  "width":122,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d79b649de8bf4a7f899be3ca3af61b06",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":177},
            "size":{
              "width":46,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d15f2ad38b945ee9c62d76a651f8c97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":177},
                "size":{
                  "width":46,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u36.png"}},
{
          "id":"32d13b8d9f9b4eedabb5cc08fa26e2ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":5,
              "y":120},
            "size":{
              "width":66,
              "height":126},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47c34ca3090c4fbd88a4e35cb13633bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":5,
                  "y":120},
                "size":{
                  "width":66,
                  "height":126},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u84.png"}},
{
          "id":"67db660f24ca49bc8f54484797b5c966",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":156},
            "size":{
              "width":10,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/客户列表/u86_line.png"}},
{
          "id":"f064ab37b87b4f499bf7a684ee3c3c44",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":325},
            "size":{
              "width":318,
              "height":157}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"96e47f3e55a84467ae5d5312944f4ff6",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"14dd614c9ea345cdbba8ec7691c2e59d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":44},
            "size":{
              "width":30,
              "height":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d107727ec8c143b7a4bd5558aef4a001",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":44},
                "size":{
                  "width":30,
                  "height":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 日程",
                      "target":{
                        "targetType":"page",
                        "url":"日程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/客户列表/u88.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e50f4734ad1242b6b2499e63c1c9b674":{
      "scriptId":"u0"},
    "6f36ad66ee4d456e9a0808077b5e97cc":{
      "scriptId":"u1"},
    "2a6298ead607485fafc158da5bdb1289":{
      "scriptId":"u2"},
    "b526f74204484c7482db92767e7fc181":{
      "scriptId":"u3"},
    "a3b426fe26894011aaaac031e20a8e5f":{
      "scriptId":"u4"},
    "ccf63a241bb94b6ba0fefa896e061226":{
      "scriptId":"u5"},
    "05791a2bf7d947e99ef8ae57b4d25467":{
      "scriptId":"u6"},
    "59c297bc5ad74a828e659edc353cf530":{
      "scriptId":"u7"},
    "77cfb08d81b34c74a72b57d8fb7ababd":{
      "scriptId":"u8"},
    "91fa4e1e5d7f4477b2d01436e188748f":{
      "scriptId":"u9"},
    "a605dce0d9154c28a33696ed1ff74e30":{
      "scriptId":"u10"},
    "e3862508e0de462b913464b148c8ed51":{
      "scriptId":"u11"},
    "357c981680954f66b924994b5db39620":{
      "scriptId":"u12"},
    "3dcdbf9ce12a440084b37482d647f3d9":{
      "scriptId":"u13"},
    "80a8916b2ae7457d98eecbcb45dd0733":{
      "scriptId":"u14"},
    "df8197f9834a487da16396068858cb0f":{
      "scriptId":"u15"},
    "594f904174cd45faaef8217a3bae7119":{
      "scriptId":"u16"},
    "cce823585dda4fbc90ffeeced1331071":{
      "scriptId":"u17"},
    "f577e9d053ca4eddb30a92a499d0a2ee":{
      "scriptId":"u18"},
    "dd0d715da76b4d63a4aa2fd932c5c080":{
      "scriptId":"u19"},
    "7e69f2b2c76d4a4ea78b53413e8ce082":{
      "scriptId":"u20"},
    "325f7b9c16594b6aa9b7517dbdba4e2c":{
      "scriptId":"u21"},
    "899fe6e7c3d54ec1852ea4439b9e07da":{
      "scriptId":"u22"},
    "665d0489f1c64a55bf1a346e94774799":{
      "scriptId":"u23"},
    "3434fa9b8c104353a41b2144ca756aa4":{
      "scriptId":"u24"},
    "7c254f89362241249e162f18f8acea3a":{
      "scriptId":"u25"},
    "51a959843a404d8bb336878545803f0e":{
      "scriptId":"u26"},
    "3706e65223e34d5d9a31d45621e53cc2":{
      "scriptId":"u27"},
    "c62793111555483ab9b545589b104ff0":{
      "scriptId":"u28"},
    "6acf125021ab4667939580735684ccd6":{
      "scriptId":"u29"},
    "dfba0c69b8b14236a01cf48113c0db68":{
      "scriptId":"u30"},
    "ac8e9a3e892a4be6b4272729c6562f8b":{
      "scriptId":"u31"},
    "dabbab12bc7847e29304cfd2d672422a":{
      "scriptId":"u32"},
    "d3081c146e6549a890f1e7c058846c85":{
      "scriptId":"u33"},
    "ad9023081645440cab13644786c95f48":{
      "scriptId":"u34"},
    "80fbff81afea49d19c1da46cd9bd815f":{
      "scriptId":"u35"},
    "42e870cd15cc42689b0b2f6525d0fc35":{
      "scriptId":"u36"},
    "b4be4d3afd38427181e8338a8c6b4772":{
      "scriptId":"u37"},
    "1e02fc5640b949a18c1d80ce657c7e50":{
      "scriptId":"u38"},
    "4dca72be8be94bf087232aff55d0b592":{
      "scriptId":"u39"},
    "8bf90ad604a14a8b9891a012aae98301":{
      "scriptId":"u40"},
    "214a62a1d9424f8980aa9091f022654d":{
      "scriptId":"u41"},
    "23b1aa3b14d14b71893aeb516d494de7":{
      "scriptId":"u42"},
    "e23e6ded27bd4a18ac9ee57082e50cb3":{
      "scriptId":"u43"},
    "d4a6e7a1310542ae9f11272ffa553f4a":{
      "scriptId":"u44"},
    "fb598067655246b2873dba3627352494":{
      "scriptId":"u45"},
    "25f7a301128645c7aa200b5460a04b2a":{
      "scriptId":"u46"},
    "3de48fe0cc7349359de0e05bb83f346d":{
      "scriptId":"u47"},
    "b1f60f37f27b42b6abf22db409d24c85":{
      "scriptId":"u48"},
    "b79b83a41ee04437b09a939756221cb0":{
      "scriptId":"u49"},
    "c691c51f63434affa0f63e44e1d781b0":{
      "scriptId":"u50"},
    "d0aa7461caa54e9d9503e3fdcc7857f7":{
      "scriptId":"u51"},
    "f22990fa848441a38805c1f0bf8410f8":{
      "scriptId":"u52"},
    "afe1f3f7ad924ea9a0181eb31580abff":{
      "scriptId":"u53"},
    "06af502c12214633b0b886c48727ce4a":{
      "scriptId":"u54"},
    "923650ed35c64924ab2b9a6253708c24":{
      "scriptId":"u55"},
    "cd5e4b5d31f64aeda1645ece6c0de449":{
      "scriptId":"u56"},
    "102066b9aa5b405cae82c4c9b02fe614":{
      "scriptId":"u57"},
    "cc808d549f924548bccf313eb7305bd2":{
      "scriptId":"u58"},
    "68c2583fe6b84b0da97a6daf9806c5e3":{
      "scriptId":"u59"},
    "13a41fda43b34fba9ebfd5b525703dda":{
      "scriptId":"u60"},
    "e27ed91655f8470181130eda687eae35":{
      "scriptId":"u61"},
    "4507bf3ed62e4b4aba75dab8c9f32ea9":{
      "scriptId":"u62"},
    "6dc5d5e17d24487aae5feeb2435a5fcd":{
      "scriptId":"u63"},
    "605798f1f74a411ea0e79bd5225ae9c1":{
      "scriptId":"u64"},
    "454701d93d844bfca83e06ca44d81850":{
      "scriptId":"u65"},
    "1e2b041433754c0db9065260cfbdb559":{
      "scriptId":"u66"},
    "8cf3d727b7e44be18345fc0db0b55a42":{
      "scriptId":"u67"},
    "f2b9791f2b674f6992687bd7bbf9b63d":{
      "scriptId":"u68"},
    "8aa05429e68047a9a460ef40c6a6d385":{
      "scriptId":"u69"},
    "aac09d64ce724d3d957adc013d096d83":{
      "scriptId":"u70"},
    "4bb2d46843a24a198d1b8efe984116ac":{
      "scriptId":"u71"},
    "361e6db32c8c4431acec5577bf0df825":{
      "scriptId":"u72"},
    "ebc7f977a8b54560aade6afa4db588d8":{
      "scriptId":"u73"},
    "59fd01f9157a40319ed160e33bf943e6":{
      "scriptId":"u74"},
    "2a43611ab0264283b45a0ce8c16acbd8":{
      "scriptId":"u75"},
    "6392ced5b2514e8f97d2ce82cd9a790d":{
      "scriptId":"u76"},
    "49a917e965f846e6a14c6ca8addd5627":{
      "scriptId":"u77"},
    "d548a71075a74339bcb0093ea4b70d29":{
      "scriptId":"u78"},
    "9fef995203b447baad0509750fffce21":{
      "scriptId":"u79"},
    "c6d36e2d0edd40fdb1d70cc8d0620b8e":{
      "scriptId":"u80"},
    "dfea5032c15040e0b4f47273f4477876":{
      "scriptId":"u81"},
    "d79b649de8bf4a7f899be3ca3af61b06":{
      "scriptId":"u82"},
    "7d15f2ad38b945ee9c62d76a651f8c97":{
      "scriptId":"u83"},
    "32d13b8d9f9b4eedabb5cc08fa26e2ba":{
      "scriptId":"u84"},
    "47c34ca3090c4fbd88a4e35cb13633bf":{
      "scriptId":"u85"},
    "67db660f24ca49bc8f54484797b5c966":{
      "scriptId":"u86"},
    "f064ab37b87b4f499bf7a684ee3c3c44":{
      "scriptId":"u87"},
    "14dd614c9ea345cdbba8ec7691c2e59d":{
      "scriptId":"u88"},
    "d107727ec8c143b7a4bd5558aef4a001":{
      "scriptId":"u89"}}});