$axure.loadCurrentPage({
  "url":"蓝景丽家.html",
  "generationDate":new Date(1415687653834.83),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a9d0b4e9f19e47c6bb390a5d6717530f",
    "type":"Axure:Page",
    "name":"蓝景丽家",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5bba13cd542b4d1982c82feeefb7c846",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":102,
              "y":11},
            "size":{
              "width":794,
              "height":1487}},
          "adaptiveStyles":{
},
          "masterId":"984fa132bdee4430802a486dd3e5c298"},
{
          "id":"5e03e2976d354d1db82f25104f1369d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":242,
              "y":530},
            "size":{
              "width":507,
              "height":274},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5963e34707f942b483c21fb50dd72238",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":242,
                  "y":530},
                "size":{
                  "width":507,
                  "height":274},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/蓝景丽家/u21.png"}},
{
          "id":"3edc43be5fce4e1cb5a370cc67b107d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"33px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF8F8F8},
            "location":{
              "x":181,
              "y":317},
            "size":{
              "width":639,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3267c13db90457b9bcd560d2b5812e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"33px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF8F8F8},
                "location":{
                  "x":181,
                  "y":317},
                "size":{
                  "width":639,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u20.png"}},
{
          "id":"f3f9e96caf594a878707328d162648de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"bold",
            "location":{
              "x":201,
              "y":341},
            "size":{
              "width":38,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30d922045d8544b2a5b6ae9082e31b5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"bold",
                "location":{
                  "x":201,
                  "y":341},
                "size":{
                  "width":38,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/装修流程/u32.png"}},
{
          "id":"fb2586436a2b4761a80f180424b5c1ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFDADADA},
            "location":{
              "x":181,
              "y":402},
            "size":{
              "width":210,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26b4595bd92a406eba9f769a144db231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDADADA},
                "location":{
                  "x":181,
                  "y":402},
                "size":{
                  "width":210,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 设计师详情,<br>设计师,<br>工长详情,<br>工长",
                      "objectsToFades":[{
                          "objectPath":["2016f0995bec43e78cbeb24438b97052"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["769cb041fcb74b3299536ed80659e68a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8e9c2ea0b66846b7a10257e7f9847bed"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["752739b772fc4e1fa68d8ed38d585f4c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/蓝景丽家/u27.png",
            "mouseDown~":"images/蓝景丽家/u27_mouseDown.png"}},
{
          "id":"03d7ed86fef24d9cac42a90a8077a1e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDADADA}}},
            "location":{
              "x":601,
              "y":402},
            "size":{
              "width":219,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a9560d7628445149e624a42ee4ba891",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFDADADA}}},
                "location":{
                  "x":601,
                  "y":402},
                "size":{
                  "width":219,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 工长",
                      "objectsToFades":[{
                          "objectPath":["752739b772fc4e1fa68d8ed38d585f4c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 设计师,<br>设计师详情,<br>工长详情",
                      "objectsToFades":[{
                          "objectPath":["769cb041fcb74b3299536ed80659e68a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2016f0995bec43e78cbeb24438b97052"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8e9c2ea0b66846b7a10257e7f9847bed"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/蓝景丽家/u29.png",
            "mouseOver~":"images/蓝景丽家/u29_mouseOver.png"}},
{
          "id":"a8d351dc83074b95af0fdcb16e8458d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDADADA}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDADADA}}},
            "location":{
              "x":391,
              "y":402},
            "size":{
              "width":210,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36a2be78100444ddb8f5710e9cb6a391",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFDADADA}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFDADADA}}},
                "location":{
                  "x":391,
                  "y":402},
                "size":{
                  "width":210,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 设计师",
                      "objectsToFades":[{
                          "objectPath":["769cb041fcb74b3299536ed80659e68a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 工长详情,<br>设计师详情,<br>工长",
                      "objectsToFades":[{
                          "objectPath":["8e9c2ea0b66846b7a10257e7f9847bed"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2016f0995bec43e78cbeb24438b97052"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["752739b772fc4e1fa68d8ed38d585f4c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/蓝景丽家/u31.png",
            "mouseOver~":"images/蓝景丽家/u27.png",
            "mouseDown~":"images/蓝景丽家/u27.png"}},
{
          "id":"769cb041fcb74b3299536ed80659e68a",
          "label":"设计师",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":181,
              "y":452},
            "size":{
              "width":639,
              "height":687},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"2a6e8c9806a34d479e1b71f987ae5d61",
              "label":"设计师",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ae4a82fe2aab43d68b4fecbf63db6625",
                  "label":"",
                  "parentDynamicPanel":"769cb041fcb74b3299536ed80659e68a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":639,
                      "height":812},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8d5a577827af4cc4913b7017f6f7b6eb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"769cb041fcb74b3299536ed80659e68a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":639,
                          "height":812},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/蓝景丽家/u34.png"}},
{
                  "id":"037151e5bf2f4328bfa42d69d59c8a74",
                  "label":"",
                  "parentDynamicPanel":"769cb041fcb74b3299536ed80659e68a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":632,
                      "height":103},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3515d4a682ce467a8ee241366ceae71d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"769cb041fcb74b3299536ed80659e68a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":632,
                          "height":103},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 设计师详情",
                              "objectsToFades":[{
                                  "objectPath":["2016f0995bec43e78cbeb24438b97052"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 工长详情,<br>工长,<br>设计师",
                              "objectsToFades":[{
                                  "objectPath":["8e9c2ea0b66846b7a10257e7f9847bed"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["752739b772fc4e1fa68d8ed38d585f4c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["769cb041fcb74b3299536ed80659e68a"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"2016f0995bec43e78cbeb24438b97052",
          "label":"设计师详情",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":181,
              "y":452},
            "size":{
              "width":639,
              "height":687},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6dcd48db79b4499abe6c4a09b6ee6c86",
              "label":"",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d693c24d10d14fa4b16ed52eee37702d",
                  "label":"",
                  "parentDynamicPanel":"2016f0995bec43e78cbeb24438b97052",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":639,
                      "height":679},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"595dcb8df6e042ab97b5a98940ce86c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2016f0995bec43e78cbeb24438b97052",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":639,
                          "height":679},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/蓝景丽家/u39.png"}},
{
                  "id":"19361ddc4f794f168a959842707e5609",
                  "label":"",
                  "parentDynamicPanel":"2016f0995bec43e78cbeb24438b97052",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-25},
                    "size":{
                      "width":639,
                      "height":818},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2d0e7e932d194d73806b285a6bf37e32",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2016f0995bec43e78cbeb24438b97052",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":-25},
                        "size":{
                          "width":639,
                          "height":818},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/蓝景丽家/u41.jpg"}}]}]},
{
          "id":"8e9c2ea0b66846b7a10257e7f9847bed",
          "label":"工长详情",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":181,
              "y":452},
            "size":{
              "width":639,
              "height":687},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"7a032e276e734ce49558e28815025f64",
              "label":"",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c1dfc04bf25f4399bdc74274bfa2cd9e",
                  "label":"",
                  "parentDynamicPanel":"8e9c2ea0b66846b7a10257e7f9847bed",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":639,
                      "height":679},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"43fa8981083b43708d7cd9e896df9e25",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8e9c2ea0b66846b7a10257e7f9847bed",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":639,
                          "height":679},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/蓝景丽家/u39.png"}},
{
                  "id":"956ff692500f40d8b480d686afc39e51",
                  "label":"",
                  "parentDynamicPanel":"8e9c2ea0b66846b7a10257e7f9847bed",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-7},
                    "size":{
                      "width":639,
                      "height":823},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ee3608cc0cb54c8a8adb9544883df46e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8e9c2ea0b66846b7a10257e7f9847bed",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":-7},
                        "size":{
                          "width":639,
                          "height":823},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/蓝景丽家/u46.jpg"}}]}]},
{
          "id":"752739b772fc4e1fa68d8ed38d585f4c",
          "label":"工长",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":181,
              "y":452},
            "size":{
              "width":639,
              "height":687},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"04ca182b9cd94acc89cdd844858499a0",
              "label":"设计师",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"088ac2655e6740708d397970d579ed5a",
                  "label":"",
                  "parentDynamicPanel":"752739b772fc4e1fa68d8ed38d585f4c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-6},
                    "size":{
                      "width":640,
                      "height":817},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4fbc01290f364603b5e816f9a9019242",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"752739b772fc4e1fa68d8ed38d585f4c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":-6},
                        "size":{
                          "width":640,
                          "height":817},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/蓝景丽家/u49.png"}},
{
                  "id":"429084bc5eda492b85e297b51e446ced",
                  "label":"",
                  "parentDynamicPanel":"752739b772fc4e1fa68d8ed38d585f4c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":7},
                    "size":{
                      "width":640,
                      "height":88},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"edd7ae2a8f444b0da7bf8a84e830b9f9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"752739b772fc4e1fa68d8ed38d585f4c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":7},
                        "size":{
                          "width":640,
                          "height":88},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 工长详情",
                              "objectsToFades":[{
                                  "objectPath":["8e9c2ea0b66846b7a10257e7f9847bed"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 设计师,<br>设计师详情,<br>工长",
                              "objectsToFades":[{
                                  "objectPath":["769cb041fcb74b3299536ed80659e68a"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["2016f0995bec43e78cbeb24438b97052"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["752739b772fc4e1fa68d8ed38d585f4c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
    "984fa132bdee4430802a486dd3e5c298":{
      "packageId":"984fa132bdee4430802a486dd3e5c298",
      "type":"Axure:Master",
      "name":"shoujixin",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0924992c31c149048016d672e5c7f726",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":794,
                "height":1487},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18279859f5f846ce8c3645a511e3061b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":794,
                    "height":1487},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u0.jpg"}},
{
            "id":"70f92109e52a40af94df453ebb3e8fd2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":307},
              "size":{
                "width":640,
                "height":822},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1a0f733bad824f2595138b3ed7ed226f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":80,
                    "y":307},
                  "size":{
                    "width":640,
                    "height":822},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u2.png"}},
{
            "id":"afaeff7a64e54c80962de48a01e9fe2c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":1129},
              "size":{
                "width":640,
                "height":97},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"74df996240be4f2eae72b660a9d138d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":80,
                    "y":1129},
                  "size":{
                    "width":640,
                    "height":97},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u4.png"}},
{
            "id":"ad28bbac596b43b58a7b09fd8c61d066",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":368,
                "y":1139},
              "size":{
                "width":39,
                "height":36},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fd172ca0c7684ee3a771250caa2a4708",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":368,
                    "y":1139},
                  "size":{
                    "width":39,
                    "height":36},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u6.png"}},
{
            "id":"00913d450cdc4fcaa0b8e0987daf0158",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":580,
                "y":1141},
              "size":{
                "width":39,
                "height":33},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"23e12321df4e4b8e918b93a4238c0b2e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":580,
                    "y":1141},
                  "size":{
                    "width":39,
                    "height":33},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u8.png"}},
{
            "id":"6aff273e7ae443acaad54ef5d53ef650",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":175,
                "y":1143},
              "size":{
                "width":38,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"895a51871df84fdeb64de494f9ded835",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":175,
                    "y":1143},
                  "size":{
                    "width":38,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u10.png"}},
{
            "id":"f64805ae112045e2acbffd535c1532ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":327,
                "y":1134},
              "size":{
                "width":123,
                "height":92},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"46456e5bf1a64ccf8f309dbbddbdde36",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":327,
                    "y":1134},
                  "size":{
                    "width":123,
                    "height":92},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"153adc10da0545eb85d07f4f4553ba83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":539,
                "y":1134},
              "size":{
                "width":123,
                "height":92},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2071049e0e8d4b418468c9a8514ed7e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":539,
                    "y":1134},
                  "size":{
                    "width":123,
                    "height":92},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登陆页",
                        "target":{
                          "targetType":"page",
                          "url":"登陆页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bb67617ebb764a5ba40a60393669df03",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":132,
                "y":1129},
              "size":{
                "width":123,
                "height":92},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"35fcb7f3ba564c56a8900c8c914f3812",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":132,
                    "y":1129},
                  "size":{
                    "width":123,
                    "height":92},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 聊天",
                        "target":{
                          "targetType":"page",
                          "url":"聊天.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ca7ebea22b8a48e9a088034eb7d63cfb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFF0000},
              "location":{
                "x":223,
                "y":1139},
              "size":{
                "width":11,
                "height":11},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24509502b78240de82bb50d987c9e129",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF0000},
                  "location":{
                    "x":223,
                    "y":1139},
                  "size":{
                    "width":11,
                    "height":11},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/确定施工方式简介/u19.png"}}]}}},
  "objectPaths":{
    "5bba13cd542b4d1982c82feeefb7c846":{
      "scriptId":"u0",
      "0924992c31c149048016d672e5c7f726":{
        "scriptId":"u1"},
      "18279859f5f846ce8c3645a511e3061b":{
        "scriptId":"u2"},
      "70f92109e52a40af94df453ebb3e8fd2":{
        "scriptId":"u3"},
      "1a0f733bad824f2595138b3ed7ed226f":{
        "scriptId":"u4"},
      "afaeff7a64e54c80962de48a01e9fe2c":{
        "scriptId":"u5"},
      "74df996240be4f2eae72b660a9d138d3":{
        "scriptId":"u6"},
      "ad28bbac596b43b58a7b09fd8c61d066":{
        "scriptId":"u7"},
      "fd172ca0c7684ee3a771250caa2a4708":{
        "scriptId":"u8"},
      "00913d450cdc4fcaa0b8e0987daf0158":{
        "scriptId":"u9"},
      "23e12321df4e4b8e918b93a4238c0b2e":{
        "scriptId":"u10"},
      "6aff273e7ae443acaad54ef5d53ef650":{
        "scriptId":"u11"},
      "895a51871df84fdeb64de494f9ded835":{
        "scriptId":"u12"},
      "f64805ae112045e2acbffd535c1532ea":{
        "scriptId":"u13"},
      "46456e5bf1a64ccf8f309dbbddbdde36":{
        "scriptId":"u14"},
      "153adc10da0545eb85d07f4f4553ba83":{
        "scriptId":"u15"},
      "2071049e0e8d4b418468c9a8514ed7e2":{
        "scriptId":"u16"},
      "bb67617ebb764a5ba40a60393669df03":{
        "scriptId":"u17"},
      "35fcb7f3ba564c56a8900c8c914f3812":{
        "scriptId":"u18"},
      "ca7ebea22b8a48e9a088034eb7d63cfb":{
        "scriptId":"u19"},
      "24509502b78240de82bb50d987c9e129":{
        "scriptId":"u20"}},
    "5e03e2976d354d1db82f25104f1369d5":{
      "scriptId":"u21"},
    "5963e34707f942b483c21fb50dd72238":{
      "scriptId":"u22"},
    "3edc43be5fce4e1cb5a370cc67b107d5":{
      "scriptId":"u23"},
    "e3267c13db90457b9bcd560d2b5812e2":{
      "scriptId":"u24"},
    "f3f9e96caf594a878707328d162648de":{
      "scriptId":"u25"},
    "30d922045d8544b2a5b6ae9082e31b5d":{
      "scriptId":"u26"},
    "fb2586436a2b4761a80f180424b5c1ff":{
      "scriptId":"u27"},
    "26b4595bd92a406eba9f769a144db231":{
      "scriptId":"u28"},
    "03d7ed86fef24d9cac42a90a8077a1e0":{
      "scriptId":"u29"},
    "8a9560d7628445149e624a42ee4ba891":{
      "scriptId":"u30"},
    "a8d351dc83074b95af0fdcb16e8458d8":{
      "scriptId":"u31"},
    "36a2be78100444ddb8f5710e9cb6a391":{
      "scriptId":"u32"},
    "769cb041fcb74b3299536ed80659e68a":{
      "scriptId":"u33"},
    "ae4a82fe2aab43d68b4fecbf63db6625":{
      "scriptId":"u34"},
    "8d5a577827af4cc4913b7017f6f7b6eb":{
      "scriptId":"u35"},
    "037151e5bf2f4328bfa42d69d59c8a74":{
      "scriptId":"u36"},
    "3515d4a682ce467a8ee241366ceae71d":{
      "scriptId":"u37"},
    "2016f0995bec43e78cbeb24438b97052":{
      "scriptId":"u38"},
    "d693c24d10d14fa4b16ed52eee37702d":{
      "scriptId":"u39"},
    "595dcb8df6e042ab97b5a98940ce86c0":{
      "scriptId":"u40"},
    "19361ddc4f794f168a959842707e5609":{
      "scriptId":"u41"},
    "2d0e7e932d194d73806b285a6bf37e32":{
      "scriptId":"u42"},
    "8e9c2ea0b66846b7a10257e7f9847bed":{
      "scriptId":"u43"},
    "c1dfc04bf25f4399bdc74274bfa2cd9e":{
      "scriptId":"u44"},
    "43fa8981083b43708d7cd9e896df9e25":{
      "scriptId":"u45"},
    "956ff692500f40d8b480d686afc39e51":{
      "scriptId":"u46"},
    "ee3608cc0cb54c8a8adb9544883df46e":{
      "scriptId":"u47"},
    "752739b772fc4e1fa68d8ed38d585f4c":{
      "scriptId":"u48"},
    "088ac2655e6740708d397970d579ed5a":{
      "scriptId":"u49"},
    "4fbc01290f364603b5e816f9a9019242":{
      "scriptId":"u50"},
    "429084bc5eda492b85e297b51e446ced":{
      "scriptId":"u51"},
    "edd7ae2a8f444b0da7bf8a84e830b9f9":{
      "scriptId":"u52"}}});