$axure.loadCurrentPage({
  "url":"收藏列表.html",
  "generationDate":new Date(1417588019905.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b5d504f358774d9cab0a54fda4021eb1",
    "type":"Axure:Page",
    "name":"收藏列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"212ab1d2bfa446e7a4eb2dc9db20920f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":353,
              "height":26},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eed704299b7c4511b94cda2166bda127",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":353,
                  "height":26},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天界面/u2.png"}},
{
          "id":"eba81b1311bc4045bff846065c18269e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":399,
              "height":35},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e19a1edf96d4c4980900768bc9d5802",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":26},
                "size":{
                  "width":399,
                  "height":35},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏列表/u2.png"}},
{
          "id":"50c2c673eff148d9ad31f9ab32948fad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":353,
              "y":0},
            "size":{
              "width":47,
              "height":26},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0f7f964cd6646a0bb80fbb48a41c753",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":353,
                  "y":0},
                "size":{
                  "width":47,
                  "height":26},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天界面/u4.png"}},
{
          "id":"3efc2fc418834b0aa14a52afaaf2363b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":353,
              "y":61},
            "size":{
              "width":47,
              "height":573},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"367f262defd7405fb8cbcc17e9e8e9aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":353,
                  "y":61},
                "size":{
                  "width":47,
                  "height":573},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天界面/u8.png"}},
{
          "id":"b6a16275af4a4180ab41839ae1df624f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":399,
              "y":26},
            "size":{
              "width":1,
              "height":35},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6e0caef5b604cfdbf088c0e6bbcda58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":399,
                  "y":26},
                "size":{
                  "width":1,
                  "height":35},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天界面/u10.png"}},
{
          "id":"e1cf2f8ef7b448718bd3232621ea81c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":399,
              "y":61},
            "size":{
              "width":1,
              "height":573},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"113ab5dd52974bdf958424bd604901fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":399,
                  "y":61},
                "size":{
                  "width":1,
                  "height":573},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天界面/u12.png"}},
{
          "id":"b0f7a0ea45f44fbe8577b2633bb65cc0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":399,
              "y":0},
            "size":{
              "width":1,
              "height":26},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f362ecc00ae4253b3ae56ae155d31c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":399,
                  "y":0},
                "size":{
                  "width":1,
                  "height":26},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天界面/u14.png"}},
{
          "id":"dbcefbbd1ccb40e68ed3985386866a42",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":61},
            "size":{
              "width":353,
              "height":573},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11b7103191204e0fad43de475a89b00b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":61},
                "size":{
                  "width":353,
                  "height":573},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天界面/u16.png"}},
{
          "id":"785dcba4efad4808b42415f1a5418f44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "location":{
              "x":1,
              "y":62},
            "size":{
              "width":399,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99134bc8f016488b9ae1ea89db2acb82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "location":{
                  "x":1,
                  "y":62},
                "size":{
                  "width":399,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏列表/u16.png"}},
{
          "id":"9c0a6dfc696c4a75a7dc17c9569452ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF454B57},
            "location":{
              "x":74,
              "y":26},
            "size":{
              "width":231,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f8ae11b2c93486d84c840cefd384256",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF454B57},
                "location":{
                  "x":74,
                  "y":26},
                "size":{
                  "width":231,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏列表/u18.png"}},
{
          "id":"cb450c99d016432892c606fcdd5b9c4a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":40},
            "size":{
              "width":14,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/收藏列表/u20_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/收藏列表/u20_line.png"}},
{
          "id":"a78cd05efc0b4ba79ee7424ddd697295",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":169},
            "size":{
              "width":399,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xCEFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/收藏列表/u21_line.png"}},
{
          "id":"9c196dfdd7ae430b9cace64b7947fdcd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":535},
            "size":{
              "width":399,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xCEFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/收藏列表/u21_line.png"}},
{
          "id":"43a58dfc8e6849a1bfe81ed33ed8ada2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":291},
            "size":{
              "width":399,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xCEFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/收藏列表/u21_line.png"}},
{
          "id":"5ee6ec6d7448425d8821d5100c85f917",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":46,
              "y":76},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5a0ea83568442c0a60ff459fab947ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":46,
                  "y":76},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d25d15acc3db43c98b003ed7070f3c19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":367,
              "y":76},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7670a81341441d6a2886dafe861ead6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":367,
                  "y":76},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f4f81f407c3443794b8f26b187784d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":47,
              "y":121},
            "size":{
              "width":225,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bc93f96c3b547fda8356a9f098b6a2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":47,
                  "y":121},
                "size":{
                  "width":225,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d800ad6a31324783b75be5dcd7e4077f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":72},
            "size":{
              "width":27,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"036fb6cfadd740a9a88aeff81e70d4ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":72},
                "size":{
                  "width":27,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏列表/u30.png"}},
{
          "id":"6a9ae9ae4c914ec899fbb9ac136ccdf4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":72},
            "size":{
              "width":27,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a281d070b2e47bf80809eda4f2454a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":72},
                "size":{
                  "width":27,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏列表/u32.png"}},
{
          "id":"38d28769f29846af853f474cd0a2b973",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":46,
              "y":316},
            "size":{
              "width":40,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"823211ac60e34804b7444ae98abe1c92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":46,
                  "y":316},
                "size":{
                  "width":40,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fdbab739c244f60b73d5e6807228c91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":332,
              "y":316},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fd37ac28da64288a29b68987e5f3c36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":332,
                  "y":316},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a9e3f6b1d2c4fb3980c46710164b722",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":313},
            "size":{
              "width":27,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4068372e9ac5495a9df3f29ed683f8ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":313},
                "size":{
                  "width":27,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏列表/u30.png"}},
{
          "id":"a0299f081b8045b5a7cbb8cb301b1671",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":312},
            "size":{
              "width":27,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac306dd1257f4ee88635148310a42cef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":312},
                "size":{
                  "width":27,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏列表/u32.png"}},
{
          "id":"e56e8e9eaf634e8c9b4b38f7d673c22d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":46,
              "y":205},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7057d0c5dad842ca9a77c3038c80c792",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":46,
                  "y":205},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5e7daf5e457436c9a0a2e7a65e494eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":333,
              "y":205},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42365463079249a982d4a77109b59b90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":333,
                  "y":205},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1f96873ab7d41babb4c282f08b45ec8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":201},
            "size":{
              "width":27,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be2fb991a913417da9c17ddac5583f3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":201},
                "size":{
                  "width":27,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏列表/u30.png"}},
{
          "id":"ac44c491d40043abbe041d3b8d4f3c55",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":201},
            "size":{
              "width":27,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8341bcbea43443a5ac36079eeb43d335",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":201},
                "size":{
                  "width":27,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏列表/u32.png"}},
{
          "id":"6dd86ce2170e4e1d8885b9660cbc5cc2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":340},
            "size":{
              "width":168,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a3d702699204b12a851efef48a16d4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":340},
                "size":{
                  "width":168,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏列表/u50.jpg"}},
{
          "id":"efd6628cf5bc46c7a08dd6305478554d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":229},
            "size":{
              "width":163,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17fde153244a411d9719839fd1813044",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":229},
                "size":{
                  "width":163,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏列表/u52.png"}},
{
          "id":"b265cfac345c47c3be00a2559d9045bb",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天界面",
                      "target":{
                        "targetType":"page",
                        "url":"聊天界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c685f19c927e4557aaa8f7841b1d59b0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":411},
            "size":{
              "width":399,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xCEFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/收藏列表/u21_line.png"}},
{
          "id":"240e80fbe45149a7a5a38d8ab3f13ec1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":41,
              "y":434},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c41b98821d5f4d92b068fd39a4ae4507",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":434},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d54dda2b0c84ef29bebd03fe63c01a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":333,
              "y":434},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c02b46a4d2649c9a7c91871ee373ae8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":333,
                  "y":434},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31f58a454fad43bc923af02fa8147e16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":42,
              "y":479},
            "size":{
              "width":337,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d15ceee7d7884ec3b504878a26af80d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":42,
                  "y":479},
                "size":{
                  "width":337,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ca6d4fa81dd42e08817fb923ffc8157",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":430},
            "size":{
              "width":27,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e26c58024121433688b736b0cc8990d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":430},
                "size":{
                  "width":27,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏列表/u32.png"}},
{
          "id":"4e14f36db8d84a38a242bb90aaabf0bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":35,
              "y":553},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2363782a80045baa82683547cda4ffd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":35,
                  "y":553},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8fa66f62c9d4067879baf39180c4d16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":327,
              "y":553},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5d6d893f7ff410aa0dd3453f6099196",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":327,
                  "y":553},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3dc17ec054084dcabd0fd3470c540f45",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":36,
              "y":590},
            "size":{
              "width":225,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e44c712679340debc63280a8a2b7242",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":36,
                  "y":590},
                "size":{
                  "width":225,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c535dfba20304857a24b8d2490ab45e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":5,
              "y":549},
            "size":{
              "width":27,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02ed1981e2eb42f5a7cdfd05cf084a87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":5,
                  "y":549},
                "size":{
                  "width":27,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏列表/u32.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "212ab1d2bfa446e7a4eb2dc9db20920f":{
      "scriptId":"u0"},
    "eed704299b7c4511b94cda2166bda127":{
      "scriptId":"u1"},
    "eba81b1311bc4045bff846065c18269e":{
      "scriptId":"u2"},
    "4e19a1edf96d4c4980900768bc9d5802":{
      "scriptId":"u3"},
    "50c2c673eff148d9ad31f9ab32948fad":{
      "scriptId":"u4"},
    "d0f7f964cd6646a0bb80fbb48a41c753":{
      "scriptId":"u5"},
    "3efc2fc418834b0aa14a52afaaf2363b":{
      "scriptId":"u6"},
    "367f262defd7405fb8cbcc17e9e8e9aa":{
      "scriptId":"u7"},
    "b6a16275af4a4180ab41839ae1df624f":{
      "scriptId":"u8"},
    "a6e0caef5b604cfdbf088c0e6bbcda58":{
      "scriptId":"u9"},
    "e1cf2f8ef7b448718bd3232621ea81c1":{
      "scriptId":"u10"},
    "113ab5dd52974bdf958424bd604901fb":{
      "scriptId":"u11"},
    "b0f7a0ea45f44fbe8577b2633bb65cc0":{
      "scriptId":"u12"},
    "3f362ecc00ae4253b3ae56ae155d31c6":{
      "scriptId":"u13"},
    "dbcefbbd1ccb40e68ed3985386866a42":{
      "scriptId":"u14"},
    "11b7103191204e0fad43de475a89b00b":{
      "scriptId":"u15"},
    "785dcba4efad4808b42415f1a5418f44":{
      "scriptId":"u16"},
    "99134bc8f016488b9ae1ea89db2acb82":{
      "scriptId":"u17"},
    "9c0a6dfc696c4a75a7dc17c9569452ac":{
      "scriptId":"u18"},
    "5f8ae11b2c93486d84c840cefd384256":{
      "scriptId":"u19"},
    "cb450c99d016432892c606fcdd5b9c4a":{
      "scriptId":"u20"},
    "a78cd05efc0b4ba79ee7424ddd697295":{
      "scriptId":"u21"},
    "9c196dfdd7ae430b9cace64b7947fdcd":{
      "scriptId":"u22"},
    "43a58dfc8e6849a1bfe81ed33ed8ada2":{
      "scriptId":"u23"},
    "5ee6ec6d7448425d8821d5100c85f917":{
      "scriptId":"u24"},
    "e5a0ea83568442c0a60ff459fab947ba":{
      "scriptId":"u25"},
    "d25d15acc3db43c98b003ed7070f3c19":{
      "scriptId":"u26"},
    "d7670a81341441d6a2886dafe861ead6":{
      "scriptId":"u27"},
    "9f4f81f407c3443794b8f26b187784d8":{
      "scriptId":"u28"},
    "1bc93f96c3b547fda8356a9f098b6a2d":{
      "scriptId":"u29"},
    "d800ad6a31324783b75be5dcd7e4077f":{
      "scriptId":"u30"},
    "036fb6cfadd740a9a88aeff81e70d4ab":{
      "scriptId":"u31"},
    "6a9ae9ae4c914ec899fbb9ac136ccdf4":{
      "scriptId":"u32"},
    "7a281d070b2e47bf80809eda4f2454a6":{
      "scriptId":"u33"},
    "38d28769f29846af853f474cd0a2b973":{
      "scriptId":"u34"},
    "823211ac60e34804b7444ae98abe1c92":{
      "scriptId":"u35"},
    "0fdbab739c244f60b73d5e6807228c91":{
      "scriptId":"u36"},
    "4fd37ac28da64288a29b68987e5f3c36":{
      "scriptId":"u37"},
    "7a9e3f6b1d2c4fb3980c46710164b722":{
      "scriptId":"u38"},
    "4068372e9ac5495a9df3f29ed683f8ae":{
      "scriptId":"u39"},
    "a0299f081b8045b5a7cbb8cb301b1671":{
      "scriptId":"u40"},
    "ac306dd1257f4ee88635148310a42cef":{
      "scriptId":"u41"},
    "e56e8e9eaf634e8c9b4b38f7d673c22d":{
      "scriptId":"u42"},
    "7057d0c5dad842ca9a77c3038c80c792":{
      "scriptId":"u43"},
    "d5e7daf5e457436c9a0a2e7a65e494eb":{
      "scriptId":"u44"},
    "42365463079249a982d4a77109b59b90":{
      "scriptId":"u45"},
    "a1f96873ab7d41babb4c282f08b45ec8":{
      "scriptId":"u46"},
    "be2fb991a913417da9c17ddac5583f3d":{
      "scriptId":"u47"},
    "ac44c491d40043abbe041d3b8d4f3c55":{
      "scriptId":"u48"},
    "8341bcbea43443a5ac36079eeb43d335":{
      "scriptId":"u49"},
    "6dd86ce2170e4e1d8885b9660cbc5cc2":{
      "scriptId":"u50"},
    "3a3d702699204b12a851efef48a16d4f":{
      "scriptId":"u51"},
    "efd6628cf5bc46c7a08dd6305478554d":{
      "scriptId":"u52"},
    "17fde153244a411d9719839fd1813044":{
      "scriptId":"u53"},
    "b265cfac345c47c3be00a2559d9045bb":{
      "scriptId":"u54"},
    "c685f19c927e4557aaa8f7841b1d59b0":{
      "scriptId":"u55"},
    "240e80fbe45149a7a5a38d8ab3f13ec1":{
      "scriptId":"u56"},
    "c41b98821d5f4d92b068fd39a4ae4507":{
      "scriptId":"u57"},
    "4d54dda2b0c84ef29bebd03fe63c01a4":{
      "scriptId":"u58"},
    "3c02b46a4d2649c9a7c91871ee373ae8":{
      "scriptId":"u59"},
    "31f58a454fad43bc923af02fa8147e16":{
      "scriptId":"u60"},
    "d15ceee7d7884ec3b504878a26af80d1":{
      "scriptId":"u61"},
    "3ca6d4fa81dd42e08817fb923ffc8157":{
      "scriptId":"u62"},
    "e26c58024121433688b736b0cc8990d6":{
      "scriptId":"u63"},
    "4e14f36db8d84a38a242bb90aaabf0bd":{
      "scriptId":"u64"},
    "a2363782a80045baa82683547cda4ffd":{
      "scriptId":"u65"},
    "c8fa66f62c9d4067879baf39180c4d16":{
      "scriptId":"u66"},
    "e5d6d893f7ff410aa0dd3453f6099196":{
      "scriptId":"u67"},
    "3dc17ec054084dcabd0fd3470c540f45":{
      "scriptId":"u68"},
    "5e44c712679340debc63280a8a2b7242":{
      "scriptId":"u69"},
    "c535dfba20304857a24b8d2490ab45e3":{
      "scriptId":"u70"},
    "02ed1981e2eb42f5a7cdfd05cf084a87":{
      "scriptId":"u71"}}});