$axure.loadCurrentPage({
  "url":"聊天.html",
  "generationDate":new Date(1417673125645.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dbc8ff45bbf444699af0e6415407c1af",
    "type":"Axure:Page",
    "name":"聊天",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"29d8eae9e86b47ad85b9e832083f5f91",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":15},
            "size":{
              "width":302,
              "height":475}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3d1f5da457d442ca08ba08689cca41d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":15},
                "size":{
                  "width":302,
                  "height":475}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u0.png"}},
{
          "id":"a8b652e4f2c645418340ffc0404346ed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":107.5,
              "y":103},
            "size":{
              "width":287,
              "height":317}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb3a0cbe2b3042a6a40c7d48f38f0d4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":107.5,
                  "y":103},
                "size":{
                  "width":287,
                  "height":317}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u2.png"}},
{
          "id":"f0f6796106f6425f9073f5933f89aeb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":100,
              "y":63},
            "size":{
              "width":300,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b136befa820416b8528134ae921cc3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":100,
                  "y":63},
                "size":{
                  "width":300,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天/u4.png"}},
{
          "id":"7effbbc187b943ff9d7eb686e3c12cc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":108,
              "y":140},
            "size":{
              "width":62,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a64d3dfac7f342a89386b02c272e292d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":108,
                  "y":140},
                "size":{
                  "width":62,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 客户个人信息",
                      "target":{
                        "targetType":"page",
                        "url":"客户个人信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99d325e1cae14d31ab27c0338c3af21e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":108,
              "y":37},
            "size":{
              "width":32,
              "height":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaf1cd5ce71c4ac28ab4c22835d067ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":108,
                  "y":37},
                "size":{
                  "width":32,
                  "height":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 2",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全部客户",
                      "target":{
                        "targetType":"page",
                        "url":"全部客户.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "29d8eae9e86b47ad85b9e832083f5f91":{
      "scriptId":"u0"},
    "d3d1f5da457d442ca08ba08689cca41d":{
      "scriptId":"u1"},
    "a8b652e4f2c645418340ffc0404346ed":{
      "scriptId":"u2"},
    "eb3a0cbe2b3042a6a40c7d48f38f0d4f":{
      "scriptId":"u3"},
    "f0f6796106f6425f9073f5933f89aeb5":{
      "scriptId":"u4"},
    "5b136befa820416b8528134ae921cc3b":{
      "scriptId":"u5"},
    "7effbbc187b943ff9d7eb686e3c12cc5":{
      "scriptId":"u6"},
    "a64d3dfac7f342a89386b02c272e292d":{
      "scriptId":"u7"},
    "99d325e1cae14d31ab27c0338c3af21e":{
      "scriptId":"u8"},
    "aaf1cd5ce71c4ac28ab4c22835d067ac":{
      "scriptId":"u9"}}});