$axure.loadCurrentPage({
  "url":"已完工.html",
  "generationDate":new Date(1416883964114.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"229fe7f6a5684a9fa57c8bba934ec6ee",
    "type":"Axure:Page",
    "name":"已完工",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"39090e407f514b7dbd88b1597b2f0156",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":30},
            "size":{
              "width":320,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e72745642fc44ab92d4ad66f0c67999",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":30},
                "size":{
                  "width":320,
                  "height":495}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u0.png"}},
{
          "id":"bd21b2e128e24650b387abf9194a15c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":70,
              "y":30},
            "size":{
              "width":320,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6684ec3aa584ec7b468fbc098f282f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":70,
                  "y":30},
                "size":{
                  "width":320,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u2.png"}},
{
          "id":"20612891b571491aacaeebf33b75c23b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":39},
            "size":{
              "width":30,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bea14f414cb3477ba26df413f072e54c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":39},
                "size":{
                  "width":30,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设计师信息页",
                      "target":{
                        "targetType":"page",
                        "url":"设计师信息页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/客户列表/u4.png"}},
{
          "id":"7913aa07f28144e39caff6839b43428b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":70,
              "y":80},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b09fae8552b044ab86fd32f0fbe19956",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":70,
                  "y":80},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u6.png"}},
{
          "id":"88f250625a6f4c80a6526cc84de5f168",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":86},
            "size":{
              "width":260,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eab7004ae0e74c0f88a89900e05918f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":86},
                "size":{
                  "width":260,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u8.png"}},
{
          "id":"cc2c2da3173b4a6aa05e67aeb7e16fcc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":93},
            "size":{
              "width":12,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4082c2a0100048f4b57d31987621a85f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":93},
                "size":{
                  "width":12,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u10.png"}},
{
          "id":"b7dd40596f2d425db7ac4b81a83f211a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":118},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"951c77a6cf3c4ff3bdb52919b1b58860",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":118},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天",
                      "target":{
                        "targetType":"page",
                        "url":"聊天.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/客户列表/u12.png"}},
{
          "id":"f3c600e76b2646f6b602b4b8d62cb014",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":125},
            "size":{
              "width":46,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f52baf31ae34d47887b309f58567b05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":125},
                "size":{
                  "width":46,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u14.png"}},
{
          "id":"d83e09fd7e0c4188a82d70f4a8170f36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":130},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12865c9b2409478dadb77829deda6aa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":130},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eaac6293c13740cb9bb9eba4fb685b91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":158,
              "y":149},
            "size":{
              "width":133,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"454e99d680234bd2a6212a82fbf21a5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":158,
                  "y":149},
                "size":{
                  "width":133,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e6ebc7d0e824771b4e0194f5dc9f5e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":168},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3e2a135366246ae99527a2099cb567f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":168},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u12.png"}},
{
          "id":"2defd3d5bfbb40949c3731ffb20096a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":180},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d30f2f534c8546c39bccdf760db781ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":180},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80bb559e49184f94aab9a0bd48c07905",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":158,
              "y":199},
            "size":{
              "width":122,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a635f02e0b44130aba4828fce40fe37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":158,
                  "y":199},
                "size":{
                  "width":122,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"989ff9797eac4e93ac3dfcb237428fd9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":176},
            "size":{
              "width":46,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe68a3da6597418d9fd2d41eac89d42c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":176},
                "size":{
                  "width":46,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u36.png"}},
{
          "id":"31e9e9446b6e42e0ba5caa55933c3cc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":218},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"387e638a52c44ba1932472bfb8a3e3ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":218},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u12.png"}},
{
          "id":"373a48299cdc431fa3be347c98c4a143",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":225},
            "size":{
              "width":46,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"507db13a2b2146f3bab1f98ea85b5585",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":225},
                "size":{
                  "width":46,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u14.png"}},
{
          "id":"b47c696ca61c48b3a0bca6cd96d01ab2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":230},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b6261ceab0f4e8b947bfb43c48c6d0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":230},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efe4258862d2436293b55560f0a787d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":158,
              "y":249},
            "size":{
              "width":133,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f44599fed6694f62b6c6ef8c9e4a3fca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":158,
                  "y":249},
                "size":{
                  "width":133,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bebc3c3ca2494992853270b52d370b55",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":268},
            "size":{
              "width":318,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69a8174a725a4ab99767d68b8dab177f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":268},
                "size":{
                  "width":318,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u12.png"}},
{
          "id":"b31fa982b6e94c9da022f564a223f9e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":280},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ff07388e5e549238a4b8800cffb650b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":280},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a052a6a2d1c24cf4a4d73e280a4d619a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":158,
              "y":299},
            "size":{
              "width":122,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94eb9178dac94cb49d6ecab09bfe3671",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":158,
                  "y":299},
                "size":{
                  "width":122,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"767fda134b2f4dd7a74fafc8e3bd3e4e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":276},
            "size":{
              "width":46,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"409dd2bff0594da6b9fd625b3ba61e96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":276},
                "size":{
                  "width":46,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u36.png"}},
{
          "id":"e8d7ef0c323243b3ae2a028d04195737",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF949494},
            "location":{
              "x":70,
              "y":482},
            "size":{
              "width":160,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96bd2b3db9064ebfa99d8377c4e6173e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "location":{
                  "x":70,
                  "y":482},
                "size":{
                  "width":160,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 客户列表",
                      "target":{
                        "targetType":"page",
                        "url":"客户列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/客户列表/u72.png"}},
{
          "id":"7163c40c4f974a188127bb02a6faf41d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":230,
              "y":482},
            "size":{
              "width":160,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37d25297808743089695a699b805f1c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":230,
                  "y":482},
                "size":{
                  "width":160,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u70.png"}},
{
          "id":"7be3a618a3ec4a2ab3feda94ada3bf59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":338,
              "y":167},
            "size":{
              "width":50,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10bc8095096642df8c60fc9c322d3ee7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":338,
                  "y":167},
                "size":{
                  "width":50,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u74.png"}},
{
          "id":"cb800aa5a6054a2bb47bed1fbd2e92c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":167},
            "size":{
              "width":268,
              "height":52},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d91c3605c31841e1ace4a809f6a8d21d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":167},
                "size":{
                  "width":268,
                  "height":52},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u76.png"}},
{
          "id":"764718d692f148088bdcb0fb69424985",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":179},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33e641c1f197488794e6901c55c2a183",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":179},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0dbe800ccf04b1982189aad4b269629",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":108,
              "y":198},
            "size":{
              "width":122,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c360c52eb2fa418290c205e76d0338f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":108,
                  "y":198},
                "size":{
                  "width":122,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3f8746f7bae4430b6e703be93638e5c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":175},
            "size":{
              "width":46,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e26df97fbda64a65ae89a1a57468c873",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":175},
                "size":{
                  "width":46,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u36.png"}},
{
          "id":"52556b18c96044f59fbbbaa49422cbc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":118},
            "size":{
              "width":66,
              "height":126},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce2ec39fd5ff40af9bd9be1d621f7c34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":118},
                "size":{
                  "width":66,
                  "height":126},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户列表/u84.png"}},
{
          "id":"0b73a3308bea4b9cada008035fa11766",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":125},
            "size":{
              "width":10,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/客户列表/u86_line.png"}},
{
          "id":"ff59f04ad378460089c75527f9c4a4a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":44},
            "size":{
              "width":30,
              "height":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46c619c68345427f975ec05ea63f13b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":44},
                "size":{
                  "width":30,
                  "height":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 日程",
                      "target":{
                        "targetType":"page",
                        "url":"日程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/客户列表/u88.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "39090e407f514b7dbd88b1597b2f0156":{
      "scriptId":"u0"},
    "2e72745642fc44ab92d4ad66f0c67999":{
      "scriptId":"u1"},
    "bd21b2e128e24650b387abf9194a15c8":{
      "scriptId":"u2"},
    "a6684ec3aa584ec7b468fbc098f282f1":{
      "scriptId":"u3"},
    "20612891b571491aacaeebf33b75c23b":{
      "scriptId":"u4"},
    "bea14f414cb3477ba26df413f072e54c":{
      "scriptId":"u5"},
    "7913aa07f28144e39caff6839b43428b":{
      "scriptId":"u6"},
    "b09fae8552b044ab86fd32f0fbe19956":{
      "scriptId":"u7"},
    "88f250625a6f4c80a6526cc84de5f168":{
      "scriptId":"u8"},
    "eab7004ae0e74c0f88a89900e05918f5":{
      "scriptId":"u9"},
    "cc2c2da3173b4a6aa05e67aeb7e16fcc":{
      "scriptId":"u10"},
    "4082c2a0100048f4b57d31987621a85f":{
      "scriptId":"u11"},
    "b7dd40596f2d425db7ac4b81a83f211a":{
      "scriptId":"u12"},
    "951c77a6cf3c4ff3bdb52919b1b58860":{
      "scriptId":"u13"},
    "f3c600e76b2646f6b602b4b8d62cb014":{
      "scriptId":"u14"},
    "1f52baf31ae34d47887b309f58567b05":{
      "scriptId":"u15"},
    "d83e09fd7e0c4188a82d70f4a8170f36":{
      "scriptId":"u16"},
    "12865c9b2409478dadb77829deda6aa5":{
      "scriptId":"u17"},
    "eaac6293c13740cb9bb9eba4fb685b91":{
      "scriptId":"u18"},
    "454e99d680234bd2a6212a82fbf21a5b":{
      "scriptId":"u19"},
    "3e6ebc7d0e824771b4e0194f5dc9f5e3":{
      "scriptId":"u20"},
    "a3e2a135366246ae99527a2099cb567f":{
      "scriptId":"u21"},
    "2defd3d5bfbb40949c3731ffb20096a7":{
      "scriptId":"u22"},
    "d30f2f534c8546c39bccdf760db781ce":{
      "scriptId":"u23"},
    "80bb559e49184f94aab9a0bd48c07905":{
      "scriptId":"u24"},
    "4a635f02e0b44130aba4828fce40fe37":{
      "scriptId":"u25"},
    "989ff9797eac4e93ac3dfcb237428fd9":{
      "scriptId":"u26"},
    "fe68a3da6597418d9fd2d41eac89d42c":{
      "scriptId":"u27"},
    "31e9e9446b6e42e0ba5caa55933c3cc2":{
      "scriptId":"u28"},
    "387e638a52c44ba1932472bfb8a3e3ad":{
      "scriptId":"u29"},
    "373a48299cdc431fa3be347c98c4a143":{
      "scriptId":"u30"},
    "507db13a2b2146f3bab1f98ea85b5585":{
      "scriptId":"u31"},
    "b47c696ca61c48b3a0bca6cd96d01ab2":{
      "scriptId":"u32"},
    "1b6261ceab0f4e8b947bfb43c48c6d0c":{
      "scriptId":"u33"},
    "efe4258862d2436293b55560f0a787d1":{
      "scriptId":"u34"},
    "f44599fed6694f62b6c6ef8c9e4a3fca":{
      "scriptId":"u35"},
    "bebc3c3ca2494992853270b52d370b55":{
      "scriptId":"u36"},
    "69a8174a725a4ab99767d68b8dab177f":{
      "scriptId":"u37"},
    "b31fa982b6e94c9da022f564a223f9e3":{
      "scriptId":"u38"},
    "4ff07388e5e549238a4b8800cffb650b":{
      "scriptId":"u39"},
    "a052a6a2d1c24cf4a4d73e280a4d619a":{
      "scriptId":"u40"},
    "94eb9178dac94cb49d6ecab09bfe3671":{
      "scriptId":"u41"},
    "767fda134b2f4dd7a74fafc8e3bd3e4e":{
      "scriptId":"u42"},
    "409dd2bff0594da6b9fd625b3ba61e96":{
      "scriptId":"u43"},
    "e8d7ef0c323243b3ae2a028d04195737":{
      "scriptId":"u44"},
    "96bd2b3db9064ebfa99d8377c4e6173e":{
      "scriptId":"u45"},
    "7163c40c4f974a188127bb02a6faf41d":{
      "scriptId":"u46"},
    "37d25297808743089695a699b805f1c1":{
      "scriptId":"u47"},
    "7be3a618a3ec4a2ab3feda94ada3bf59":{
      "scriptId":"u48"},
    "10bc8095096642df8c60fc9c322d3ee7":{
      "scriptId":"u49"},
    "cb800aa5a6054a2bb47bed1fbd2e92c6":{
      "scriptId":"u50"},
    "d91c3605c31841e1ace4a809f6a8d21d":{
      "scriptId":"u51"},
    "764718d692f148088bdcb0fb69424985":{
      "scriptId":"u52"},
    "33e641c1f197488794e6901c55c2a183":{
      "scriptId":"u53"},
    "e0dbe800ccf04b1982189aad4b269629":{
      "scriptId":"u54"},
    "c360c52eb2fa418290c205e76d0338f2":{
      "scriptId":"u55"},
    "d3f8746f7bae4430b6e703be93638e5c":{
      "scriptId":"u56"},
    "e26df97fbda64a65ae89a1a57468c873":{
      "scriptId":"u57"},
    "52556b18c96044f59fbbbaa49422cbc0":{
      "scriptId":"u58"},
    "ce2ec39fd5ff40af9bd9be1d621f7c34":{
      "scriptId":"u59"},
    "0b73a3308bea4b9cada008035fa11766":{
      "scriptId":"u60"},
    "ff59f04ad378460089c75527f9c4a4a9":{
      "scriptId":"u61"},
    "46c619c68345427f975ec05ea63f13b4":{
      "scriptId":"u62"}}});