$axure.loadCurrentPage({
  "url":"隐私声明.html",
  "generationDate":new Date(1417588020358.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3dbd3d33f3af49358456b7158ab35db8",
    "type":"Axure:Page",
    "name":"隐私声明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"169200fac2e1410b88047f7af4a5cee2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":400,
              "height":538},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3df9305e6bd4a6fabb465e024b5a83d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":26},
                "size":{
                  "width":400,
                  "height":538},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/隐私声明/u0.png"}},
{
          "id":"5fd8db4ec750414f83e48e4ff7cd6b82",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":0},
            "size":{
              "width":350,
              "height":26},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db6a11730281417caf4c199b7b0a423a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":0},
                "size":{
                  "width":350,
                  "height":26},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u4.png"}},
{
          "id":"0171ba90f96d49fd9182f16d7a897861",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":351,
              "y":0},
            "size":{
              "width":49,
              "height":26},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e10991e0a68425290d8bfdd04e1a7f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":351,
                  "y":0},
                "size":{
                  "width":49,
                  "height":26},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u6.png"}},
{
          "id":"e2cb2ff3a94d40bc8170a9ad77611def",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF454B57},
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":400,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"647ef52fb8d844409c65c102153dbefb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF454B57},
                "location":{
                  "x":0,
                  "y":26},
                "size":{
                  "width":400,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/聊天界面/u0.png"}},
{
          "id":"af86842c31ec4a79bb2c501732009c9b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":38},
            "size":{
              "width":16,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 装修流程界面",
                      "target":{
                        "targetType":"page",
                        "url":"装修流程界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "start~":"images/忘记密码/u19_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/忘记密码/u19_line.png"}},
{
          "id":"6a9d4d8439f64147a90af4cd8b85ed78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":4,
              "y":71},
            "size":{
              "width":390,
              "height":397}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86e6280597db4a9f9dba33e7449186ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":4,
                  "y":71},
                "size":{
                  "width":390,
                  "height":397}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "169200fac2e1410b88047f7af4a5cee2":{
      "scriptId":"u0"},
    "f3df9305e6bd4a6fabb465e024b5a83d":{
      "scriptId":"u1"},
    "5fd8db4ec750414f83e48e4ff7cd6b82":{
      "scriptId":"u2"},
    "db6a11730281417caf4c199b7b0a423a":{
      "scriptId":"u3"},
    "0171ba90f96d49fd9182f16d7a897861":{
      "scriptId":"u4"},
    "7e10991e0a68425290d8bfdd04e1a7f8":{
      "scriptId":"u5"},
    "e2cb2ff3a94d40bc8170a9ad77611def":{
      "scriptId":"u6"},
    "647ef52fb8d844409c65c102153dbefb":{
      "scriptId":"u7"},
    "af86842c31ec4a79bb2c501732009c9b":{
      "scriptId":"u8"},
    "6a9d4d8439f64147a90af4cd8b85ed78":{
      "scriptId":"u9"},
    "86e6280597db4a9f9dba33e7449186ab":{
      "scriptId":"u10"}}});