$axure.loadCurrentPage({
  "url":"装修流程.html",
  "generationDate":new Date(1414464499216.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7e17ca26bc814e608bd395ee5f7d62ce",
    "type":"Axure:Page",
    "name":"装修流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"55871cbb8626492ea10ff617a0144f65",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":10},
            "size":{
              "width":794,
              "height":1487},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f6dc781ab6946c5b6d8548b60a2e61c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":10},
                "size":{
                  "width":794,
                  "height":1487},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.jpg"}},
{
          "id":"7b3b524242cb4097ac551c4bf95a2d8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":317},
            "size":{
              "width":640,
              "height":822},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ade89e622c14797a953210a1c4ac8ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":317},
                "size":{
                  "width":640,
                  "height":822},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u2.png"}},
{
          "id":"2c7a4ce3ef2f40e3ae16c15965267c4b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":1139},
            "size":{
              "width":640,
              "height":97},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"042f411927054d738141dc5f4f781b3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":1139},
                "size":{
                  "width":640,
                  "height":97},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"3d3cb1ae528b4a72b4fb4da52e9b9555",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":468,
              "y":1149},
            "size":{
              "width":39,
              "height":36},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d13725411c84c80a4a724f750c4c1b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":468,
                  "y":1149},
                "size":{
                  "width":39,
                  "height":36},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u6.png"}},
{
          "id":"2db8db7399d94503b026681f1b325082",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":1151},
            "size":{
              "width":39,
              "height":33},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc43b5aa782948baab011841402cb925",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":1151},
                "size":{
                  "width":39,
                  "height":33},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"9f5dc7d1bbc14d83ab26299a50208fa1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":275,
              "y":1153},
            "size":{
              "width":38,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da4159bba76541ccbcde2125f0e85b90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":275,
                  "y":1153},
                "size":{
                  "width":38,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u10.png"}},
{
          "id":"62664fd6ae364097863cc793172617df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":427,
              "y":1144},
            "size":{
              "width":123,
              "height":92},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7585de3b6274446b341607cf7d300b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":427,
                  "y":1144},
                "size":{
                  "width":123,
                  "height":92},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f73ac754fca4a51873d729fd8b86b25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":639,
              "y":1144},
            "size":{
              "width":123,
              "height":92},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d08c6b5297643f49af18dbf96de1e3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":639,
                  "y":1144},
                "size":{
                  "width":123,
                  "height":92},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我",
                      "target":{
                        "targetType":"page",
                        "url":"我.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf38470d0f614c4595be7efaa2eb91a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":232,
              "y":1139},
            "size":{
              "width":123,
              "height":92},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1873f098dc7f4715a5e841031abaacf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":232,
                  "y":1139},
                "size":{
                  "width":123,
                  "height":92},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天列表",
                      "target":{
                        "targetType":"page",
                        "url":"聊天列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ac436c76ccf4f98977de489c1186012",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":403},
            "size":{
              "width":639,
              "height":734}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89371aad518942379aac5a73a413238a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":403},
                "size":{
                  "width":639,
                  "height":734}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u18.png"}},
{
          "id":"189ce86fc07142148b3e435de3aa3f61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":310,
              "y":472},
            "size":{
              "width":486,
              "height":176},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4f9f2c96f874e87975e7663b6512b49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":310,
                  "y":472},
                "size":{
                  "width":486,
                  "height":176},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u20.png"}},
{
          "id":"fc1e636b053c4754bebbb3d96b8c754d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":1133},
            "size":{
              "width":639,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/装修流程/u22_line.png"}},
{
          "id":"f7b8cfc0d9c146bb8a36a41a0d3fdf1c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":403},
            "size":{
              "width":10,
              "height":734},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/装修流程/u23_line.png"}},
{
          "id":"0957d28591a44ee3b73849b4264ce4c3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":973},
            "size":{
              "width":102,
              "height":116},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ebec6114ef44da4b64251ed84ef10ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":973},
                "size":{
                  "width":102,
                  "height":116},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u24.png"}},
{
          "id":"6fb576575a7f46f0b85545ed69483df5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":733},
            "size":{
              "width":102,
              "height":116},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e47d09f26a04d889c816a0c3d35ce92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":733},
                "size":{
                  "width":102,
                  "height":116},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u24.png"}},
{
          "id":"5d12fa7bb27e4f36b32faf542e49d6ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":492},
            "size":{
              "width":102,
              "height":109},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b869fbc7f8184280879cefba797564d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":492},
                "size":{
                  "width":102,
                  "height":109},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u28.png"}},
{
          "id":"a1fb8a1f869642a9a135353fba2ff26b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"33px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF8F8F8},
            "location":{
              "x":180,
              "y":317},
            "size":{
              "width":639,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7652d6f4c15d493c92a387c18a205fae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"33px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF8F8F8},
                "location":{
                  "x":180,
                  "y":317},
                "size":{
                  "width":639,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u20.png"}},
{
          "id":"f5952933c9be4850acdb5105d306fda5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"bold",
            "location":{
              "x":200,
              "y":341},
            "size":{
              "width":38,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7bf69cc1c82494ba596cbef0e27412a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"bold",
                "location":{
                  "x":200,
                  "y":341},
                "size":{
                  "width":38,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 主页 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/装修流程/u32.png"}},
{
          "id":"db73919327c3466a8c6824915bbff2e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":606},
            "size":{
              "width":47,
              "height":36},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"783b9b0a61e949418df562d97f12ca44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":318,
                  "y":606},
                "size":{
                  "width":47,
                  "height":36},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u34.png"}},
{
          "id":"4a72c3365c224959b4297c72bd182f55",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xAF8DC153},
            "location":{
              "x":422,
              "y":514},
            "size":{
              "width":70,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b43a62ba40e842b5a00a6e6d2c7249e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xAF8DC153},
                "location":{
                  "x":422,
                  "y":514},
                "size":{
                  "width":70,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u36.png"}},
{
          "id":"968490f9e5ef4fa7a0ea5f4f1edadc98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xAFC9C9C9},
            "location":{
              "x":510,
              "y":514},
            "size":{
              "width":70,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e1965536b91499d9c5f7c0785b740bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xAFC9C9C9},
                "location":{
                  "x":510,
                  "y":514},
                "size":{
                  "width":70,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u38.png"}},
{
          "id":"feb98afe05664718a1a80ac17387414b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xAFCCCCCC},
            "location":{
              "x":598,
              "y":514},
            "size":{
              "width":70,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8ab4ee7fb194264ba805e9f7cc4900d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xAFCCCCCC},
                "location":{
                  "x":598,
                  "y":514},
                "size":{
                  "width":70,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u40.png"}},
{
          "id":"30dc00938aea4758afd4dd4ffcba5e54",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xAF967BDC},
            "location":{
              "x":332,
              "y":514},
            "size":{
              "width":70,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"997e88ae9c684c5f8b44512d8c3cad78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xAF967BDC},
                "location":{
                  "x":332,
                  "y":514},
                "size":{
                  "width":70,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 确定施工方式简介",
                      "target":{
                        "targetType":"page",
                        "url":"确定施工方式简介.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/装修流程/u42.png"}},
{
          "id":"d946e8ce737443d999519bdeaddce43f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":312,
              "y":602},
            "size":{
              "width":484,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ea1136deadc4682ba04d468d4536558",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":312,
                  "y":602},
                "size":{
                  "width":484,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u44.png"}},
{
          "id":"ef138b31e9934010996f1fc316c25454",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF6BB39D},
            "location":{
              "x":682,
              "y":604},
            "size":{
              "width":39,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e59c9d9c94c4005bd580c241f4967c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6BB39D},
                "location":{
                  "x":682,
                  "y":604},
                "size":{
                  "width":39,
                  "height":39},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u46.png"}},
{
          "id":"c17cc076f89a4d688b338733235ee388",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":686,
              "y":612},
            "size":{
              "width":29,
              "height":29},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4984ae0e46d946e4bdbe7cc0ba3d4953",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":686,
                  "y":612},
                "size":{
                  "width":29,
                  "height":29},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u48.png"}},
{
          "id":"b93faebccc974fa592fe0afb6df25ae5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF2E5C77},
            "location":{
              "x":744,
              "y":604},
            "size":{
              "width":39,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"024a8c90885244e4b02ca7251131a7cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2E5C77},
                "location":{
                  "x":744,
                  "y":604},
                "size":{
                  "width":39,
                  "height":39},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u50.png"}},
{
          "id":"1637650bc11a431787fc89ee561471fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":752,
              "y":612},
            "size":{
              "width":26,
              "height":26},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2311c59e1b894f5bb603febf4b4a7f12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":752,
                  "y":612},
                "size":{
                  "width":26,
                  "height":26},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u52.png"}},
{
          "id":"87cff15322794bcb88e7edd337c3dc2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"66px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":702,
              "y":554},
            "size":{
              "width":32,
              "height":76},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b49a0929ebff4b9a8e713788d3a1fa5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"66px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":702,
                  "y":554},
                "size":{
                  "width":32,
                  "height":76},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a70283e80600422799b77afbde011c28",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":310,
              "y":723},
            "size":{
              "width":486,
              "height":176},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02c178e157f84a3793d623eba9fc4753",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":310,
                  "y":723},
                "size":{
                  "width":486,
                  "height":176},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u20.png"}},
{
          "id":"8c3c0ea7de5040129f3930ca9a6885fa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":317,
              "y":856},
            "size":{
              "width":47,
              "height":36},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b6684fc1b6443e1b2140813ec01a584",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":317,
                  "y":856},
                "size":{
                  "width":47,
                  "height":36},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u34.png"}},
{
          "id":"0156931b5a5b4f37a601fcd94e81409b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xAFCCCCCC},
            "location":{
              "x":421,
              "y":764},
            "size":{
              "width":70,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9304b66c8c294d8d837bace8affc78cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xAFCCCCCC},
                "location":{
                  "x":421,
                  "y":764},
                "size":{
                  "width":70,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u40.png"}},
{
          "id":"8782b62e3716425b8f65da4b8ec8b1bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xAFCCCCCC},
            "location":{
              "x":331,
              "y":764},
            "size":{
              "width":70,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89573b9a52c3427da5ef887d743627a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xAFCCCCCC},
                "location":{
                  "x":331,
                  "y":764},
                "size":{
                  "width":70,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u40.png"}},
{
          "id":"b2ef368e0b934d21a4b1f52262c4fc0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":311,
              "y":852},
            "size":{
              "width":484,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72f230f8a3bd4a0484ccc7c36ecad210",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":311,
                  "y":852},
                "size":{
                  "width":484,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u44.png"}},
{
          "id":"2929312d686f44b39c2db1a0a906192e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF6BB39D},
            "location":{
              "x":681,
              "y":854},
            "size":{
              "width":39,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef8f1fb870be4b65a8bdded7cffd421e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6BB39D},
                "location":{
                  "x":681,
                  "y":854},
                "size":{
                  "width":39,
                  "height":39},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u46.png"}},
{
          "id":"783577b37f6d4d2dabe0cf230122e36e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":685,
              "y":862},
            "size":{
              "width":29,
              "height":29},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bea20cb610e24bb986b7a98013159021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":685,
                  "y":862},
                "size":{
                  "width":29,
                  "height":29},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u48.png"}},
{
          "id":"85762d84f857438a935fd0381a83bf92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF2E5C77},
            "location":{
              "x":743,
              "y":854},
            "size":{
              "width":39,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24a5f79b63b9424d8098c2044750b214",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2E5C77},
                "location":{
                  "x":743,
                  "y":854},
                "size":{
                  "width":39,
                  "height":39},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u50.png"}},
{
          "id":"92d7a847120d438d9aebe630ac923eee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":862},
            "size":{
              "width":26,
              "height":26},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"352c82f1a9744618bf2ed3ec29b367c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":862},
                "size":{
                  "width":26,
                  "height":26},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u52.png"}},
{
          "id":"b265f31e3f9f42058c03fe611b3c8e46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"66px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":701,
              "y":804},
            "size":{
              "width":32,
              "height":76},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdb4023cf5a24587a5b47b084aa412eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"66px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":701,
                  "y":804},
                "size":{
                  "width":32,
                  "height":76},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41b9a7ad54b74418a426dfce1a27dff8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":681,
              "y":602},
            "size":{
              "width":53,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fe8cc73ad0f40e3a80e27e2e0dbfdaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":681,
                  "y":602},
                "size":{
                  "width":53,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 聊天",
                      "target":{
                        "targetType":"page",
                        "url":"聊天.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"607de9f23855412f927025ce93ae62de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":311,
              "y":947},
            "size":{
              "width":486,
              "height":176},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7230def8b21a43d9af42b085c0163735",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":311,
                  "y":947},
                "size":{
                  "width":486,
                  "height":176},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u20.png"}},
{
          "id":"1c1d652c529a465c92581f86313e781f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":1080},
            "size":{
              "width":47,
              "height":36},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e8f98c76a954bf2943de7e3f52f60f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":318,
                  "y":1080},
                "size":{
                  "width":47,
                  "height":36},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u34.png"}},
{
          "id":"3cd2d6b635cb44abb37adcb6047ba8a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xAFCCCCCC},
            "location":{
              "x":422,
              "y":988},
            "size":{
              "width":70,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bab68e2670724e118b1f3a376e9d1585",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xAFCCCCCC},
                "location":{
                  "x":422,
                  "y":988},
                "size":{
                  "width":70,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u40.png"}},
{
          "id":"6912b630cc054cbe8849e78af2a4a6d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xAFCCCCCC},
            "location":{
              "x":332,
              "y":988},
            "size":{
              "width":70,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f71c5ccf5414dc09492b30efc5fda35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xAFCCCCCC},
                "location":{
                  "x":332,
                  "y":988},
                "size":{
                  "width":70,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u40.png"}},
{
          "id":"89b4ef98cbf84e0abdd801dbb31702b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":312,
              "y":1076},
            "size":{
              "width":484,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c736bc331df749b4b206ad8c7d31b1fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":312,
                  "y":1076},
                "size":{
                  "width":484,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u44.png"}},
{
          "id":"380cf0ba834e476e9446237e9483820f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF6BB39D},
            "location":{
              "x":682,
              "y":1078},
            "size":{
              "width":39,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0942b9d747e849398c4053b0f78fa174",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6BB39D},
                "location":{
                  "x":682,
                  "y":1078},
                "size":{
                  "width":39,
                  "height":39},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u46.png"}},
{
          "id":"30e4584ba06747dbbf83695a81c9629f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":686,
              "y":1086},
            "size":{
              "width":29,
              "height":29},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ea6589b655347a3bf962f63f0a9539e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":686,
                  "y":1086},
                "size":{
                  "width":29,
                  "height":29},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u48.png"}},
{
          "id":"45970e892af34876a404ba4cbf0e5338",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF2E5C77},
            "location":{
              "x":744,
              "y":1078},
            "size":{
              "width":39,
              "height":39},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8516148f895543de82c9dcc812331cff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2E5C77},
                "location":{
                  "x":744,
                  "y":1078},
                "size":{
                  "width":39,
                  "height":39},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u50.png"}},
{
          "id":"cac3e3c105304e3d97357ec23e6fac3c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":752,
              "y":1086},
            "size":{
              "width":26,
              "height":26},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e0e693f5a304227bf7f80ea32a19e9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":752,
                  "y":1086},
                "size":{
                  "width":26,
                  "height":26},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/装修流程/u52.png"}},
{
          "id":"915aa2d7d03543f9a38c3812cc2e9726",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"66px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":702,
              "y":1028},
            "size":{
              "width":32,
              "height":76},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5688fd17fcc540d68ce4e7d3492f000b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"66px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":702,
                  "y":1028},
                "size":{
                  "width":32,
                  "height":76},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "55871cbb8626492ea10ff617a0144f65":{
      "scriptId":"u0"},
    "0f6dc781ab6946c5b6d8548b60a2e61c":{
      "scriptId":"u1"},
    "7b3b524242cb4097ac551c4bf95a2d8e":{
      "scriptId":"u2"},
    "4ade89e622c14797a953210a1c4ac8ef":{
      "scriptId":"u3"},
    "2c7a4ce3ef2f40e3ae16c15965267c4b":{
      "scriptId":"u4"},
    "042f411927054d738141dc5f4f781b3e":{
      "scriptId":"u5"},
    "3d3cb1ae528b4a72b4fb4da52e9b9555":{
      "scriptId":"u6"},
    "8d13725411c84c80a4a724f750c4c1b4":{
      "scriptId":"u7"},
    "2db8db7399d94503b026681f1b325082":{
      "scriptId":"u8"},
    "dc43b5aa782948baab011841402cb925":{
      "scriptId":"u9"},
    "9f5dc7d1bbc14d83ab26299a50208fa1":{
      "scriptId":"u10"},
    "da4159bba76541ccbcde2125f0e85b90":{
      "scriptId":"u11"},
    "62664fd6ae364097863cc793172617df":{
      "scriptId":"u12"},
    "e7585de3b6274446b341607cf7d300b2":{
      "scriptId":"u13"},
    "5f73ac754fca4a51873d729fd8b86b25":{
      "scriptId":"u14"},
    "1d08c6b5297643f49af18dbf96de1e3e":{
      "scriptId":"u15"},
    "bf38470d0f614c4595be7efaa2eb91a7":{
      "scriptId":"u16"},
    "1873f098dc7f4715a5e841031abaacf7":{
      "scriptId":"u17"},
    "1ac436c76ccf4f98977de489c1186012":{
      "scriptId":"u18"},
    "89371aad518942379aac5a73a413238a":{
      "scriptId":"u19"},
    "189ce86fc07142148b3e435de3aa3f61":{
      "scriptId":"u20"},
    "a4f9f2c96f874e87975e7663b6512b49":{
      "scriptId":"u21"},
    "fc1e636b053c4754bebbb3d96b8c754d":{
      "scriptId":"u22"},
    "f7b8cfc0d9c146bb8a36a41a0d3fdf1c":{
      "scriptId":"u23"},
    "0957d28591a44ee3b73849b4264ce4c3":{
      "scriptId":"u24"},
    "4ebec6114ef44da4b64251ed84ef10ea":{
      "scriptId":"u25"},
    "6fb576575a7f46f0b85545ed69483df5":{
      "scriptId":"u26"},
    "3e47d09f26a04d889c816a0c3d35ce92":{
      "scriptId":"u27"},
    "5d12fa7bb27e4f36b32faf542e49d6ac":{
      "scriptId":"u28"},
    "b869fbc7f8184280879cefba797564d6":{
      "scriptId":"u29"},
    "a1fb8a1f869642a9a135353fba2ff26b":{
      "scriptId":"u30"},
    "7652d6f4c15d493c92a387c18a205fae":{
      "scriptId":"u31"},
    "f5952933c9be4850acdb5105d306fda5":{
      "scriptId":"u32"},
    "c7bf69cc1c82494ba596cbef0e27412a":{
      "scriptId":"u33"},
    "db73919327c3466a8c6824915bbff2e6":{
      "scriptId":"u34"},
    "783b9b0a61e949418df562d97f12ca44":{
      "scriptId":"u35"},
    "4a72c3365c224959b4297c72bd182f55":{
      "scriptId":"u36"},
    "b43a62ba40e842b5a00a6e6d2c7249e4":{
      "scriptId":"u37"},
    "968490f9e5ef4fa7a0ea5f4f1edadc98":{
      "scriptId":"u38"},
    "8e1965536b91499d9c5f7c0785b740bb":{
      "scriptId":"u39"},
    "feb98afe05664718a1a80ac17387414b":{
      "scriptId":"u40"},
    "a8ab4ee7fb194264ba805e9f7cc4900d":{
      "scriptId":"u41"},
    "30dc00938aea4758afd4dd4ffcba5e54":{
      "scriptId":"u42"},
    "997e88ae9c684c5f8b44512d8c3cad78":{
      "scriptId":"u43"},
    "d946e8ce737443d999519bdeaddce43f":{
      "scriptId":"u44"},
    "9ea1136deadc4682ba04d468d4536558":{
      "scriptId":"u45"},
    "ef138b31e9934010996f1fc316c25454":{
      "scriptId":"u46"},
    "6e59c9d9c94c4005bd580c241f4967c1":{
      "scriptId":"u47"},
    "c17cc076f89a4d688b338733235ee388":{
      "scriptId":"u48"},
    "4984ae0e46d946e4bdbe7cc0ba3d4953":{
      "scriptId":"u49"},
    "b93faebccc974fa592fe0afb6df25ae5":{
      "scriptId":"u50"},
    "024a8c90885244e4b02ca7251131a7cf":{
      "scriptId":"u51"},
    "1637650bc11a431787fc89ee561471fe":{
      "scriptId":"u52"},
    "2311c59e1b894f5bb603febf4b4a7f12":{
      "scriptId":"u53"},
    "87cff15322794bcb88e7edd337c3dc2a":{
      "scriptId":"u54"},
    "b49a0929ebff4b9a8e713788d3a1fa5f":{
      "scriptId":"u55"},
    "a70283e80600422799b77afbde011c28":{
      "scriptId":"u56"},
    "02c178e157f84a3793d623eba9fc4753":{
      "scriptId":"u57"},
    "8c3c0ea7de5040129f3930ca9a6885fa":{
      "scriptId":"u58"},
    "8b6684fc1b6443e1b2140813ec01a584":{
      "scriptId":"u59"},
    "0156931b5a5b4f37a601fcd94e81409b":{
      "scriptId":"u60"},
    "9304b66c8c294d8d837bace8affc78cf":{
      "scriptId":"u61"},
    "8782b62e3716425b8f65da4b8ec8b1bc":{
      "scriptId":"u62"},
    "89573b9a52c3427da5ef887d743627a4":{
      "scriptId":"u63"},
    "b2ef368e0b934d21a4b1f52262c4fc0f":{
      "scriptId":"u64"},
    "72f230f8a3bd4a0484ccc7c36ecad210":{
      "scriptId":"u65"},
    "2929312d686f44b39c2db1a0a906192e":{
      "scriptId":"u66"},
    "ef8f1fb870be4b65a8bdded7cffd421e":{
      "scriptId":"u67"},
    "783577b37f6d4d2dabe0cf230122e36e":{
      "scriptId":"u68"},
    "bea20cb610e24bb986b7a98013159021":{
      "scriptId":"u69"},
    "85762d84f857438a935fd0381a83bf92":{
      "scriptId":"u70"},
    "24a5f79b63b9424d8098c2044750b214":{
      "scriptId":"u71"},
    "92d7a847120d438d9aebe630ac923eee":{
      "scriptId":"u72"},
    "352c82f1a9744618bf2ed3ec29b367c9":{
      "scriptId":"u73"},
    "b265f31e3f9f42058c03fe611b3c8e46":{
      "scriptId":"u74"},
    "cdb4023cf5a24587a5b47b084aa412eb":{
      "scriptId":"u75"},
    "41b9a7ad54b74418a426dfce1a27dff8":{
      "scriptId":"u76"},
    "0fe8cc73ad0f40e3a80e27e2e0dbfdaf":{
      "scriptId":"u77"},
    "607de9f23855412f927025ce93ae62de":{
      "scriptId":"u78"},
    "7230def8b21a43d9af42b085c0163735":{
      "scriptId":"u79"},
    "1c1d652c529a465c92581f86313e781f":{
      "scriptId":"u80"},
    "6e8f98c76a954bf2943de7e3f52f60f2":{
      "scriptId":"u81"},
    "3cd2d6b635cb44abb37adcb6047ba8a0":{
      "scriptId":"u82"},
    "bab68e2670724e118b1f3a376e9d1585":{
      "scriptId":"u83"},
    "6912b630cc054cbe8849e78af2a4a6d3":{
      "scriptId":"u84"},
    "8f71c5ccf5414dc09492b30efc5fda35":{
      "scriptId":"u85"},
    "89b4ef98cbf84e0abdd801dbb31702b4":{
      "scriptId":"u86"},
    "c736bc331df749b4b206ad8c7d31b1fa":{
      "scriptId":"u87"},
    "380cf0ba834e476e9446237e9483820f":{
      "scriptId":"u88"},
    "0942b9d747e849398c4053b0f78fa174":{
      "scriptId":"u89"},
    "30e4584ba06747dbbf83695a81c9629f":{
      "scriptId":"u90"},
    "6ea6589b655347a3bf962f63f0a9539e":{
      "scriptId":"u91"},
    "45970e892af34876a404ba4cbf0e5338":{
      "scriptId":"u92"},
    "8516148f895543de82c9dcc812331cff":{
      "scriptId":"u93"},
    "cac3e3c105304e3d97357ec23e6fac3c":{
      "scriptId":"u94"},
    "9e0e693f5a304227bf7f80ea32a19e9f":{
      "scriptId":"u95"},
    "915aa2d7d03543f9a38c3812cc2e9726":{
      "scriptId":"u96"},
    "5688fd17fcc540d68ce4e7d3492f000b":{
      "scriptId":"u97"}}});