$axure.loadCurrentPage({
  "url":"相簿.html",
  "generationDate":new Date(1415687654332.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7ef8cecfb5af4a3398b7c05261bada4e",
    "type":"Axure:Page",
    "name":"相簿",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c4c69147d39142abaccd9713baa3542a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":102,
              "y":11},
            "size":{
              "width":794,
              "height":1487}},
          "adaptiveStyles":{
},
          "masterId":"984fa132bdee4430802a486dd3e5c298"},
{
          "id":"f9b324ec80984a69b2036fbf5540cbc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"33px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF8F8F8},
            "location":{
              "x":180,
              "y":317},
            "size":{
              "width":639,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14f18c7c19144057a7f5dfa3bbb7cd1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"33px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF8F8F8},
                "location":{
                  "x":180,
                  "y":317},
                "size":{
                  "width":639,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u20.png"}},
{
          "id":"e47bad088001404c81c1de1b45b68f8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":330},
            "size":{
              "width":64,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5c86d40c2f844be80700adfd11103e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":330},
                "size":{
                  "width":64,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/相簿/u23.png"}}]}},
  "masters":{
    "984fa132bdee4430802a486dd3e5c298":{
      "packageId":"984fa132bdee4430802a486dd3e5c298",
      "type":"Axure:Master",
      "name":"shoujixin",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0924992c31c149048016d672e5c7f726",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":794,
                "height":1487},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18279859f5f846ce8c3645a511e3061b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":794,
                    "height":1487},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u0.jpg"}},
{
            "id":"70f92109e52a40af94df453ebb3e8fd2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":307},
              "size":{
                "width":640,
                "height":822},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1a0f733bad824f2595138b3ed7ed226f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":80,
                    "y":307},
                  "size":{
                    "width":640,
                    "height":822},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u2.png"}},
{
            "id":"afaeff7a64e54c80962de48a01e9fe2c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":1129},
              "size":{
                "width":640,
                "height":97},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"74df996240be4f2eae72b660a9d138d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":80,
                    "y":1129},
                  "size":{
                    "width":640,
                    "height":97},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u4.png"}},
{
            "id":"ad28bbac596b43b58a7b09fd8c61d066",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":368,
                "y":1139},
              "size":{
                "width":39,
                "height":36},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fd172ca0c7684ee3a771250caa2a4708",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":368,
                    "y":1139},
                  "size":{
                    "width":39,
                    "height":36},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u6.png"}},
{
            "id":"00913d450cdc4fcaa0b8e0987daf0158",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":580,
                "y":1141},
              "size":{
                "width":39,
                "height":33},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"23e12321df4e4b8e918b93a4238c0b2e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":580,
                    "y":1141},
                  "size":{
                    "width":39,
                    "height":33},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u8.png"}},
{
            "id":"6aff273e7ae443acaad54ef5d53ef650",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":175,
                "y":1143},
              "size":{
                "width":38,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"895a51871df84fdeb64de494f9ded835",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":175,
                    "y":1143},
                  "size":{
                    "width":38,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u10.png"}},
{
            "id":"f64805ae112045e2acbffd535c1532ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":327,
                "y":1134},
              "size":{
                "width":123,
                "height":92},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"46456e5bf1a64ccf8f309dbbddbdde36",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":327,
                    "y":1134},
                  "size":{
                    "width":123,
                    "height":92},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"153adc10da0545eb85d07f4f4553ba83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":539,
                "y":1134},
              "size":{
                "width":123,
                "height":92},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2071049e0e8d4b418468c9a8514ed7e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":539,
                    "y":1134},
                  "size":{
                    "width":123,
                    "height":92},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登陆页",
                        "target":{
                          "targetType":"page",
                          "url":"登陆页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bb67617ebb764a5ba40a60393669df03",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":132,
                "y":1129},
              "size":{
                "width":123,
                "height":92},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"35fcb7f3ba564c56a8900c8c914f3812",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":132,
                    "y":1129},
                  "size":{
                    "width":123,
                    "height":92},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 聊天",
                        "target":{
                          "targetType":"page",
                          "url":"聊天.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ca7ebea22b8a48e9a088034eb7d63cfb",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFF0000},
              "location":{
                "x":223,
                "y":1139},
              "size":{
                "width":11,
                "height":11},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24509502b78240de82bb50d987c9e129",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF0000},
                  "location":{
                    "x":223,
                    "y":1139},
                  "size":{
                    "width":11,
                    "height":11},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/确定施工方式简介/u19.png"}}]}}},
  "objectPaths":{
    "c4c69147d39142abaccd9713baa3542a":{
      "scriptId":"u0",
      "0924992c31c149048016d672e5c7f726":{
        "scriptId":"u1"},
      "18279859f5f846ce8c3645a511e3061b":{
        "scriptId":"u2"},
      "70f92109e52a40af94df453ebb3e8fd2":{
        "scriptId":"u3"},
      "1a0f733bad824f2595138b3ed7ed226f":{
        "scriptId":"u4"},
      "afaeff7a64e54c80962de48a01e9fe2c":{
        "scriptId":"u5"},
      "74df996240be4f2eae72b660a9d138d3":{
        "scriptId":"u6"},
      "ad28bbac596b43b58a7b09fd8c61d066":{
        "scriptId":"u7"},
      "fd172ca0c7684ee3a771250caa2a4708":{
        "scriptId":"u8"},
      "00913d450cdc4fcaa0b8e0987daf0158":{
        "scriptId":"u9"},
      "23e12321df4e4b8e918b93a4238c0b2e":{
        "scriptId":"u10"},
      "6aff273e7ae443acaad54ef5d53ef650":{
        "scriptId":"u11"},
      "895a51871df84fdeb64de494f9ded835":{
        "scriptId":"u12"},
      "f64805ae112045e2acbffd535c1532ea":{
        "scriptId":"u13"},
      "46456e5bf1a64ccf8f309dbbddbdde36":{
        "scriptId":"u14"},
      "153adc10da0545eb85d07f4f4553ba83":{
        "scriptId":"u15"},
      "2071049e0e8d4b418468c9a8514ed7e2":{
        "scriptId":"u16"},
      "bb67617ebb764a5ba40a60393669df03":{
        "scriptId":"u17"},
      "35fcb7f3ba564c56a8900c8c914f3812":{
        "scriptId":"u18"},
      "ca7ebea22b8a48e9a088034eb7d63cfb":{
        "scriptId":"u19"},
      "24509502b78240de82bb50d987c9e129":{
        "scriptId":"u20"}},
    "f9b324ec80984a69b2036fbf5540cbc7":{
      "scriptId":"u21"},
    "14f18c7c19144057a7f5dfa3bbb7cd1a":{
      "scriptId":"u22"},
    "e47bad088001404c81c1de1b45b68f8a":{
      "scriptId":"u23"},
    "f5c86d40c2f844be80700adfd11103e4":{
      "scriptId":"u24"}}});