$axure.loadCurrentPage({
  "url":"登录界面.html",
  "generationDate":new Date(1417506160218.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ba92c6acdae34005832ba1aeb1e166e2",
    "type":"Axure:Page",
    "name":"登录界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"584083f8eb6b464cb7dd607c266b45e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":400,
              "height":538},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3387942e74554d0a899052d0b005b5b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "location":{
                  "x":0,
                  "y":26},
                "size":{
                  "width":400,
                  "height":538},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u0.png"}},
{
          "id":"f446b5f83a3c4f8581ea2bd4cfad9be0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":82,
              "y":233},
            "size":{
              "width":238,
              "height":134},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd9ca2cd78794c1c868cb7df33a9aa57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":82,
                  "y":233},
                "size":{
                  "width":238,
                  "height":134},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u2.png"}},
{
          "id":"f9ae18bb933844ef95e514ae8d901adf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":0},
            "size":{
              "width":350,
              "height":26},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19e949fdecd54b37befa996579db3b10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":0},
                "size":{
                  "width":350,
                  "height":26},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u4.png"}},
{
          "id":"e2b8bc725a6c455fbd0c56c9627b9544",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":351,
              "y":0},
            "size":{
              "width":49,
              "height":26},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"629b400ba602479cb381fcbe6df88681",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":351,
                  "y":0},
                "size":{
                  "width":49,
                  "height":26},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u6.png"}},
{
          "id":"1129a37276414bab902116aa24c7f7a1",
          "label":"用户名",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":251},
            "size":{
              "width":149,
              "height":17}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 键盘,<br>隐藏 错误提示,<br>提示状态信息",
                      "objectsToFades":[{
                          "objectPath":["558a17bb23a643c3905530540a040fd3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f54e160a958349dc96fe3dac2ac80522"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["69ecc30733a34a7897229b128767704a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 用户名 = &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["1129a37276414bab902116aa24c7f7a1"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"用例 1<br> (If 文字于 用户名 = &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["1129a37276414bab902116aa24c7f7a1"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 用户名 = &quot;手机号码&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["1129a37276414bab902116aa24c7f7a1"]},
{
                                "exprType":"stringLiteral",
                                "value":"手机号码",
                                "stos":[]}]}]}},
{
                      "action":"fadeWidget",
                      "description":"隐藏 提示状态信息,<br>错误提示,<br>键盘",
                      "objectsToFades":[{
                          "objectPath":["69ecc30733a34a7897229b128767704a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f54e160a958349dc96fe3dac2ac80522"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["558a17bb23a643c3905530540a040fd3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"用例 2<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 键盘",
                      "objectsToFades":[{
                          "objectPath":["558a17bb23a643c3905530540a040fd3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "placeholderText":"手机号码"},
{
          "id":"76eae2d9ca934bed9aed373022669e41",
          "label":"密码",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":289},
            "size":{
              "width":149,
              "height":17}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 键盘",
                      "objectsToFades":[{
                          "objectPath":["558a17bb23a643c3905530540a040fd3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 密码 = &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["76eae2d9ca934bed9aed373022669e41"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"用例 1<br> (If 文字于 密码 = &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["76eae2d9ca934bed9aed373022669e41"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 密码 = &quot;密码&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["76eae2d9ca934bed9aed373022669e41"]},
{
                                "exprType":"stringLiteral",
                                "value":"密码",
                                "stos":[]}]}]}},
{
                      "action":"fadeWidget",
                      "description":"隐藏 键盘,<br>提示状态信息,<br>错误提示",
                      "objectsToFades":[{
                          "objectPath":["558a17bb23a643c3905530540a040fd3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["69ecc30733a34a7897229b128767704a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f54e160a958349dc96fe3dac2ac80522"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"用例 2<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 键盘",
                      "objectsToFades":[{
                          "objectPath":["558a17bb23a643c3905530540a040fd3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "placeholderText":"密码"},
{
          "id":"9e6bfdd216154c80be1a3b9d378bdee5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":159,
              "y":325},
            "size":{
              "width":54,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0x93666666},
            "cornerRadiusTopLeft":"5",
            "outerShadow":{
              "on":false,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":3,
              "color":{
                "r":204,
                "g":204,
                "b":204,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13acb7457bf64da7b6c297dafdab03e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":159,
                  "y":325},
                "size":{
                  "width":54,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x93666666},
                "cornerRadiusTopLeft":"5",
                "outerShadow":{
                  "on":false,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":3,
                  "color":{
                    "r":204,
                    "g":204,
                    "b":204,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If 文字于 用户名 = &quot;手机号码&quot; 和 文字于 密码 = &quot;请输入密码&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["1129a37276414bab902116aa24c7f7a1"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"手机号码",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["76eae2d9ca934bed9aed373022669e41"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"请输入密码",
                        "stos":[]}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 提示状态信息",
                      "objectsToFades":[{
                          "objectPath":["69ecc30733a34a7897229b128767704a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 错误提示 to 不能为空",
                      "panelsToStates":[{
                          "panelPath":["f54e160a958349dc96fe3dac2ac80522"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 错误提示,<br>隐藏 提示状态信息",
                      "objectsToFades":[{
                          "objectPath":["f54e160a958349dc96fe3dac2ac80522"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["69ecc30733a34a7897229b128767704a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"用例 5<br> (Else If 文字于 用户名 ≠ &quot;123456&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"!=",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["1129a37276414bab902116aa24c7f7a1"]}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"123456",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 错误提示 to 用户名错误，请输入用户名",
                      "panelsToStates":[{
                          "panelPath":["f54e160a958349dc96fe3dac2ac80522"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 错误提示,<br>隐藏 提示状态信息,<br>键盘",
                      "objectsToFades":[{
                          "objectPath":["69ecc30733a34a7897229b128767704a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f54e160a958349dc96fe3dac2ac80522"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["558a17bb23a643c3905530540a040fd3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"用例 2<br> (Else If 文字于 密码 = &quot;&quot; 和 文字于 用户名 ≠ &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["76eae2d9ca934bed9aed373022669e41"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"!=",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["1129a37276414bab902116aa24c7f7a1"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 错误提示 to 密码错误，请输入密码",
                      "panelsToStates":[{
                          "panelPath":["f54e160a958349dc96fe3dac2ac80522"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 错误提示,<br>隐藏 键盘",
                      "objectsToFades":[{
                          "objectPath":["f54e160a958349dc96fe3dac2ac80522"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["558a17bb23a643c3905530540a040fd3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"用例 3<br> (Else If 文字于 用户名 = &quot;123456&quot; 和 文字于 密码 ≠ &quot;123456&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["1129a37276414bab902116aa24c7f7a1"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"123456",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"!=",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["76eae2d9ca934bed9aed373022669e41"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"123456",
                        "stos":[]}}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 错误提示 to 密码错误，请输入密码",
                      "panelsToStates":[{
                          "panelPath":["f54e160a958349dc96fe3dac2ac80522"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 错误提示,<br>隐藏 键盘",
                      "objectsToFades":[{
                          "objectPath":["f54e160a958349dc96fe3dac2ac80522"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["558a17bb23a643c3905530540a040fd3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"用例 4<br> (Else If 文字于 用户名 = &quot;123456&quot; 和 文字于 密码 = &quot;123456&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"&&",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["1129a37276414bab902116aa24c7f7a1"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"123456",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["76eae2d9ca934bed9aed373022669e41"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"123456",
                        "stos":[]}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 提示状态信息 弹出效果",
                      "objectsToFades":[{
                          "objectPath":["69ecc30733a34a7897229b128767704a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"flyout"}}}]},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 装修流程界面",
                      "target":{
                        "targetType":"page",
                        "url":"装修流程界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseUp":{
              "description":"OnMouseUp",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 提示状态信息",
                      "objectsToFades":[{
                          "objectPath":["69ecc30733a34a7897229b128767704a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录界面/u10.png"}},
{
          "id":"1740fa22e6544c029ea3f91d4a2630f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":223,
              "y":327},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0210431331014858a40e2d13dcd15a16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":223,
                  "y":327},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 忘记密码",
                      "target":{
                        "targetType":"page",
                        "url":"忘记密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69ecc30733a34a7897229b128767704a",
          "label":"提示状态信息",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":1,
              "y":26},
            "size":{
              "width":399,
              "height":22},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"40dbad8d8c84404281575702f8eb0b75",
              "label":"正在登录",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d894f3ce900a459784b1d72b01628315",
                  "label":"",
                  "parentDynamicPanel":"69ecc30733a34a7897229b128767704a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xDD454B57},
                    "size":{
                      "width":400,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c0ccfe2554eb483b98c968c69bad7e67",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"69ecc30733a34a7897229b128767704a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xDD454B57},
                        "size":{
                          "width":400,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录界面/u15.png"}},
{
                  "id":"01370f2316c042da8a2c6295ee856985",
                  "label":"",
                  "parentDynamicPanel":"69ecc30733a34a7897229b128767704a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":176,
                      "y":3},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e60c475c55594939bfe4181f6463d252",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"69ecc30733a34a7897229b128767704a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":176,
                          "y":3},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3236fa1825f541109e1110fef902150b",
                  "label":"",
                  "parentDynamicPanel":"69ecc30733a34a7897229b128767704a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF,
                      "opacity":0},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":166,
                      "y":7},
                    "size":{
                      "width":8,
                      "height":8},
                    "borderWidth":"2",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7ac2b7fdea2540718cb661a8221ac397",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"69ecc30733a34a7897229b128767704a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF,
                          "opacity":0},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":166,
                          "y":7},
                        "size":{
                          "width":8,
                          "height":8},
                        "borderWidth":"2",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录界面/u19.png"}}]}]},
{
          "id":"b7b070fb871b4b7e960f2b187cce6a1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":142,
              "y":132},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"946f57f5888b4ef9aa54f99089bb6382",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":142,
                  "y":132},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03744fc417d54e7a9b4fa634bcbf6bb4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":86},
            "size":{
              "width":120,
              "height":103}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25a18486dd4247b9a81a0e02229a1893",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":86},
                "size":{
                  "width":120,
                  "height":103}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u23.png"}},
{
          "id":"558a17bb23a643c3905530540a040fd3",
          "label":"键盘",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":1,
              "y":353},
            "size":{
              "width":399,
              "height":211},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"83ba66c35ca44b1b844e0c81cb4e6cc0",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ef24cf1fb156434184041d2fa975c7c4",
                  "label":"",
                  "parentDynamicPanel":"558a17bb23a643c3905530540a040fd3",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":13},
                    "size":{
                      "width":399,
                      "height":200},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"245f7e10c6094a6f901c8813a7249691",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"558a17bb23a643c3905530540a040fd3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":1,
                          "y":13},
                        "size":{
                          "width":399,
                          "height":200},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录界面/u26.png"}}]}]},
{
          "id":"f54e160a958349dc96fe3dac2ac80522",
          "label":"错误提示",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":399,
              "height":538},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"39d4a75bf6684427a70f855ab8f3c39c",
              "label":"不能为空",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a29959acfc5347598e0ccda42af95385",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x51FFFFFF},
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":400,
                      "height":539},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"328a31ee7b45490ba454c72253f02aad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x51FFFFFF},
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":400,
                          "height":539},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录界面/u29.png"}},
{
                  "id":"698e2a400ed9404daefb1d9e157a714d",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":81,
                      "y":198},
                    "size":{
                      "width":222,
                      "height":160},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "outerShadow":{
                      "on":true,
                      "offsetX":2,
                      "offsetY":2,
                      "blurRadius":2,
                      "color":{
                        "r":153,
                        "g":153,
                        "b":153,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eea6d73c5ed7451ebded4b25ff274b9c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":81,
                          "y":198},
                        "size":{
                          "width":222,
                          "height":160},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "outerShadow":{
                          "on":true,
                          "offsetX":2,
                          "offsetY":2,
                          "blurRadius":2,
                          "color":{
                            "r":153,
                            "g":153,
                            "b":153,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录界面/u31.png"}},
{
                  "id":"790df3602c01447c9265a6854583dbf2",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":102,
                      "y":241},
                    "size":{
                      "width":178,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/登录界面/u33_line.png"}},
{
                  "id":"133cd87c09e346ca80c2bf2857bcbf05",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":102,
                      "y":296},
                    "size":{
                      "width":178,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/登录界面/u33_line.png"}},
{
                  "id":"86bdf0e149404eecb1d66714e302d06a",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "location":{
                      "x":102,
                      "y":218},
                    "size":{
                      "width":73,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7dfce66ebd9e46eca5df64dfcf9cc1ec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "location":{
                          "x":102,
                          "y":218},
                        "size":{
                          "width":73,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"57f4ec9124354b20ad3a7e2b2de25e63",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":102,
                      "y":265},
                    "size":{
                      "width":131,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"03fe32ec2bd14527b1372e73c1848ff0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":102,
                          "y":265},
                        "size":{
                          "width":131,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6ee66b9638924d8092502670e7cd0b7a",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "location":{
                      "x":156,
                      "y":316},
                    "size":{
                      "width":48,
                      "height":22},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"48944c644d584bb6a02de1342c8d055b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "location":{
                          "x":156,
                          "y":316},
                        "size":{
                          "width":48,
                          "height":22},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 登录界面",
                              "target":{
                                "targetType":"page",
                                "url":"登录界面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/登录界面/u39.png"}}]},
{
              "id":"d8ea3e17d9ac487cbb4b26ef57358e03",
              "label":"用户名错误，请输入用户名",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d79da6e91ba345e3a3ca0e76899743d6",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x51FFFFFF},
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":400,
                      "height":539},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9de238b8be9d48a6865803f5505acd2f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x51FFFFFF},
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":400,
                          "height":539},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录界面/u29.png"}},
{
                  "id":"67f0748bcbd54c2fb4d6c5e4cbcefcad",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":81,
                      "y":198},
                    "size":{
                      "width":222,
                      "height":160},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "outerShadow":{
                      "on":true,
                      "offsetX":2,
                      "offsetY":2,
                      "blurRadius":2,
                      "color":{
                        "r":153,
                        "g":153,
                        "b":153,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd5612b4f51a4bf9a707b54afe74142b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":81,
                          "y":198},
                        "size":{
                          "width":222,
                          "height":160},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "outerShadow":{
                          "on":true,
                          "offsetX":2,
                          "offsetY":2,
                          "blurRadius":2,
                          "color":{
                            "r":153,
                            "g":153,
                            "b":153,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录界面/u31.png"}},
{
                  "id":"3b8df67f7d864333993c3e9e291c96a3",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":102,
                      "y":241},
                    "size":{
                      "width":178,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/登录界面/u33_line.png"}},
{
                  "id":"eab6ac5a04ab4fc181f9ebae54485236",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":102,
                      "y":296},
                    "size":{
                      "width":178,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/登录界面/u33_line.png"}},
{
                  "id":"731ee2c499e24094a091fcf9f5206e3a",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "location":{
                      "x":102,
                      "y":218},
                    "size":{
                      "width":73,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e556b2219282409aad3429b07741a21e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "location":{
                          "x":102,
                          "y":218},
                        "size":{
                          "width":73,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"28930c5ae32c4d9a948035a7b1784c8b",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":102,
                      "y":265},
                    "size":{
                      "width":183,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"08a203c403fb48bc8307cc1b39676906",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":102,
                          "y":265},
                        "size":{
                          "width":183,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2de31389729548ae88544011e7b1fa96",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "location":{
                      "x":156,
                      "y":316},
                    "size":{
                      "width":48,
                      "height":22},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d7ee6211b5994fca9899e75054326675",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "location":{
                          "x":156,
                          "y":316},
                        "size":{
                          "width":48,
                          "height":22},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 登录界面",
                              "target":{
                                "targetType":"page",
                                "url":"登录界面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/登录界面/u39.png"}}]},
{
              "id":"6ee8190d4bc74504a3cd045eb6abf544",
              "label":"密码错误，请输入密码",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8bbc345277b147818dff211774287fc4",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x51FFFFFF},
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":400,
                      "height":539},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a3280e5387354ce08fa4c3263b197484",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x51FFFFFF},
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":400,
                          "height":539},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录界面/u29.png"}},
{
                  "id":"2bcac9ddef20416ab7312f0c49bebfed",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":81,
                      "y":198},
                    "size":{
                      "width":222,
                      "height":160},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "outerShadow":{
                      "on":true,
                      "offsetX":2,
                      "offsetY":2,
                      "blurRadius":2,
                      "color":{
                        "r":153,
                        "g":153,
                        "b":153,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6f1864c9c25b4a72ac8ad38788b286ec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":81,
                          "y":198},
                        "size":{
                          "width":222,
                          "height":160},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "outerShadow":{
                          "on":true,
                          "offsetX":2,
                          "offsetY":2,
                          "blurRadius":2,
                          "color":{
                            "r":153,
                            "g":153,
                            "b":153,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录界面/u31.png"}},
{
                  "id":"fca4e83a701c42f3aab4b9fbf2a87142",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":102,
                      "y":241},
                    "size":{
                      "width":178,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/登录界面/u33_line.png"}},
{
                  "id":"c4092eb7c58a414f812c966f49ef63ee",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":102,
                      "y":296},
                    "size":{
                      "width":178,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/登录界面/u33_line.png"}},
{
                  "id":"569958feb2a145aebc5a859191e104b4",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "location":{
                      "x":102,
                      "y":218},
                    "size":{
                      "width":73,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f7e30fb519e749e990e1627af68f7cf4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "location":{
                          "x":102,
                          "y":218},
                        "size":{
                          "width":73,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b2a7fe9c8e5d402fa113e7fd808a903d",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":102,
                      "y":265},
                    "size":{
                      "width":183,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"41e77744b23c4bebaa6d2cdf8af7e883",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":102,
                          "y":265},
                        "size":{
                          "width":183,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"956e555aad614f1aaec4ddf162744047",
                  "label":"",
                  "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "location":{
                      "x":156,
                      "y":316},
                    "size":{
                      "width":48,
                      "height":22},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d7e24726234f4832885b75f8daf63c02",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f54e160a958349dc96fe3dac2ac80522",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "location":{
                          "x":156,
                          "y":316},
                        "size":{
                          "width":48,
                          "height":22},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 登录界面",
                              "target":{
                                "targetType":"page",
                                "url":"登录界面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/登录界面/u39.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "584083f8eb6b464cb7dd607c266b45e7":{
      "scriptId":"u0"},
    "3387942e74554d0a899052d0b005b5b9":{
      "scriptId":"u1"},
    "f446b5f83a3c4f8581ea2bd4cfad9be0":{
      "scriptId":"u2"},
    "bd9ca2cd78794c1c868cb7df33a9aa57":{
      "scriptId":"u3"},
    "f9ae18bb933844ef95e514ae8d901adf":{
      "scriptId":"u4"},
    "19e949fdecd54b37befa996579db3b10":{
      "scriptId":"u5"},
    "e2b8bc725a6c455fbd0c56c9627b9544":{
      "scriptId":"u6"},
    "629b400ba602479cb381fcbe6df88681":{
      "scriptId":"u7"},
    "1129a37276414bab902116aa24c7f7a1":{
      "scriptId":"u8"},
    "76eae2d9ca934bed9aed373022669e41":{
      "scriptId":"u9"},
    "9e6bfdd216154c80be1a3b9d378bdee5":{
      "scriptId":"u10"},
    "13acb7457bf64da7b6c297dafdab03e0":{
      "scriptId":"u11"},
    "1740fa22e6544c029ea3f91d4a2630f8":{
      "scriptId":"u12"},
    "0210431331014858a40e2d13dcd15a16":{
      "scriptId":"u13"},
    "69ecc30733a34a7897229b128767704a":{
      "scriptId":"u14"},
    "d894f3ce900a459784b1d72b01628315":{
      "scriptId":"u15"},
    "c0ccfe2554eb483b98c968c69bad7e67":{
      "scriptId":"u16"},
    "01370f2316c042da8a2c6295ee856985":{
      "scriptId":"u17"},
    "e60c475c55594939bfe4181f6463d252":{
      "scriptId":"u18"},
    "3236fa1825f541109e1110fef902150b":{
      "scriptId":"u19"},
    "7ac2b7fdea2540718cb661a8221ac397":{
      "scriptId":"u20"},
    "b7b070fb871b4b7e960f2b187cce6a1b":{
      "scriptId":"u21"},
    "946f57f5888b4ef9aa54f99089bb6382":{
      "scriptId":"u22"},
    "03744fc417d54e7a9b4fa634bcbf6bb4":{
      "scriptId":"u23"},
    "25a18486dd4247b9a81a0e02229a1893":{
      "scriptId":"u24"},
    "558a17bb23a643c3905530540a040fd3":{
      "scriptId":"u25"},
    "ef24cf1fb156434184041d2fa975c7c4":{
      "scriptId":"u26"},
    "245f7e10c6094a6f901c8813a7249691":{
      "scriptId":"u27"},
    "f54e160a958349dc96fe3dac2ac80522":{
      "scriptId":"u28"},
    "a29959acfc5347598e0ccda42af95385":{
      "scriptId":"u29"},
    "328a31ee7b45490ba454c72253f02aad":{
      "scriptId":"u30"},
    "698e2a400ed9404daefb1d9e157a714d":{
      "scriptId":"u31"},
    "eea6d73c5ed7451ebded4b25ff274b9c":{
      "scriptId":"u32"},
    "790df3602c01447c9265a6854583dbf2":{
      "scriptId":"u33"},
    "133cd87c09e346ca80c2bf2857bcbf05":{
      "scriptId":"u34"},
    "86bdf0e149404eecb1d66714e302d06a":{
      "scriptId":"u35"},
    "7dfce66ebd9e46eca5df64dfcf9cc1ec":{
      "scriptId":"u36"},
    "57f4ec9124354b20ad3a7e2b2de25e63":{
      "scriptId":"u37"},
    "03fe32ec2bd14527b1372e73c1848ff0":{
      "scriptId":"u38"},
    "6ee66b9638924d8092502670e7cd0b7a":{
      "scriptId":"u39"},
    "48944c644d584bb6a02de1342c8d055b":{
      "scriptId":"u40"},
    "d79da6e91ba345e3a3ca0e76899743d6":{
      "scriptId":"u41"},
    "9de238b8be9d48a6865803f5505acd2f":{
      "scriptId":"u42"},
    "67f0748bcbd54c2fb4d6c5e4cbcefcad":{
      "scriptId":"u43"},
    "cd5612b4f51a4bf9a707b54afe74142b":{
      "scriptId":"u44"},
    "3b8df67f7d864333993c3e9e291c96a3":{
      "scriptId":"u45"},
    "eab6ac5a04ab4fc181f9ebae54485236":{
      "scriptId":"u46"},
    "731ee2c499e24094a091fcf9f5206e3a":{
      "scriptId":"u47"},
    "e556b2219282409aad3429b07741a21e":{
      "scriptId":"u48"},
    "28930c5ae32c4d9a948035a7b1784c8b":{
      "scriptId":"u49"},
    "08a203c403fb48bc8307cc1b39676906":{
      "scriptId":"u50"},
    "2de31389729548ae88544011e7b1fa96":{
      "scriptId":"u51"},
    "d7ee6211b5994fca9899e75054326675":{
      "scriptId":"u52"},
    "8bbc345277b147818dff211774287fc4":{
      "scriptId":"u53"},
    "a3280e5387354ce08fa4c3263b197484":{
      "scriptId":"u54"},
    "2bcac9ddef20416ab7312f0c49bebfed":{
      "scriptId":"u55"},
    "6f1864c9c25b4a72ac8ad38788b286ec":{
      "scriptId":"u56"},
    "fca4e83a701c42f3aab4b9fbf2a87142":{
      "scriptId":"u57"},
    "c4092eb7c58a414f812c966f49ef63ee":{
      "scriptId":"u58"},
    "569958feb2a145aebc5a859191e104b4":{
      "scriptId":"u59"},
    "f7e30fb519e749e990e1627af68f7cf4":{
      "scriptId":"u60"},
    "b2a7fe9c8e5d402fa113e7fd808a903d":{
      "scriptId":"u61"},
    "41e77744b23c4bebaa6d2cdf8af7e883":{
      "scriptId":"u62"},
    "956e555aad614f1aaec4ddf162744047":{
      "scriptId":"u63"},
    "d7e24726234f4832885b75f8daf63c02":{
      "scriptId":"u64"}}});